### ISSUE TITLE
MegaParsec or Megaparsec?

### ISSUE THREAD

**Issue by neongreen** [mrkkrp/megaparsec#10]
Pros of MegaParsec:

* It's more obvious that it's related to Parsec. (Is it actually a good thing?)

Cons of MegaParsec:

* “parsec” is a unit of measurement, so it shouldn't be capitalised in “megaparsec”.
* “Megaparsec” is consistent with “Attoparsec” and “Picoparsec”, 2 other libraries with “parsec” in them.
* I suspect (but can't prove) that everyone who uses ThisCapitalisation in nir product's name regrets it when the product becomes popular.

**Comment by mrkkrp** [comment]
I'm not against renaming, it would be quite easy to rename the thing on this early stage of development. One more cons of "Megaparsec" is that it's easier to type. I would like to hear other opinions too. @albertnetymk, what do you think about the name?

**Comment by albertnetymk** [comment]
I have no strong opinion on this. Personally, I prefer `MegaParsec`, for it's obvious that it's related to `Parsec`, as mentioned by OP, but just better, active maintenance, better test coverage... For other examples, `Attoparsec`, and its fork, `Picoparsec` have different trade-off from `Parsec`, so I would rather not say that `megaparsec` falls in the same camp as them.

**Comment by mrkkrp** [comment]
@albertnetymk, thank you, I see your point. Although `megaparsec` will always be derivative from `Parsec`, I think now that indeed `Megaparsec` is easier to type and it looks better, as one word.

So, if there is no objections I will rename it to `Megaparsec`.
