### ISSUE TITLE
Number lexer

### ISSUE THREAD

**Issue by minad** [mrkkrp/megaparsec#101]
Hi @mrkkrp,

concerning the number lexer, I would like to have a few things :)
Would you accept patches concerning that?
1. Parsing arbitrary prefixes and bases. Your `nump`goes in that direction, however it is restricted too much by haskell syntax. What about a combinator like `numberBase base`? The base can be anything up to 16. The prefix can then be parsed separately with `string'`
2. Supporting `_` in the number strings, e.g., 3.141_592_653_596, 1_000_000_000

While 1. is a simple addition, I don't know how one could add 2. Maybe by passing an additional digit parser?

Daniel

**Comment by mrkkrp** [comment]
We do not currently parse prefixes as part of parsers that are shipped with the library, [see here](https://hackage.haskell.org/package/megaparsec-4.4.0/docs/Text-Megaparsec-Lexer.html#v:hexadecimal). Parsing of numbers with arbitrary base may be added, there is nothing wrong with that idea.

Your second proposition looks like rather a custom thing, for which you can write your own parser that accepts underscores. I don't think `1_000_000` notation is used frequently (in fact, I see this sort of notation for the first time; I think spaces are used much more frequently as delimiters). Also, I've seen something like this `1 0000 0000`, so it's a custom thing that should be writen by user for concrete use-case, IMO.

**Comment by minad** [comment]
Yes, you don't. However you use read and add the prefix for the parsing step internally. I meant we could switch to a more general string to integer converter. This would allow the addition of the aforementioned parser.

Actually, the underscore is not that uncommon. See for example http://docs.oracle.com/javase/7/docs/technotes/guides/language/underscores-literals.html, http://mlton.org/SuccessorML and http://docs.ruby-lang.org/en/2.0.0/syntax/literals_rdoc.html#label-Numbers

 Yes, I am doing this with my own parser right now. However since the whole point of splitting up this Parsec.Token module was to make it more generic, I thought I bring it up ;)

**Comment by mrkkrp** [comment]
No worries, thanks for the proposition!

**Comment by mrkkrp** [comment]
Feel free to open a PR implementing 1 if you want this feature, but I won't work on this myself (there are other more important things to work on in Megaparsec).

**Comment by mrkkrp** [comment]
@minad, Just re-reading this thread, I think my last comment was harsh (I wrote it in a hurry) — sorry for that. The point is not that your proposition is of no value to the project, but that at the time I was working on rather fundamental changes that required quite a bit of time and concentration and also fair amount of testing.

So everything in your hands, if you file a PR, I will be glad to consider it!

**Comment by minad** [comment]
> @minad [1], Just re-reading this thread, I think my last comment was
> harsh (I wrote it in a hurry) — sorry for that. The point is not
> that your proposition is of no value to the project, but that at the
> time I was working on rather fundamental changes that required quite a
> bit of time and concentration and also fair amount of testing.
> 
> So everything in your hands, if you file a PR, I will be glad to
> consider it!

Hi, it is fine :) I didn't expect you to implement it - just had the 
idea, so to keep it in mind. I will make a PR for that at some point.
