### ISSUE TITLE
How to use `space`

### ISSUE THREAD

**Issue by crockeea** [mrkkrp/megaparsec#103]
The docs for `space` repeatedly suggest `spaceChar` for the first argument. However, `spaceChar` has type `m Char`, but `space` expects an `m ()`. What is a simple option for the first arg to `space`?

**Comment by mrkkrp** [comment]
Try `void spaceChar`. Also see [this tutorial](https://mrkkrp.github.io/megaparsec/tutorials/parsing-simple-imperative-language.html).
