### ISSUE TITLE
Earlier versions of GHC this library compiles with?

### ISSUE THREAD

**Issue by AKST** [mrkkrp/megaparsec#107]
Hi, I'm doing some investigation into GHC compile time performance regression, and I noticed that on the GHC wiki a remark about there being a compile time slow down between `7.6` & `8.0`, so I was just wondering if you knew much about the portability of this library between and different GHC versions? Thanks.

**Comment by mrkkrp** [comment]
The library works and compiles fine with 7.6, .7.8, .7.10, and 8.0. If not, report it as a bug. Indeed, there is some sort of compile time regression, please see Travis CI builds:

https://travis-ci.org/mrkkrp/megaparsec

The last build shows ×8 regression in compilation time between GHC 7.6 and GHC 8.0. This is so bad that I had to use `travis_wait 40` to build it with newer GHCs.

One starting point for you is that `tests/Prim.hs` takes most part of the time, perhaps 90 % of compilation time. This is very suspicious, I don't know and (don't have much time to spend in investigations) what in that module causes such dramatic slowdown. If you find out something please let me know.

**Comment by AKST** [comment]
Wow that's shocking, I'll definitely try have a look into to that, maybe inspect core output see if it's blowing up or something.

**Comment by mrkkrp** [comment]
@AKST, Also take a look at [HLearn](https://github.com/mikeizbicki/HLearn) it seems to have severe problems with compilation time. It took almost *two hours* to compile it on my laptop, I thought it hanged.

**Comment by AKST** [comment]
Thanks for the head up, I'll add that to the list libraries I'll check out

**Comment by thomie** [comment]
> The last build shows ×8 regression in compilation time between GHC 7.6 and GHC 8.0.

Some progress on this in https://ghc.haskell.org/trac/ghc/ticket/12343 and https://github.com/thomie/megaslow.

**Comment by mrkkrp** [comment]
@thomie, Thanks, I really hope this issue with compilation time will be fixed, would be great.

**Comment by mrkkrp** [comment]
Closing this issue so it doesn't hang here and distract me. If you find something feel free to comment here anyway.
