### ISSUE TITLE
Please export manyAcc from Text.Megaparsec.Prim

### ISSUE THREAD

**Issue by ramon-garcia** [mrkkrp/megaparsec#108]
For compatibility with parsec, which exports manyAccum, please export manyAcc

I am porting the compiler of Microsoft bond, from parsec to megaparsec. And this is the final problem that I have

Best regards

**Comment by mrkkrp** [comment]
Parsec exports many things that should stay internal. `manyAcc` in one of them, IMO. `many` should usually do the trick. Please show me how Parsec's `manyAccum` is used in the code you're porting and then perphaps it will be clearer why you need it.

**Comment by ramon-garcia** [comment]
This is the referencing code

manySortedBy :: (a -> a -> Ordering) -> ParsecT s u m a -> ParsecT s u m [a]
manySortedBy = manyAccum . insertBy

It does look reasonable to be able to invoke a callback function when each element is inserted.

**Comment by mrkkrp** [comment]
I see. However, in your case

```haskell
manySortedBy :: (Alternative f, Ord a) => (a -> a -> Ordering) -> f a -> f [a]
manySortedBy f = fmap sortBy f . many
```

…should do the trick just as well. These functions are semantically equivalent. With `insertBy` you need to traverse every time to find a place to insert new element, while `sortBy` just sorts once. This solution may be even better unless I'm missing something.

**Comment by mrkkrp** [comment]
Have you resolved your problem using the proposed definition of `manySortedBy`?

**Comment by ramon-garcia** [comment]
Yes, of course.

Anyway, perhaps it makes sense to export a function that allows user defined accumulation, some function of the form c->a->c where c is the accumulated type and a is the element type.

I agree with you that using manyAccum in this case is silly, inserting each element in a sorted position takes O(N^2) time, where a reasonable sort takes O(N log N)
