### ISSUE TITLE
Support for nondecreasing indentation...

### ISSUE THREAD

**Issue by mgajda** [mrkkrp/megaparsec#110]
I have played with your indentation combinators, and it seems that they do not support two features of Haskell-like indentation:
1. Nondecreasing indentation
2. Having some items started in the same line, before the indented block starts.

**Comment by mrkkrp** [comment]
Can you explain what “nondecsreasing indentation” means? For 2, you can use any parser for “header” of indented block, thus achieving any sort of behaviour. Maybe I'm missing something, but it's not actually clear from your message what you're trying to do.

**Comment by mgajda** [comment]
Hi Mark,
I stated it incorrectly - sorry.

I have an indent block starting on the line that is not indented:
```
indent = case
  1 -> True
    2 -> False
```
I would like to allow the last line to be indented slightly more than the second.
Currently the `indentGuard` assumes that indentation is the same for the entire block.

**Comment by mrkkrp** [comment]
Well, Haskell does not allow this sort of indentation. The `indentBlock` and `lineFold` helpers work with more conventional indentation schemes, you will probably need to build your parser manually with `indentGuard`. You first get indentation of the second line and then use it with `indentGuard` to make sure the second line is more indented. Sorry, I don't have time to write the actual example, but that idea should work.

**Comment by mrkkrp** [comment]
Have you suceeded with this?

**Comment by mgajda** [comment]
I have started under impression that the interface would be somewhat more trivial to setup, and after the first stumbling block I decided to switch to `indentation-trifecta`.
Sorry.

**Comment by mrkkrp** [comment]
Megaparsec does not impose anything. Everything that is possible to do with monadic parser combinators is doable with it. The lexer module just contains some shortcuts that seem to make sense but nothing that you cannot build from scratch yourself. This does not mean however that they cover every possible use case. If you can come up with other useful helpers, you are welcome to add them.

No need to be sorry, if Trifecta works for you better, that's fine :-)
