### ISSUE TITLE
Labelling/annotating expected items

### ISSUE THREAD

**Issue by mikeplus64** [mrkkrp/megaparsec#111]
For a work project I'm working on it would be really nice to have a way to annotate specific expected items in ParseErrors. I'd like to be able to label expected items by the parser that they came from, e.g. "string", "number" etc.

At the moment errorCustom /kind of/ let's you achieve this, except when ParseErrors are combined you can't map specific ErrorItems to elements of errorCustom (i.e., autocompletions to labels).

**Comment by mrkkrp** [comment]
To be honest this looks like something not very common, so complexity that it would introduce probably is not worth it. Nevertheless, let it hang here so if more people request such a thing, we could add it. Thanks for opening the issue.

**Comment by mikeplus64** [comment]
I think a fairly low impact way to implement this would be adding a new constructor like:

LabelledTokens (NonEmpty Char) (NonEmpty t)

and a function that labels all "Tokens" ErrorItems, e.g. `labelTokens :: Text -> Parser a -> Parser a`. I'm not sure how this would look with the CPS stuff but I'm happy to give this a go.

**Comment by mikeplus64** [comment]
I think for any sort of language parser this is very useful as now you can see the category of the expected items produced e.g. "expression", "verb", "noun", "value", etc.. At the moment it's either one or the other, but both would be better IMO.

**Comment by mikeplus64** [comment]
I guess another way to implement it would be to tag errors with the `SourcePos` they come from.

**Comment by mikeplus64** [comment]
I'm still maintaining my own branch with this in it because it's very useful for me in production, but maybe a different design would be more palatable? I'm not sure how to implement this but:

If there was a function `mapParseError :: MonadParsec e t m => (ParseError t e -> ParseError t e) -> m a -> m a` that could be used here instead of changing anything. You'd just be able to take everything in `errorExpected` and dump it into the custom data field to achieve the same thing.

**Comment by mikeplus64** [comment]
like `withRecovery`, without the recovery ... :-)

**Comment by mrkkrp** [comment]
This probably may be added in some form in 5.2.0. For the upcoming 5.1.0 release I'm not adding new things right now.

**Comment by mrkkrp** [comment]
Actually I'm thinking of adding a combinator of the type `MonadParsec e t m => m a -> m (Either (ParseError t e) a)`. Equipped with this, you should be able to do what you need.

**Comment by mrkkrp** [comment]
If you are OK with such a function, tell me and I'll close this issue and open another open describing that function and schedule it for 5.2.0.

**Comment by mrkkrp** [comment]
I changed my mind, this looks like a simple yet useful thing to add in 5.1.0. Closing in favor of #145.
