### ISSUE TITLE
debug function

### ISSUE THREAD

**Issue by flip111** [mrkkrp/megaparsec#115]
for attoparsec i was using this debug function

```haskell
debug :: Parser a -> Parser a
debug p = do
  (consumed, a) <- match p
  remaining <- lookAhead takeText
  traceM ("consumed: " ++ show consumed)
  traceM ("remaining: " ++ show remaining)
  return a
```

I couldn't find an equivalent function for `match` and `takeText`. How can i debug a parser written with megaparsec?

**Comment by mrkkrp** [comment]
Thank you for opening the issue. Indeed such functions are missing, but we should add them. I'll get to it pretty soon I guess. Support for debugging will be added in version 5.1.0.

**Comment by flip111** [comment]
Is this moving to 5.2 now? This function would still be very valuable. Is there any other way to debug in the meantime?

**Comment by mrkkrp** [comment]
I just decided that there are other priorities for 5.1 right now (given my limited free time these days). I do think that function(s) for debugging are a useful addition, but I would like to think more about which exactly functions to add.

**Comment by mrkkrp** [comment]
The debug function is coming to Megaparsec in version 5.1.0. It will be in form of a primitive combinator to allow to see what's going on on lower level. This should be quite convenient.

**Comment by mrkkrp** [comment]
BTW, equivalent of `takeText` as called `getInput`.

**Comment by mrkkrp** [comment]
Now there is the `dbg` function that should be quite useful in debugging, [see here](https://github.com/mrkkrp/megaparsec/pull/144/files#diff-7762a64005e439e93f28d5c9a983baa9R1163).

**Comment by flip111** [comment]
When you have a parser of type `Parser Foo` where `Foo` has an instance of typeable. Is it possible to use `show $ typeOf foo` to make a string instead of manually providing a string for the first argument of dbg?

**Comment by mrkkrp** [comment]
What if you have two different parsers that parse the same type of data?

**Comment by flip111** [comment]
Then use the normal dbg function as it is now ...
