### ISSUE TITLE
Error recovery tutorial remarks

### ISSUE THREAD

**Issue by flip111** [mrkkrp/megaparsec#116]
Hello. I was following the tutorial for error recovery and have a few remarks and suggestions. I copied all the text into a file and try to run the example.

```
λ> parseTest expr "5 + foo"
Multiplication (Value 5.0) (Reference "foo")
```
This seems wrong, on my end it's `Sum`, not `Multiplication`

--

When adding the last part i get
```
Not in scope: type constructor or class ‘Dec’
```
Seems to be missing an import

--

```
import Data.Scientific (toRealFloat)
```
yields

```
Could not find module ‘Data.Scientific’
    It is a member of the hidden package ‘scientific-0.3.4.7@scien_3vmCXiZeJinKZBcLawS8i0’.
```
Should also be easy to fix, just would be nice to mention this step in the tutorial too. I'm using stack by the way.

**Comment by mrkkrp** [comment]
* This tutorial is for Megaparsec 5, which is present in nightly resolvers, but not in LTS yet (this is why `Dec` is not in scope, it's exported by `Text.Megaparsec` in version 5). Try `nightly-2016-06-20` or somethnig like that.

* About `scientific` — you need to add it to `package-depends` section in your Cabal file and the error will be gone.

* `Multiplication` vs `Sum` — good catch, I'll update that.

**Comment by mrkkrp** [comment]
Fixed: mrkkrp/megaparsec-site@6187585

**Comment by flip111** [comment]
Do you have any idea when megaparsec lands in LTS?

**Comment by neongreen** [comment]
@flip111 LTS 7.0 will be released in September. Stackage Nightly has already switched to GHC 8, so I don't expect another LTS 6.x release. September it is, then.
