### ISSUE TITLE
How to do custom error messages?

### ISSUE THREAD

**Issue by flip111** [mrkkrp/megaparsec#117]
Hi, i'm trying to get my parser to produce error messages such as the ones by, for example, clang. For that i need a line number and position in the line. I don't really have an idea where to start. I would like the parser to continue parsing after errors have been found. So i figure i could make a list and each time an error has been found push onto it a tuple with message + position. Then later retrieve the matching source code from the line number. Could someone provide a small example to get started on this scenario? I hope it's supported

```
int i = "hello";
        ^
Wrong data type on line 3 column 9
```

I imagine the underlying data could be something like this:

```
("Wrong data type", (9, 3))
```

**Comment by mrkkrp** [comment]
You seem to want displaying of line where error happened with carret `^` pointing exact position of error. This is not supported out-of-box, but you can add it yourself.

To add this feature you will need line and column position. You get them from error record like so (instruction for Megaparsec 5):

1. From `ParseError` you get stack of source positions `NonEmpty SourcePos` using the record selector `errorPos`.

2. From `NonEmpty SourcePos` you need to get its head, use `head` from `Data.List.NonEmpty` for that.

3. From `SourcePos` you can get source line via `sourceLine`, source column via `sourceColumn`, and `sourceName` will tell you file name.

Having this information, you should take original text you parsed and get the line of interest, then print it, print another line with `^` using column position and then you can just use `parseErrorPretty` to print the rest.

Hope it helps.

**Comment by mrkkrp** [comment]
BTW, there is [Trifecta](https://hackage.haskell.org/package/trifecta) parsing library that gives you clang-style error messages by default. It's not very well documented, but if you can figure out how to use it, maybe it could be a better fit for you.

**Comment by mrkkrp** [comment]
Let's actually keep this one as a feature request for error position indication similar to Clang's one.

**Comment by flip111** [comment]
Hi, this is my progress so far

```haskell
main :: IO ()
main =
  do let input = "x = |3 * (1 + y)\nq = 2 + @4"
     case parse (rawData <* eof) "blabla.txt" input of
       Right _ -> print "bar"
                  -- putStrLn $ show $ length $ errorPos pe
       Left pe -> mapM_ (\x -> putStrLn $ errorMessage input x) (errorPos pe) --putStrLn (errorMessage input err)
         where
           err = LNE.head (errorPos pe)

errorMessage :: String -> SourcePos -> String
errorMessage input err = unlines
  [ src ++ ":" ++ show line ++ ":" ++ show col ++ ": " ++ "error description here"
  , ilin
  , replicate eind ' ' ++ "^"
  ]
  where
    col  = fromIntegral $ unPos $ sourceColumn $ err
    eind = col - 1
    line = fromIntegral $ unPos $ sourceLine $ err
    src  = sourceName err
    ilin = (lines input) !! (line - 1)
```
output
```
blabla.txt:2:9: error description here
q = 2 + @4
        ^
```
expected output
```
blabla.txt:1:5: error description here
x = |3 * (1 + y)
    ^
blabla.txt:2:9: error description here
q = 2 + @4
        ^
```
Some question about this
1. There are two errors in the input, mapM_ only gets 1 error, why is this?
2. Instead of "error description here" i would like to let the error description originate from the rules. For example at rule `number` my error description could be `"@4 is not a valid number"`. How can i "send" custom error messages from rules to valie `pe` (error information record)?
3. is it really needed to supply a source file? Perhaps there are other origins than a file.

I haven't tried `parseErrorPretty` yet .. but i think i want to customize all error messages myself anyway.

**Comment by mrkkrp** [comment]
1. You don't show your `rawData`, so I can't tell you when the second error is reported but not first. Please take time to [read documentation](https://hackage.haskell.org/package/megaparsec-5.0.1/docs/Text-Megaparsec-Error.html#t:ParseError), and you will find that `errorPos` is not collection of positions for *several* errors, but stack of positions, that's used when you work with `include` files or similar. In your case it sure will contain single element.

2. For this you need to replace [`Dec`](https://hackage.haskell.org/package/megaparsec-5.0.1/docs/Text-Megaparsec-Error.html#t:Dec) with your own type. The type will have constructors corresponding to all your “special” cases. Then you use [`failure`](https://hackage.haskell.org/package/megaparsec-5.0.1/docs/Text-Megaparsec.html#v:failure) to report them.

3. You can always supply `""` and it won't be shown in error messages at all (the only need for the name is to show it in error messages, the parser itself doesn't care where you get your input from).

You can take a look at `parseErrorPretty` for inspiration anyway.

**Comment by flip111** [comment]
This blog post looks nice https://mrkkrp.github.io/megaparsec/tutorials/custom-error-messages.html

Maybe it would be a good idea to add a paragraph to the post to see it in action? Some examples of wrong input and different error messages which are appearing.

I guess that `<?>` sets the name of the item.

**Comment by mrkkrp** [comment]
@flip111, Thanks for the feedback, I think I'll add the examples indeed.

**Comment by mrkkrp** [comment]
@flip111, I included some examples of how that parser behaves at the end of the tutorial. You can read about `(<?>)` combinatior [here](https://hackage.haskell.org/package/megaparsec-5.0.1/docs/Text-Megaparsec.html#v:label).

**Comment by mrkkrp** [comment]
I think we can close this for now. I believe it should be implemented as a separate package which could depend on a library that can do colorful tricks in terminals and stuff like that. I think it's out of scope for Megaparsec itself right now, and the original problem seems to be resolved by now (?).

**Comment by flip111** [comment]
Yes it looks very good !
