### ISSUE TITLE
Error recovery: search in sub-rules

### ISSUE THREAD

**Issue by flip111** [mrkkrp/megaparsec#118]
I've read the tutorial on error recovery. From what i understand you can forward the pointer to, for example, the next line and then continue parsing. Then currect rule will fail and it will fall back to the previous rule(s). Below is a simple grammar with image.

```
A = (B | F)+
B = C | E
C = D
```
![example](https://cloud.githubusercontent.com/assets/2244480/16409833/236065ec-3d28-11e6-8673-993d77eb85df.png)

For input string `ABCE` it could parse `ABC` first then fail in parsing `D` then fallback to the previous rule `C` which fails too, then `B` which can succeed on choosing `E`. Or in case of input string `ABCF` `B` would fail as well and it would go back to `A` and succeed there on choosing `F`.

Would it be possible to into sub-rules as well? For example input string `ABDF`, `AB` would match then `D` would fail, but now i'd like the parser to go inspect subrules and find that there is a rule that can match the `D`. With this information it would be possible to provide error messages like

```
ABDF
  ^
Found `D` after `AD`, did you forget to add `C`?
```

Another example using SQL:

```
SELECT FROM table
       ^
Expected a column list here, but found FROM
```

I know that for example the last error message you can just hardcode it, but with complicated grammars searching down subnodes it would be possible that there are multiple candidates so you would get a list of suggestions.

Another benefit of this that you have to do less "guessing" on where to put the pointer. The error recovery tutorial suggest to put the pointer on the next line. But with with searching subrules you could just forward the pointer conditionally on wether subrules where found or not. Example `ABZDF`, encountered an error on `Z`, start searching subrules failed, forward pointer to `D` and succeed searching subrules as described above.

**Comment by mrkkrp** [comment]
Your post does not make much sense to me. There is no fallbacks, all you can do is to skip some part of input stream, that's all. If you know how to do what you are describing without breaking backwards-compatibility and performance, open a PR. The idea expressed in code may be more understandable to me.

**Comment by flip111** [comment]
Hi @mrkkrp thanks for your reply. I don't know how to do in haskell what i want to do. I'm still a beginner and i can do a code example but only in imperative code. Below are two parsers in php, the second one has the suggested feature. The main idea here is not to touch the input stream cursor, but to select a different rule to match the current token on. It's still my assumption that the current way of doing error recovery in megaparsec is by going back to parent rule(s). This is shown in the first code snippet.

```php
<?php
// A = B | F
// B = C | E
// C = D

// [ parsing function, next rule ]
// next rule === null --> terminal
// next rule !== null --> non-terminal
$rules = [
  'root' => [
    [function($char) { return $char === 'A'; }, 'A']
  ],
	'A' => [
    [function($char) { return $char === 'B'; }, 'B'],
    [function($char) { return $char === 'F'; }, null],
	],
  'B' => [
    [function($char) { return $char === 'C'; }, 'C'],
    [function($char) { return $char === 'E'; }, null],
  ],
  'C' => [
    [function($char) { return $char === 'D'; }, null]
  ]
];

$input = 'ABCE'; // input to parse
$rule_stack[] = 'root'; // push something on stack to have a start point
$matched = ''; // append to this empty string all the things that were matched

for ($i = 0; $i < strlen($input); $i++) {
  $token = $input[$i]; // read token (char) from "stream" (string)
  $found_match = false; // simple boolean to keep track if something was matched (needed for error handling later)
  $current_rule = end($rule_stack); // last rule on stack

  foreach ($rules[$current_rule] as $rule) {
    if ($rule[0]($token)) { // index 0 was the matching function, lets call it with argument the input token
      $matched .= $token; // append to matched string
      $rule_stack[] = $rule[1]; // push the next rule to search on the stack, this will be something like ['root', 'A', ..]
      $found_match = true; // bookkeeping
      break;
    }
  }

  if ($found_match === false) {
    printf("Parse error at %s\n", $token);

    // now we can do some error recovery here

    // leave the position the same
    $i--; // to cancel out $i++ after loop

    // go back to one rule higher, try matching there
    array_pop($rule_stack); // remove last element from stack

    // don't break because we don't want to end parsing, try to continue instead
    //break;
  }
}

printf("Matched: %s", $matched);
/* Output:
Parse error at E
Matched: ABCE
*/
```

```php
<?php
$rules = [
  'root' => [
    [function($char) { return $char === 'A'; }, 'A']
  ],
  'A' => [
    [function($char) { return $char === 'B'; }, 'B'],
    [function($char) { return $char === 'F'; }, null],
  ],
  'B' => [
    [function($char) { return $char === 'C'; }, 'C'],
    [function($char) { return $char === 'E'; }, null],
  ],
  'C' => [
    [function($char) { return $char === 'D'; }, null]
  ]
];

$input = 'ABDF'; // input to parse
$rule_stack[] = 'root'; // push something on stack to have a start point
$matched = ''; // append to this empty string all the things that were matched

for ($i = 0; $i < strlen($input); $i++) {
  $token = $input[$i]; // read token (char) from "stream" (string)
  $found_match = false; // simple boolean to keep track if something was matched (needed for error handling later)
  $current_rule = end($rule_stack); // last rule on stack

  foreach ($rules[$current_rule] as $rule) {
    if ($rule[0]($token)) { // index 0 was the matching function, lets call it with argument the input token
      $matched .= $token; // append to matched string
      $rule_stack[] = $rule[1]; // push the next rule to search on the stack, this will be something like ['root', 'A', ..]
      $found_match = true; // bookkeeping
      break;
    }
  }

  if ($found_match === false) {
    printf("Parse error at %s\n", $token);

    // now we can do some error recovery here

    // leave the position the same
    $i--; // to cancel out $i++ after loop

    $found_match2 = false;
    // $rule_stack is here   ['root', 'A', 'B']
    // but rule 'B' does not have a parsing function that can match 'D'
    // start searching the sub-rules instead, this will effectively be a parser in a parser
    foreach ($rules[$current_rule] as $rule) { // we are in 'B' here
      if ($rule[1] !== null) { // there are sub-rules here (non-terminals)
        // now start the search in subrules (this is the parser in parser idea here ..
        // notice it looks very similar to code before)
        foreach ($rules[$rule[1]] as $rule2) {
          if ($rule2[0]($token)) {
            $matched .= $token;
            //$rule_stack[] = $rule2[1]; // don't polute the main stack here, for this trvial example we don't need a stack for the sub-rule parser
            $found_match2 = true;
            break;
          }
        }
      }
    }

    // it was possible to finish rule 'B' here by continuing in subrule 'C'
    if ($found_match2) {
      // therefor it's valid to pop the non-valid 'B' off the stack
      // and continue normally
      array_pop($rule_stack);
      $i++; // advance the cursor because the token was parsed succesfully in the error-recovery block
    }

    // don't break because we don't want to end parsing, try to continue instead
    //break;
  }
}

printf("Matched: %s", $matched);
/* Output:
Parse error at D
Matched: ABDF
*/
```

**Comment by mrkkrp** [comment]
You don't need error recovery, you need branching. See `(<|>)`, `choice`, `try` and other primitives. The “error recovery” term is used for something a bit different in Megaparsec.

See docs here:

https://hackage.haskell.org/package/megaparsec-5.0.0/docs/Text-Megaparsec.html

Also try this tutorial:

https://mrkkrp.github.io/megaparsec/tutorials/parsing-simple-imperative-language.html

**Comment by flip111** [comment]
Can you motivate why you think error recovery is not applicable here? Maybe my BNF is not really in the most understandable notation, i will make the terminals explicit (with quotes)

```
A = "A" | "A" B | "A" "F"
B = "B" | "B" C | "B" "E"
C = "C" | "C" D
D = "D"
```

Both `ABCE` and `ABDF` are not able to match here. `ABCE` will go like this:

* Match `"A" B` in rule A
* Match `"B" C` in rule B
* Match `"C" ` in rule C (the other choice can not match)
* Unable to match E because rules have been exhausted here (no implicit backtracking)

`ABDF` will go like this:

* Match `"A" B` in rule A
* Match `"B"` in rule B (the other two choices can not match)
* Unable to match DF because rules have been exhausted here (no implicit backtracking)

By the way, i know i should use `<|>` for choices (branching).

**Comment by mrkkrp** [comment]
Yes, this makes sense, but Megaparsec's error recovery has nothing to do with this.

**Comment by flip111** [comment]
I mean i think you can express these rules in megaparsec, then how would megaparsec recover from this? I was here under the assumption that the current rule will fail and then fall back to the previous (parent) rule, can you confirm this?

**Comment by mrkkrp** [comment]
You can achieve this with `try` applied to parent rule, then when its sub-rule fails, the parent rule fails as well but because of `try` it does not consume input, backtrakcs, and new `(<|>)` can go to the next one. This is branching. This is how idiomatic parsers in Attoparsec/Parsec/Megaparsec are built. You normally don't need any error recovery to write parsers this way.

Now, the error recovery is a unique feature of Megaparsec, it allows you to recover when everything else failed and you would otherwise just finish with error message. It just gives you a way to skip bad part of input and continue parsing after it.

**Comment by mrkkrp** [comment]
Is it clearer for you now how to achieve what you want?

**Comment by flip111** [comment]
With "backtracking" i meant going back to previous rules. Like you describe i can do this with `try`. But this only works if the parent can handle the token with a different branch. I'm really talking about the error recovery feature.

In [the tutorial](https://mrkkrp.github.io/megaparsec/tutorials/fun-with-the-recovery-feature.html) `equation` is the parent rule, it can try to recover from unparsable tokens (can not be match by sub-rules `expr`, `term`, ...etc). What would happen if you try to parse `y = + 2 * 3`? I think it would fail because there is something missing on the left side of the `+`. That means that `+` is a wrong token in this context (and has no meaning). But if you could search in subrules of `expr` you can detect that the user probably meant to write `# + 2 * 3`, where # is an arbitrary number. You could then give an explicit error message based on this information `"did you forget to put a number on the left side of + ?"`

I'm sorry that i'm unable to explain myself in a more concise way.

**Comment by mrkkrp** [comment]
Now finally I get what you want to achieve. No, this is currently not possible. The parser works by going forward, it does not go back. So error message will be probably like this: unexpected '+', expecting term. Or something.

**Comment by flip111** [comment]
I'm not sure with what you mean the parser does not go back? I propose to attempt to make it go forward with a search in possible sub-rules. You can have two benefits from this:

1. create error messages based on sub-rules. Example for `y = # + 2 * 3` maybe there are more possible things that can go in place of #. You can have a sub-rule that allows a digit in this place `y = 1 + 2 * 3`. But there could be another sub-rule that takes a letter (another variable in the equation) `y = z + 2 * 3`. I repeat the SQL example from before too: `SELECT FROM tbl` is missing a column list, so `FROM` is the unexpected token ... but a sub-rule of the SELECT-clause can partially match if it would have a column list.

2. making smarter error recovery. In the example of `y = # + 2 * 3` you don't have to go to the end of the line. But you can choose the parse the last part of the equation and reduce it to this `y = # + 6`.

I mean this information is available in the code .. it's just a matter of doing a search. The result of the search will be a list with partially matching sub-rules and an indication of how much they match. From there you can pick the top 3 or something and present it to the user.

Anyway ... i think it would be an awesome feature. I'm just unable to code it at this point ... will take some months at least until i learned enough. @mrkkrp are you interested in this feature? Maybe at some point it can be merged in the codebase with a PR??

**Comment by mrkkrp** [comment]
I propose you study the existing code base and then you are wolcome to propose specific changes.

**Comment by flip111** [comment]
Ok thank you for the discussion :)
