### ISSUE TITLE
instance Stream [L a]

### ISSUE THREAD

**Issue by mitchellwrosen** [mrkkrp/megaparsec#120]
It would be nice to have this instance:

``` haskell
instance Stream [L a] where
  type Token [L a] = L a

  uncons [] = Nothing
  uncons (t:ts) = Just (t,ts)

  updatePos _ _ p (L NoLoc _) = (p, p)
  updatePos _ _ (L (Loc p1 p2) _) = (p2sp p1, p2sp p2)
   where
    p2sp :: Pos -> SourcePos
    p2sp (Pos x y z _) = SourcePos x y z
```

where `L` is from [srcloc](https://hackage.haskell.org/package/srcloc). This would provide better integration with the [lexer-applicative](https://hackage.haskell.org/package/lexer-applicative) library, which lexes into `L`-tagged tokens.

Is it worth it to add a `srcloc` dependency for this?

**Comment by mrkkrp** [comment]
I'm not sure. I personally don't need this, but maybe someone else does.

**Comment by mrkkrp** [comment]
Closing for now.
