### ISSUE TITLE
Incorrect "combinator 'many' is applied to a parser that accepts an empty string"

### ISSUE THREAD

**Issue by devonhollowood** [mrkkrp/megaparsec#122]
I ran into a case where I get the error message `combinator 'many' is applied to a parser that accepts an empty string` on a combinator that does not accept an empty string. The exact conditions that trigger it seem a little complicated, but here's a minimal-ish reproduction:

```haskell
import Text.Megaparsec
import Text.Megaparsec.Lexer (integer)
import Text.Megaparsec.String

badParser :: Parser (String, String, String)
badParser = do
    begin <- lookAhead (string "hi" <|> string "highlander")
    let header = string begin <* char ' '
    (,,)
        <$> option "hello" (try $ header *>
            (string "hello" <|> string "goodbye") <* eol)
        <*> option "up" (try $ header *>
            (string "up" <|> string "down") <* eol)
        <*> option "dog" (try $ header *>
            (string "cat" <|> string "dog") <* eol)
```

```haskell
ghci> parse (many badParser) "" "highlander hello\nhighlander up\nhighlander dog\n"
*** Exception: Text.Megaparsec.Prim.many: combinator 'many' is applied to a parser that accepts an empty string.
CallStack (from HasCallStack):
  error, called at ./Text/Megaparsec/Prim.hs:368:11 in megaparsec-5.0.0-LNVOzsebc7p2uljSOAtTZs:Text.Megaparsec.Prim
ghci> parse badParser "" "highlander hello\nhighlander up\nhighlander dog\n"
Right ("hello","up","dog")
ghci> parse badParser "" ""
Left (ParseError {errorPos = SourcePos {sourceName = "", sourceLine = Pos 1, sourceColumn = Pos 1} :| [], errorUnexpected = fromList [EndOfInput], errorExpected = fromList [Tokens ('h' :| "i"),Tokens ('h' :| "ighlander")], errorCustom = fromList []})
```
So even though the last example here shows that `badParser` does not accept an empty string, I still get an error when running `many badParser`.

The problem seems to come from using the `option`-like parsers in conjunction with the fact that "hi" is a prefix of "highlander" (I say "`option`-like parsers" because I initially ran into this problem using `<$?>` in `Text.Megaparsec.Prim`). Removing the `option` gets rid of the unexpected `many` error.

```haskell
noOption :: Parser (String, String, String)
noOption = do
    begin <- lookAhead (string "hi" <|> string "highlander")
    let header = string begin <* char ' '
    (,,)
        <$> try (header *>
            (string "hello" <|> string "goodbye") <* eol)
        <*> try (header *>
            (string "up" <|> string "down") <* eol)
        <*> try (header *>
            (string "cat" <|> string "dog") <* eol)
```

```haskell
ghci> parse (many noOption) "" "highlander hello\nhighlander up\nhighlander dog\n"
Right []
ghci> parse noOption "" "highlander hello\nhighlander up\nhighlander dog\n"
Left (ParseError {errorPos = SourcePos {sourceName = "", sourceLine = Pos 1, sourceColumn = Pos 3} :| [], errorUnexpected = fromList [Tokens ('g' :| "")], errorExpected = fromList [Tokens (' ' :| "")], errorCustom = fromList []})
```
(It's interesting to note that that `parse noOption "" "highlander hello\nhighlander up\nhighlander dog\n"` gives a failure while `parse badParser "" "highlander hello\nhighlander up\nhighlander dog\n"` gives a success, but ~~I'd need to think about that a little more to decide whether or not that is a bug in its own right.~~ edit: I thought about this part a little more and it makes perfect sense. Nevermind.)

Reordering the conditions also fixes it:
```haskell
reordered :: Parser (String, String, String)
reordered = do
    begin <- lookAhead (string "highlander" <|> string "hi")
    let header = string begin <* char ' '
    (,,)
        <$> option "hello" (try $ header *>
            (string "hello" <|> string "goodbye") <* eol)
        <*> option "up" (try $ header *>
            (string "up" <|> string "down") <* eol)
        <*> option "dog" (try $ header *>
            (string "cat" <|> string "dog") <* eol)
```

```haskell
ghci> parse (many reordered) "" "highlander hello\nhighlander up\nhighlander dog\n"
Right [("hello","up","dog")]
ghci> parse reordered "" "highlander hello\nhighlander up\nhighlander dog\n"
Right ("hello","up","dog")
```

I tested using both Megaparsec 4.4.0 and Megaparsec 5.0.0, and the problem exists in both.

Also, do you do any mentoring for contributors? I have some free time this weekend, and if you can tell me where to start looking for the bug I'd be happy to try to fix it.

**Comment by devonhollowood** [comment]
Okay, I thought about this some more, and there's an even simpler case which I think illustrates what's going on:

```haskell
simple :: Parser String
simple = lookAhead $ string "hello"
```

```haskell
ghci> parse simple "" "hello"
Right "hello"
ghci> parse (many simple) "" "hello"
*** Exception: Text.Megaparsec.Prim.many: combinator 'many' is applied to a parser that accepts an empty string.
CallStack (from HasCallStack):
  error, called at ./Text/Megaparsec/Prim.hs:368:11 in megaparsec-5.0.0-LNVOzsebc7p2uljSOAtTZs:Text.Megaparsec.Prim
ghci> parse simple "" ""
Left (ParseError {errorPos = SourcePos {sourceName = "", sourceLine = Pos 1, sourceColumn = Pos 1} :| [], errorUnexpected = fromList [EndOfInput], errorExpected = fromList [Tokens ('h' :| "ello")], errorCustom = fromList []})
```

The issue is in the weird interaction between `lookAhead` and `many`: `lookAhead` does not accept an empty string, but it also does not actually consume any input. In the original case, when all of the `option`s are not present, the parser reduces to a simple `lookAhead` with nothing following it. I suppose it doesn't really make sense to apply `many` to a parse which consumes no input, so maybe the simplest solution is to just change the error message on `many` to state `combinator 'many' is applied to a parser that may consume no input` or something like that.

**Comment by flip111** [comment]
I suspect that this also gets triggered when you chain 2 or more `many`'s. Because the inner `many` may consume no input so the outer `many` runs into a problem. I have yet to confirm this though ...

**Comment by flip111** [comment]
Ok i confirmed that this is indeed the case. So i would like to warn everyone when you have rules likes this in your grammar

```
a ::= b*
b ::= c*
```
where `*` means zero-or-more (like in regular expressions).

that this is going to trigger this exception.

I think there is a problem with this check because "many times consume no input" should resolve to "0 times". So in the case of above grammar when there are zero `c`'s there should also be zero `b`'s. So when implemented with lists both `c` and `b` should be an empty list.
