### ISSUE TITLE
Why is there no runParser for instances of MonadParsec?

### ISSUE THREAD

**Issue by siddharthist** [mrkkrp/megaparsec#125]
Forgive me if this is a stupid question, I'm new to monad transformers. Looking at the documentation, I see `runParser`, `runParser'`, `runParserT`, and `runParserT'`, all of which operate on various instances of `ParsecT`.

What if I have a monad stack that's an instance of `MonadParsec` that I want to run, and `ParsecT` isn't the outermost monad?

**Comment by mrkkrp** [comment]
You run your outermost monad with a function like `runReader` or `runState`, and again if necessary till you get to `ParsecT` and then you run it with one of the available functions.

**Comment by siddharthist** [comment]
@mrkkrp That makes sense to me. Is there any reason that those functions couldn't be generalized, though? Do they use some feature of `ParsecT` that isn't part of the `MonadParsec` class?

Also: thanks for the awesome library and quick response! :+1:

**Comment by mrkkrp** [comment]
It's not normally done (and essentially useless, not to mention harder-to-understand error messages), but if we wanted to do it, it's possible to do something like that. You introduce `runParserT` to `MonadParsec` using current implementation for `ParsecT`. Then when you make `StateT`, `ReaderT` — all the standard monad transformers instances of `MonadParsec` you first run their “running” function, then `runParserT` on the result (inner monad). This scheme will allow you to run `runParserT` once and get to its inner monad (you can't go further, though).

**Comment by siddharthist** [comment]
@mrkkrp Thanks for taking the time to explain it!
