### ISSUE TITLE
Performance pitfall(s)?

### ISSUE THREAD

**Issue by FPtje** [mrkkrp/megaparsec#126]
Yesterday and today I worked on migrating my GLua linter from parsec to megaparsec-5.0.0. Sadly, performance of the linter has drastically decreased since.

With parsec, linting [this project](https://github.com/FPtje/DarkRP) takes between 7 to 8 seconds. With megaparsec it takes around 30 seconds. Memory usage is also through the roof, with the linter taking 29MB with parsec and ~ 400MB with megaparsec.

Now I'm probably falling for some kind of performance pitfall, doing something that causes the thing to blow up. I have a hunch on what I'm doing wrong (later in the issue), but it would be nice to get some confirmation. I also think that my issue can be documented as a performance pitfall. Other people could perhaps benefit from my mistake being in some kind of list holding bad practices.

My project has its lexer, parser and "bad sequence finder" moved to megaparsec:
[Parsec Lexer](https://github.com/FPtje/GLuaFixer/blob/master/src/GLua/PSLexer.hs) versus [Megaparsec lexer](https://github.com/FPtje/GLuaFixer/blob/megaparsec/src/GLua/PSLexer.hs)
[Parsec parser](https://github.com/FPtje/GLuaFixer/blob/master/src/GLua/PSParser.hs) versus [Megaparsec parser](https://github.com/FPtje/GLuaFixer/blob/megaparsec/src/GLua/PSParser.hs)
[Parsec BadSequenceFinder](https://github.com/FPtje/GLuaFixer/blob/master/src/GLuaFixer/BadSequenceFinder.hs) versus [Megaparsec BadSequenceFinder](https://github.com/FPtje/GLuaFixer/blob/megaparsec/src/GLuaFixer/BadSequenceFinder.hs)

The profiler shows the following:
```
COST CENTRE              MODULE                       %time %alloc

pMSatisfy                GLua.PSParser                 61.0   58.1
<?>                      Text.Megaparsec.Prim           5.2    7.3
makeExprParser           Text.Megaparsec.Expr           4.0   10.1
updatePos                GLua.PSParser                  3.3    0.0
compare                  GLua.AG.Token                  2.8    0.0
pMTok                    GLua.PSParser                  1.4    0.0
searchSettings           GLuaFixer.Util                 1.4    0.5
==                       GLua.AG.Token                  1.2    0.0
parseNumber.pHexadecimal GLua.PSLexer                   1.1    3.6
ident                    GLuaFixer.BadSequenceFinder    1.0    0.0
parseToken               GLua.PSLexer                   1.0    1.5
lcp2sp                   GLua.PSParser                  0.6    3.5
```

Clearly, the [`pMSatisfy`](https://github.com/FPtje/GLuaFixer/blob/megaparsec/src/GLua/PSParser.hs#L54) primitive is the bottleneck in both CPU time and memory allocation. 

The kicker, however, is that when I disable the BadSequenceFinder, the megaparsec version suddenly becomes faster than the parsec version, with parsec taking 6 seconds and megaparsec 5.

Now the [BadSequenceFinder](https://github.com/FPtje/GLuaFixer/blob/megaparsec/src/GLuaFixer/BadSequenceFinder.hs#L286) is slow (it tries to parse bad sequences, parses one token and then tries again until the end). It does this because it looks for bad patterns in the code (calls to deprecated functions, bad whitespace placement, that kind of stuff) but it seems that doing this is much more expensive in megaparsec than it is in parsec. 

The changes in BadSequenceFinder are minimal, the only thing I've done in the migration process is renaming the imports and recreating this function, which megaparsec lacks:

```haskell
parserZero :: AParser a
parserZero = failure Set.empty Set.empty Set.empty
```

----

In the end this is pretty much the same parser, but it blows up with megaparsec while it doesn't with parsec. Whatever is going wrong here is probably worth documenting.

**Comment by mrkkrp** [comment]
Thanks, this is interesting. I'll take a closer look when I have time and get back to you.

**Comment by FPtje** [comment]
Here's a minimal reproducible case where a huge performance difference can be seen between Parsec and Megaparsec:

```haskell
module Main where

-- Rename imports to Megaparsec for Megaparsec example
import Text.Parsec
import Text.Parsec.String

asciiString :: [Char]
asciiString = " !\"#$%&\'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~"

longString :: String
longString = asciiString ++ asciiString

someChar :: Parser Char
someChar =
  oneOf asciiString


input :: String
input = concat [[x, y, z] | x <- longString, y <- longString, z <- longString]

abc :: Parser String
abc = try $ string "abc"

searchParser :: Parser [String]
searchParser =
  (:) <$> abc <*> searchParser <|>
  anyChar *> searchParser <|>
  return []

main :: IO ()
main =
  do
    putStrLn "length of input string: "
    print $ length input
    let result = parse searchParser "parsecTest" input

    putStrLn ""
    putStrLn "Result:"
    print result

```

Place in a file called `Main.hs`, compile with `ghc Main.hs` and run the `Main` executable.

Note: This example took over 10GB of RAM on my PC. Set `longString` to just `asciiString` for it to take less ridiculous amounts of RAM.

The parsec version of this example takes between 15 and 16 seconds on my laptop to finish. The megaparsec version takes around a minute.

With `longString = asciiString` the example is considerably smaller. There it takes the parsec around 2.0 seconds and Megaparsec 5.4 seconds.

**Comment by mrkkrp** [comment]
`parserZero` is called `mzero` it's part of `MonadPlus` instance, as it should be. Equivalent in `Alternative` is `empty`. Exporting `parserZero` in Parsec is redundant and I think it's even wrong, since you should be using `MonadPlus` and `Alternative` methods instead.

**Comment by mrkkrp** [comment]
OK, I'm going to focus on the minimal reproducing case you posted. On my machine I can see 2× difference in time of execution between Parsec (6.617 sec) and Megaparsec (12.422).

Unfortunately, the `(<|>)` operation is indeed more expensive in Megaparsec at the moment. It may be actually faster than in Parsec if you don't build long chains of alternatives, but in the case you show, it's quite bad.

The reason for this is that Megaparsec has more machinery and features than Parsec and for all this stuff to work we need to do more in `(<|>)` and most importantly to have improved error messages we should keep some sort of info from failed parsers on the left side when thy do not consume input, this turns to be quite a problem in your case.

I'll see what I can do to improve the situation. I'm going make this issue my priority for the next Megaparsec release.

**Comment by mrkkrp** [comment]
Re: about memory consumption in your example. The consumption is so high because your parser backtracks a lot, almost every its attempt requires backtracking. Memory consumption with Parsec is just as bad, BTW.

**Comment by mrkkrp** [comment]
OK, looked into the code once again and I could not find how to improve the situation. Backtracking is expensive in libraries of this sort and your example does *a lot* of backtracking. This is normal usage of Megaparsec.

----

Here is a way to re-write that example so it works faster and consumes less memory.

```haskell
module Main (main) where

import Data.Maybe (catMaybes)
import Text.Megaparsec
import Text.Megaparsec.String

asciiString :: String
asciiString = " !\"#$%&\'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~"

longString :: String
longString = asciiString ++ asciiString

input :: String
input = concat [[x, y, z] | x <- longString, y <- longString, z <- longString]

abc :: Parser (Maybe String)
abc =
  let f ch g = do
        x <- anyChar
        if x == ch
          then g
          else skipTillNext
  in f 'a' $ f 'b' $ f 'c' $ return (Just "abc")

skipTillNext :: Parser (Maybe String)
skipTillNext = Nothing <$ many (satisfy (/= 'a'))

searchParser :: Parser [String]
searchParser = catMaybes <$> (skipTillNext *> many abc)

main :: IO ()
main =
  do
    putStrLn "length of input string: "
    print $ length input
    let result = parse searchParser "parsecTest" input

    putStrLn ""
    putStrLn "Result:"
    print result
```

This consumes less space and finishes in 1.248 sec. I hope this will give you an idea how to fix your real code as well.
