### ISSUE TITLE
Error messages by 'string' parser suck

### ISSUE THREAD

**Issue by mrkkrp** [mrkkrp/megaparsec#13]
Here is an example:

```
λ> parseTest (string "re" <* eof) "ri"
parse error at line 1, column 1:
unexpected "i"
expecting "re"
```

This reports first mismatching character, but specified position is at the beginning of the whole string. Also, since it's logical that we should tell the user whole expected word, we should also tell him/her whole mismatching part, so:

```
λ> parseTest (string "re" <* eof) "ri"
parse error at line 1, column 1:
unexpected "ri"
expecting "re"
λ> parseTest (string "foo" <* eof) "bar"
parse error at line 1, column 1:
unexpected 'b'
expecting "foo"
```

↑ this is how proper error message should look, imho. Let's see if this can be fixed.

**Comment by mrkkrp** [comment]
OK, almost done… One more case to consider:

```
λ> parseTest (string "foo" <* eof) "fo"
parse error at line 1, column 1:
unexpected end of input
expecting "foo"
```

While it's technically correct, we could say:

```
λ> parseTest (string "foo" <* eof) "fo"
parse error at line 1, column 1:
unexpected "fo"
expecting "foo"
```

— much better.

**Comment by neongreen** [comment]
How do you deal with very long strings? for instance, what would `string
"re"` produce when applied to "random string which happens to start with
'r' and keeps going and going and going"?

**Comment by mrkkrp** [comment]
@neongreen, I only track first mismatch, than I return `unexpected <string before mismatch including first mismatched character> expecting <given parameter>`. This this rather about rewriting of more general `tokens` parser, than about `string` parser itself.

**Comment by mrkkrp** [comment]
@neongreen, here is my tests for `string` parser:

```haskell
prop_string :: String -> String -> Property
prop_string a' s' = checkParser (string a') (w a' 0 s') s'
    where w [] _ []    = Right a'
          w [] i (s:_) = posErr i s' [uneCh s, exStr ""]
          w _  0 []    = posErr 0 s' [suneStr "", exStr a']
          w _  i []    = posErr 0 s' [suneStr (take i s'), exStr a']
          w (a:as) i (s:ss)
            | a == s    = w as i' ss
            | otherwise = posErr 0 s' [suneStr (take i' s'), exStr a']
              where i'  = succ i
```

I will push my work after a while anyway, but since you're interested in various corner cases, it maybe of interest for you.

**Comment by neongreen** [comment]
> string before mismatch including first mismatched character

Oh, this kinda hasn't occurred to me, but I understand now. Nevermind!
