### ISSUE TITLE
Operator Parser with identical prefix

### ISSUE THREAD

**Issue by alexkazik** [mrkkrp/megaparsec#130]
I have two operators & and && and the second one never gets parsed since the first is picked and then there is an unexpected & rights afterwards.
It does work if I swap the precedence but that is the wrong one.
Any ideas?

Short example, tried with megaparsec-5.0.1 and ghc-8.0.1:

    module Main where

    import           Control.Monad         (void)
    import           Text.Megaparsec
    import           Text.Megaparsec.Expr
    import qualified Text.Megaparsec.Lexer as L
    import           Text.Megaparsec.String

    data Expr = Name String
              | Operator String Expr Expr
                deriving (Show)

    sc :: Parser ()
    sc = (hidden . skipMany $ void $ oneOf " \t") <?> "space char"

    symbol :: String -> Parser String
    symbol = L.symbol sc

    expr :: Parser Expr
    expr = makeExprParser term operators

    term :: Parser Expr
    term = Name <$> some alphaNumChar <* sc

    operators :: [[Operator Parser Expr]]
    operators =
      [ [ InfixL (Operator <$> symbol "+") ]
      , [ InfixL (Operator <$> symbol "&") ]
      , [ InfixL (Operator <$> symbol "&&") ]
      ]

    main = do
      print $ runParser (sc *> expr <* eof) "inline" "a + c & b"
      print $ runParser (sc *> expr <* eof) "inline" "a + c && b"

**Comment by user471** [comment]
https://github.com/mrkkrp/megaparsec/issues/129

You can use 
```
opChar :: Parser Char
opChar = oneOf "!#$%&*+./<=>?@\\^|-~"

operator name =
    lexeme $ try $
    do{ string name
      ; notFollowedBy opChar <?> ("end of " ++ show name)
      }
```
instead of `symbol`
```
[ [ InfixL (Operator <$> operator "+") ]
```

**Comment by mrkkrp** [comment]
Maybe indeed, I'll add it today, thanks for suggesting that.

**Comment by mrkkrp** [comment]
BTW, it's better to remove `<?> …` part, it doesn't buy you anything in Megaparsec, probably makes error messages worse.
