### ISSUE TITLE
NonEmpty parsers

### ISSUE THREAD

**Issue by minad** [mrkkrp/megaparsec#131]
Hi,

I've seen that you use NonEmpty internally. What about providing combinators like `some'`, `sepBy1'`, etc. which return NonEmpty lists? Probably it would be worth to expose this level of detail in the types since NonEmpty is also part of base.

Daniel

**Comment by mrkkrp** [comment]
This would be a good idea if we could make types of those functions (`some` , `sepBy1`) return `NonEmpty`, but at least `some` in defined in `Control.Applicative` and it returns plain list, so let's stick to this for consistency.

I don't think providing these functions will buy us anything but possible confusion. It's trivial to apply `fromList` function to the basic combinators if you want though.

**Comment by minad** [comment]
Yeah, this is some kind of legacy issue. It would be nicer to implement sepBy1 etc in terms of `toList . sepEndBy1'` etc.

It is always the question how far you want to push it with the types. Why did you use NonEmpty internally if I may ask? Was it worth it?

**Comment by mrkkrp** [comment]
I think it's worth it because it guards against empty labels and empty expected/unexpected things, but at the same time it's very rare that you need to construct a `ParseError` value manually, so the syntactic overhead is also avoided. This way it's basicly a good thnig at no cost.

**Comment by mrkkrp** [comment]
I'll close this one if you don't mind.

**Comment by minad** [comment]
Sure, maybe we could reconsider in the far future assuming that more people are using NonEmpty then ;)

I am using my own parsers producing NonEmpty where my AST contains such nodes.
