### ISSUE TITLE
A possible bug in "Text.Megparsec.Expr" module

### ISSUE THREAD

**Issue by mrkkrp** [mrkkrp/megaparsec#132]
A Parsec user reports in aslatter/parsec#57 that the function `buildExpressionParser` (named `makeExprParser` in Megaparsec) may have a bug.

----

In the uncommon case where a prefix operator has lower precedence than an infix operator, such as in boolean expressions, e.g

* `&&` is an infix operator.
* `!` is a prefix operator of lower precedence.

The input `!a && b` is correctly parsed `Not (And a b)`, but the parser fails to parse `a && !b` (as `And a (Not b)`).

----

We should check if this takes place with Megaparsec and then add a test and fix it if at all possible (should be doable without major re-write I hope).

**Comment by mrkkrp** [comment]
I can reproduce this with the following code:

```haskell
module Main (main) where

import Control.Applicative (empty)
import Control.Monad
import Text.Megaparsec
import Text.Megaparsec.Expr
import Text.Megaparsec.String
import qualified Text.Megaparsec.Lexer as L

sc :: Parser ()
sc = L.space (void spaceChar) empty empty

lexeme :: Parser a -> Parser a
lexeme = L.lexeme sc

symbol :: String -> Parser String
symbol = L.symbol sc

data Expr =
  And Expr Expr |
  Not Expr |
  Val String
  deriving (Eq, Ord, Show)

val :: Parser Expr
val = Val <$> lexeme (some lowerChar)

op :: [[Operator Parser Expr]]
op =
  [ [ InfixN (And <$ symbol "&&")]
  , [ Prefix (Not <$ symbol  "!")] ]

expr :: Parser Expr
expr = makeExprParser val op

main :: IO ()
main = return ()
```

**Comment by mrkkrp** [comment]
**This is not easily fixable.** What's going on is that the `makeExprParser` works with precedence on “layer-by-layer” basis making term parser more and more complex. So when infix operator is added, there is no prefix operator at all as far as `makeExprParser` concerned. This is why we get this error.

Here is what we get using the new `dbg` primitive wrapped around `val` and operators:

**Successful** (`!` is prefix operator, and the rest is its term):

```
λ> parseTest expr "!a && b"
symbol !> IN: "!a && b"
symbol !> MATCH (COK): '!'
symbol !> VALUE: Expr -> Expr

val> IN: "a && b"
val> MATCH (COK): "a "
val> VALUE: Val "a"

symbol &&> IN: "&& b"
symbol &&> MATCH (COK): "&& "
symbol &&> VALUE: Expr -> Expr -> Expr

val> IN: 'b'
val> MATCH (COK): 'b'
val> VALUE: Val "b"

Not (And (Val "a") (Val "b"))
```

**Unsuccessful** (parsing of `!` fails and we get into “next level” where prefix `!` does not exist, only the infix `&&`):

```
λ> parseTest expr "a && !b"
symbol !> IN: "a && !b"
symbol !> MATCH (EERR): <EMPTY>
symbol !> ERROR:
symbol !> 1:1:
symbol !> unexpected 'a'
symbol !> expecting '!'

val> IN: "a && !b"
val> MATCH (COK): "a "
val> VALUE: Val "a"

symbol &&> IN: "&& !b"
symbol &&> MATCH (COK): "&& "
symbol &&> VALUE: Expr -> Expr -> Expr

val> IN: "!b"
val> MATCH (EERR): <EMPTY>
val> ERROR:
val> 1:6:
val> unexpected '!'
val> expecting lowercase letter

1:6:
unexpected '!'
expecting lowercase letter
```

----

The design of `makeExprParser` actually makes sense and it's even elegant. I decided to keep it “as is”, at least for now. Closing and labelling and “won't fix”. Feel free to post here if you happen to have ideas how to improve the parser.

**Comment by ijks** [comment]
Hi, looks like I ran into a similar problem. Specifically, I have a `**` (exponentiation operator) with a higher precedence than a `-` (negation) operator. Parsing something like `1 ** -2` fails.

I understand reworking `makeExprParser` to support this is complicated, and I unfortunately have no idea where I'd begin if I wanted to make a PR to fix it. Is a workaround possible though? I've already used tricks like creating a larger parser from multiple `makeExprParser`s to solve another problem; would that be useful here maybe? (Just thinking out loud.)

Also, it would be nice if this limitation was mentioned in the docs, and I _am_ willing and able to make a PR for that. :)

P.S. It was a very pleasant surprise to find this bug already reported with such a clear explanation!

**Comment by mrkkrp** [comment]
> Also, it would be nice if this limitation was mentioned in the docs, and I am willing and able to make a PR for that. :)

You may certainly go ahead with that.

I don't know of a workaround, and I'm a bit busy right now to think about it...
