### ISSUE TITLE
What would you do differently?

### ISSUE THREAD

**Issue by mckeankylej** [mrkkrp/megaparsec#134]
Hi I am writing a port of megaparsec to purescript. If you had the ability to do it all again, is there anything you would change? Also keep in mind purescript doesnt have fun deps or type families (yet).

**Comment by mrkkrp** [comment]
I'm satisfied with the state of the library. Mostly everything I wanted to do I already did. One thing that could be done better is testing. It would be nicer to use Hspec for tests in combination with a helper package `hspec-megaparsec`, but I'll get to that.

**Comment by mckeankylej** [comment]
Thanks I will be sure to test everything!
