### ISSUE TITLE
Expose SourcePos Arbitrary instance

### ISSUE THREAD

**Issue by flip111** [mrkkrp/megaparsec#139]
I'm capturing the source position of tokens in my syntax tree. And also i'm using QuickCheck to generate some ast, print it and then parse it to see if all is ok. But to generate the ast i need an Arbitrary instance of SourcePos. I found it here

https://github.com/mrkkrp/megaparsec/blob/6a7c41d88998d5358b10920497fb6efe388ab3a5/tests/Util.hs#L249-L253

Can this be exposed?

**Comment by mrkkrp** [comment]
I'm already doing this in #138 and we are migrating to Hspec + `hspec-megaparsec` (which is also is going to be more powerful). Patience!

**Comment by flip111** [comment]
Looks good ! I don't watch all issues so i didn't know about this update.

**Comment by flip111** [comment]
As a temporary workaround i pasted this in my own source file

```haskell
shortString :: Gen String
shortString = sized $ \n -> do
  k <- choose (0, n `div` 2)
  vectorOf k arbitrary

instance Arbitrary M.SourcePos where
  arbitrary = M.SourcePos
    <$> shortString
    <*> (unsafePos <$> choose (1, 1000))
    <*> (unsafePos <$> choose (1, 100))
```

**Comment by mrkkrp** [comment]
Resolved in #138.

**Comment by flip111** [comment]
Thank you @mrkkrp i will test it as soon as it shows up in any nightly of hackage, atm i'm on `nightly-2016-07-07`

**Comment by mrkkrp** [comment]
Megaparsec 5.1.0 will probably be released next week, next day after release it will show up in nightly builds.

**Comment by flip111** [comment]
I have a problem with my quickcheck test related to SourcePos. I built a concrete syntax tree (CST) with quickcheck arbitrary (that's why i needed the Arbitrary instance of SourcePos). Then i pretty-print this CST, then i parse it with my megaparsec parser. Then i should end up with the same CST which was generated by quickcheck.

However the generated SourcePos does not match with the actual SourcePos. For example this is the first part of my data:

Generated by quickcheck
```
CC [CI_Library (LC (Ter {t_text = (SourcePos {sourceName = "", sourceLine = Pos 562
```

output of pretty-printer into parser
```
CC [CI_Library (LC (Ter {t_text = (SourcePos {sourceName = "", sourceLine = Pos 1
```

Quickcheck generated a source position of 562 for the first terminal, which is weird because it's a concrete syntax tree so it capture everything, so the first token should start on position 1. Which is the correct output (see second snippet).

I have not found a solution for this but i'm thinking of 3 possible solutions:

1. let quickcheck generate correct source positions
2. traverse the input and output CST to set SourcePos to the same value before being compare with quickcheck
3. change the equality implementation of the data

I thought 2 would be the easiest so i first investigate this, but it turns out it's not a trivial problem. Would possibly need to use libraries such as https://hackage.haskell.org/package/mono-traversable or https://hackage.haskell.org/package/pandoc-types-1.16.1.1/docs/Text-Pandoc-Walk.html

I'm not even sure if this should be covered by megaparsec actually .. any idea?

**Comment by mrkkrp** [comment]
Well, what Megaparsec's `Arbitrary` instance does looks reasonable to me — it just generates random `SourcePos`. That's what I generally want to get in my tests that deal with `SourcePos`. In your case, I would just made a function that would “normallize” CST after generation (and made it part of corresponding `Arbitrary` instance for CST).

At any rate, this is not an issue with Megaparsec's `Arbitrary` instance for `SourcePos`, IMO.
