### ISSUE TITLE
Add a primitive combinator that can return 'Either (ParseError t e) a' things

### ISSUE THREAD

**Issue by mrkkrp** [mrkkrp/megaparsec#145]
Simply put, the combinator will allow not to fail completely in case of parse error, but to get the error inside of `Left` and do things with it. One use case is that you can modify the `ParseError` and then re-fail with the new error. This has been requested in #111, cc @mikeplus64.

More generally, this allows to do arbitrary things with parse errors, like logging them and what-not. I think it's a valuable addition to the library.

We should also provide a `refail` function:

```haskell
refail :: MonadParsec e s m => ParseError (Token s) e -> m a
```

to fail with pre-constructed `ParseError`. This is easy to build on top of `failure` if we first set source position to match position of given `ParseError` — no new primitives are necessary.

**Comment by flip111** [comment]
This helps to support https://github.com/mrkkrp/megaparsec/issues/118
