### ISSUE TITLE
Indent parsing

### ISSUE THREAD

**Issue by mpickering** [mrkkrp/megaparsec#148]
I am trying to write a parser which parses a list but it seems the indent parsing functions are setup differently than I need.

The type of lists I want to parse is..

```
* item
   1 continue 
   * nested list
* new list item
```

Notice here that the first element of the list is on the _same line_ as the reference token. The level of identation should be set at the start of "item" and "nested" for the two levels of list. 

It seems the current combinators expect a reference marker to be on its own line and the indented content to follow on subsequent lines. Is there a way to get this behaviour?

**Comment by mrkkrp** [comment]
The provided helpers for indentation-sensitive parsing cover what seemed to me the most common cases. Keep in mind though, that they are not something built-in. You could build all these helpers yourself independently. That said, you can create your own helpers that do exactly what you want — Megaparsec does not get in your way.

I'm sorry, I currently have no time to write code that would solve your problem, but you could start by reading source code of `Text.Megaparsec.Lexer` and adapting it to your needs. I believe many helpers you'll be able to reuse. Indentation-sensitive parsing is certainly feasible with Megaparsec, and it has been done, but I have not so much feedback from actual users as I wish, so if you want to add new helpers or you have any other ideas, please let me know.

I'll let this hang for now, maybe I'll have more time in the future and I'll be able to give you more concrete advice.

**Comment by mrkkrp** [comment]
@mpickering Have you ever succeeded with this? If not, I'm now on vacation and I have some time to spend to help you if you wish. :-D

If you have resolved this on your own, please close the issue.

**Comment by mrkkrp** [comment]
Closing due to lack of response. You can reopen later if it makes sense.
