### ISSUE TITLE
charLiteral does not support \&

### ISSUE THREAD

**Issue by adituv** [mrkkrp/megaparsec#154]
Attempting to parse e.g. "\"\\x123\\&4\"" with the `stringLiteral` function defined in the documentation for `charLiteral` fails on the \& when I would expect the result to be `"\x123\&4"` (`['\x123', '4']`).  The failure seems to be because `readLitChar` does not read `\&` even though it's in the Haskell report; perhaps because `\&` is technically not a character.

This may or may not be intended, but I think it is not intended because of the documentation "The literal character is parsed according to the grammar rules defined in the Haskell report."

This could alternatively be seen as a bug in `readLitChar`.

**Comment by mrkkrp** [comment]
Hmm, if I try to enter `'\&4'` in GHCi I get:

> lexical error in string/character literal at character '&'

Are you sure it's part of Haskell syntax? I can't have a char like that: `foo = '\&4'`.

**Comment by adituv** [comment]
Good point, it's not a char as such; it's used only in strings and represents the lack of a character/an empty string.  The only use I can think of is in strings like the one above where you're separating a numeric escape code from a numeral.  Perhaps I should just add the case to stringLiteral

**Comment by mrkkrp** [comment]
I think we could also update the docs to mention this and perhaps add an example of code that supports the `\&` combination properly?
