### ISSUE TITLE
5.1.2 Documentation on Hackage points to old source

### ISSUE THREAD

**Issue by WeeBull** [mrkkrp/megaparsec#155]
Looks like something funny happened with the 5.1.2 upload to Hackage. The documentation appears to be up to date, but the source looks to be pre-5.0.

For example, compare [5.1.1 ParseError](https://hackage.haskell.org/package/megaparsec-5.1.1/docs/src/Text-Megaparsec-Error.html#ParseError) with [5.1.2 ParseError](https://hackage.haskell.org/package/megaparsec-5.1.2/docs/src/Text-Megaparsec-Error.html#ParseError)

**Comment by mrkkrp** [comment]
Thank you for taking time to report this. Please use #153 for further discussion.
