### ISSUE TITLE
how to fail when building expression parsers

### ISSUE THREAD

**Issue by abnud1** [mrkkrp/megaparsec#156]
I'm writing a compiler for java for my university project.  

Now I want to build the expression parser, according to examples a sample parser could be written like this : 

```
expr = makeExprParser term table <?> "expression"

term = parens expr <|> integer <?> "term"

table = [ [ prefix  "-"  negate
          , prefix  "+"  id ]
        , [ postfix "++" (+1) ]
        , [ binary  "*"  (*)
          , binary  "/"  div  ]
        , [ binary  "+"  (+)
          , binary  "-"  (-)  ] ]

binary  name f = InfixL  (f <$ symbol name)
prefix  name f = Prefix  (f <$ symbol name)
postfix name f = Postfix (f <$ symbol name)
```

The problem is that f has signature `a -> a -> a` but in java I have to do semantic checking so f should have been `a -> a -> m a` so that I can `fail` with semantically wrong expressions.  

I don't know how to deal with this, Infix(L,R,N) , Prefix and Postfix all expects `m (a -> a -> a)`, now I could fail `m (a->a->a)` but I need access to the parsed expressions which I don't have.  

The only solution for me now is to return an `f` that errors and catch that error inside `Prefix`,`Postfix`,etc but that means I need IO which seems cumbersome to me.  

Is there a way to do this ?

**Comment by mrkkrp** [comment]
Hi, indeed the current API is not handy in this case, we however can't just change it at this point (perhaps in 6.0?).

What you can do, is to encode failure in the type `a` perhaps. If `a` is `Either MyError MyTerm`, then your term parser would just always return `Right term`, while the function that you provide (of type `Either MyError MyTerm -> Either MyError MyTerm -> Either MyError MyTerm`) to `InfixR` and friends could return `Left MyError` in case of trouble. It should also propagate errors from its arguments (if they are `Left`s).

Then in the `MonadParsec` monad, you could examine whether it's `Left` or `Right` and act accordingly. Hope it helps!

**Comment by abnud1** [comment]
hmmm I like the last solution, until 6.0 arrives I'm going to use it, thank you .

**Comment by mrkkrp** [comment]
Closing then for now.
