### ISSUE TITLE
error type is confusing when getting started

### ISSUE THREAD

**Issue by simonmichael** [mrkkrp/megaparsec#157]
When (re)starting with megaparsec I always trip up on "Ambiguous type variable ‘e0’ arising from a do statement prevents the constraint ‘(ErrorComponent e0)’ from being solved." and have to dig for the solution. Some ideas:

- mention that your first parser will need a type signature, and include it in the minimal example

- move that example (currently with the `parse` function) as close to the top of the page as possible

- shouldn't the first six parser-running functions show the same `(ErrorComponent e, Stream s) => ` constraint that `parse` does ?

- explain what `Dec` is. A more mnemonic name would be nice.

Thank you very much for megaparsec!

**Comment by simonmichael** [comment]
(In the main haddock, I mean: eg http://hackage.haskell.org/package/megaparsec-5.1.2/docs/Text-Megaparsec.html).

**Comment by mrkkrp** [comment]
These are fair points. I usually always specify signatures for top-level definitions, so I don't run into this problem often. `Dec` is a poor name, although it's difficult to change it now. It has the virtue of being short, though. About constraints, you probably refer to `parseMaybe`, which indeed has the constraints, while `parse` does not. I remember GHC 8 told me that the constraints were not necessary, so I dropped them. The logic here is that you still can run all these parsers even though they are not instances of `MonadParsec` unless `e` and `s` are instances of right classes: `(ErrorComponent e, Stream s) => MonadParsec e s (ParsecT e s m)`. So technically the error messages you see only arise when you use methods of `MonadParsec` without GHC knowing your `e`, not when you run your parser.

I'll adjust the docs this weekend, thanks for opening the issue!
