### ISSUE TITLE
some accepts combinator that consumes no input

### ISSUE THREAD

**Issue by flip111** [mrkkrp/megaparsec#158]
This is a nice check https://github.com/devonhollowood/megaparsec/blob/66ebd88eb3cd99b34a4749d030eebfa6d1529ec6/Text/Megaparsec/Prim.hs#L367-L370 i saw it from this issue https://github.com/mrkkrp/megaparsec/issues/122

However for some this check seems to be missing ... which is a bit strange because if you have "many of nothing" and many is 10 then "10x nothing" is not going to work but "0x nothing" would be ok. But in the case of `some` it starts at "1x nothing" which is wrong. So in the case of `some` this check seems to be even more important since in the case of `many` there is still one "chance" that it will actually be ok

**Comment by mrkkrp** [comment]
The check is not missing, `some` is defined in `Control.Applicative`: https://hackage.haskell.org/package/base-4.9.0.0/docs/Control-Applicative.html#v:some, and by default it's defined via `many` which has the check and thus `some` also has the check.

>  if you have "many of nothing" and many is 10 then "10x nothing" is not going to work but "0x nothing" would be ok. But in the case of some it starts at "1x nothing" which is wrong

Sorry, I'm unable to grasp your logic here at all.

**Comment by flip111** [comment]
When i run this code it seems that it doesn't have the check.

```haskell
module Main where

import Text.Megaparsec
import Text.Megaparsec.String

main :: IO ()
main = do
  putStrLn "hello world"

simple :: Parser String
simple = lookAhead $ string "hello"

a = parse (many simple) "" "hello"
{-
λ> a
*** Exception: Text.Megaparsec.Prim.many: combinator 'many' is applied to a parser that may consume no input.
CallStack (from HasCallStack):
  error, called at ./Text/Megaparsec/Prim.hs:376:11 in megaparsec-5.0.1-Kbr1rj2aE5WBrRq6kJu93J:Text.Megaparsec.Prim
-}

b = parse (some simple) "" "hello"
{-
Ok, modules loaded: Main.
λ> b

--- does not terminate ---
-}
```

**Comment by mrkkrp** [comment]
This is interesting, I don't see why this would happen, I'll revisit this when I have time.

**Comment by mrkkrp** [comment]
Ah OK, at least in the newest version of `base`, `some` is not defined in terms of `many`, but via its own definition. This would make your request valid if we chose to keep `error` in `many`. Another thing I wonder about what imact this may have on performance of default `some` vs manually written `some`, like `many`. I need to benchmark this (and also default `many` vs manually defined `many`), and perhaps we could write `some` manually and replace the default if it's faster.

**Comment by flip111** [comment]
Sounds good to me, happy new year !

**Comment by mrkkrp** [comment]
Happy new year! :-D
