### ISSUE TITLE
Question: is there an equivalent to parsec's makeTokenParser in megaparsec?

### ISSUE THREAD

**Issue by mgmeier** [mrkkrp/megaparsec#162]
(cf. ```Text.Parsec.Token.makeTokenParser```, generating parsers from some language definition)

megaparsec doesn't offer that nice and very helpful little helper (yet)... or did I miss something? Are there plans to have that kind of functionality in megaparsec, too?

**Comment by mrkkrp** [comment]
No such plans, it was removed on purpose. That helper is particularily inflexible, as it only allows to tweak certain parameters and if you need something that authors of Parsec didn't think of, you have no other choice but to copy the entire source code of `Token.hs` module and edit it (that happened a couple of times for sure). You should try to use Megaparsec's `Text.Megaparsec.Lexer` module instead.

See also: https://mrkkrp.github.io/megaparsec/tutorials/switch-from-parsec-to-megaparsec.html#what-happened-to-text.parsec.token

**Comment by mrkkrp** [comment]
Closing for now.

**Comment by mgmeier** [comment]
As a follow up: meanwhile I had enough time to switch my project to megaparsec. @mrkkrp The link you provided somehow slipped my attention before, so thanks for mentioning! Can confirm, `Text.Megaparsec.Lexer` works fine, just as described in the migration tutorial.
