### ISSUE TITLE
Parameterise MonadParsec on the State object also?

### ISSUE THREAD

**Issue by WeeBull** [mrkkrp/megaparsec#164]
This is just an idea that I wanted to throw out there and discuss.

I was wanting to write a new instance of `MonadParsec` which layered of top of the existing behaviour. This new instance would add some debugging features like detecting and failing when encountering left-recursion, or reporting the stack of parsers when a failure occurred. These would require new version of the combinators and extra state to be stored during parsing. 

Unfortunately, because the `MonadParsec` type doesn't take the `State` type as a parameter, I can't define an instance of `MonadParsec` which uses a different, expanded, state. I didn't want to add these extra state items to the standard `State` type as that could be a fairly substantial overhead, and only necessary when you're debugging. It would also be a pain to maintain as it would be desirable in the official Megaparsec tree (for the same reasons).

An alternative would writing an instance which uses a state monad type as the `m` parameter of `MonadParsec` and having my extra state in there. The trouble there is that the instance is already written in `Prim.hs`, and defines all the combinators to be the normal versions. My interpretation of this is that the state can interact with the parsing, but not the combinators themselves. 

I'd like to write my code in a way that could be layered on top of Megaparsec, but I don't currently see how I can do that. My thought was that by making the `MonadParsec` type take it's state type as a parameter, alternative combinators implementations could be written. I don't know what fallout such a change would have though.

Thoughts?

**Comment by mrkkrp** [comment]
Hi, sorry for late response (a lot of things were going on these days). What about putting this functionality into a monad transformer that is conceptually similar `StateT`, but it could use different type (`newtype` or written from scratch, depends on what you'll be doing and how important performance is). Then you could define combinators that work with this.

**Comment by WeeBull** [comment]
No problem about the delay. I'm only doing stuff on this part time.

That could work. Part of the reason i raised this was to get another point
of view, as i was locked in on one solution.

I'll have a play and see how it out.

**Comment by flip111** [comment]
@WeeBull did you arrive at a workable solution?

**Comment by WeeBull** [comment]
@flip111 Honestly, I've not had time to get beyond thought experiments. It's a side project, and paying work has gotten in the way recently.

I still haven't got a good reason Mark's suggestion shouldn't work though.

**Comment by mrkkrp** [comment]
I'm closing this for now, as the question seem to be answered. Feel free to reopen if you have new thoughts.
