### ISSUE TITLE
The documentation should document how to modify the documentation

### ISSUE THREAD

**Issue by alexanderkjeldaas** [mrkkrp/megaparsec#169]
The gh-pages branch only has "auto sync" commits, so clearly the documentation resides in some other system.

The documentation should probably have some link to whatever system is used to edit it.  Right now it contains generic links to github, but it is lacking in discoverability - i.e. given that I'm on the github page, I have no clue on how to change the documentation.

**Comment by mrkkrp** [comment]
This is a good point, I'll add instructions how to modify it. FYI, it's here: https://github.com/mrkkrp/megaparsec-site.

**Comment by mrkkrp** [comment]
I'll also add something to the site itself so users could quickly jump to the corresponding repo.

**Comment by mrkkrp** [comment]
I have added the “Edit the site” link to the menu. Thanks for opening the issue!
