### ISSUE TITLE
Getting the Source position as char number

### ISSUE THREAD

**Issue by wdanilo** [mrkkrp/megaparsec#170]
Hi! Is it possible to get source position not as line / col but just as the char number from the beginning of the source?

**Comment by mrkkrp** [comment]
Currently not, but this is certainly possible to add. I wonder how it would affect performance though, probably not much.

**Comment by wdanilo** [comment]
Cannot we make it as an optional overlay-parser so only users that need this functionality will get it? I think counting tokens would make it working, right?

**Comment by mrkkrp** [comment]
If I remember correctly upating of position only happens in `token` and `tokens` primitives, so we could just change these. I'm not sure I understand what you mean by "optional overlay parser", how would such parser be implemented technically? Do you have an idea about this?

**Comment by wdanilo** [comment]
Sure, I've done something like that for my purpose, so here is just a scratch code:

```
-----------------------------
-- === OffsetParser === --
-----------------------------

-- === Definition === --

newtype OffsetParserT m a = OffsetParserT (StateT Word64 m a) deriving (Functor, Applicative, Alternative, Monad, MonadPlus)
makeWrapped ''OffsetParserT


-- === OffsetParsing === --

class Monad m => OffsetParsing m where
    getOffset :: m Word64
    putOffset :: Word64 -> m ()

instance Monad m => OffsetParsing (OffsetParserT m) where
    getOffset = wrap'   get ; {-# INLINE getOffset #-}
    putOffset = wrap' . put ; {-# INLINE putOffset #-}



-- === Utils === --

incOffset :: OffsetParsing m => m ()
incOffset = putOffset =<< succ <$> getOffset ; {-# INLINE incOffset #-}

evalOffsetParserT :: Monad m => OffsetParserT m a -> m a
evalOffsetParserT = flip evalStateT 0 . unwrap' ; {-# INLINE evalOffsetParserT #-}


-- === Instances === --

instance MonadParsec e s m => MonadParsec e s (OffsetParserT m) where
    failure           = wrap' .:. failure                          ; {-# INLINE failure           #-}
    label s           = wrapped %~ label s                         ; {-# INLINE label             #-}
    hidden            = wrapped %~ hidden                          ; {-# INLINE hidden            #-}
    try               = wrapped %~ try                             ; {-# INLINE try               #-}
    lookAhead         = wrapped %~ lookAhead                       ; {-# INLINE lookAhead         #-}
    notFollowedBy     = wrapped %~ notFollowedBy                   ; {-# INLINE notFollowedBy     #-}
    withRecovery f    = wrapped %~ withRecovery (unwrap' <$> f)    ; {-# INLINE withRecovery      #-}
    observing         = wrapped %~ observing                       ; {-# INLINE observing         #-}
    eof               = wrap' eof                                  ; {-# INLINE eof               #-}
    token             = ((<* incOffset) . wrap') .: token          ; {-# INLINE token             #-}
--     tokens            = todo
    getParserState    = wrap' getParserState                       ; {-# INLINE getParserState    #-}
    updateParserState = wrap' . updateParserState                  ; {-# INLINE updateParserState #-}
```

I'm on my phone right now so I will not fill the tokens definition, but it should be straightforward to do.
Now you can use `OffsetParserT` as transformer and `getOffset` to read the current buffer position. Because it bases on `StateT` it should have negligible or any effect on performance when compiling with `-O`.

**Comment by mrkkrp** [comment]
I see what you mean. I think however it would be fairly straightforward to add token counter to parser state, it should not add any significant overhead. Would be useful for one other feature too.

**Comment by wdanilo** [comment]
Probably yes, but keeping the same information in two forms in parser state is just an "ugly" design decision for me. Of course this is just my point of view, but I just can't stand it from the "purity" perspective.

**Comment by mrkkrp** [comment]
> Probably yes, but keeping the same information in two forms in parser state is just an "ugly" design decision for me.

Not sure what you mean. I propose just adding offset (= number of processed tokens), it does not duplicate anything, because it's not possible to infer it from line/column information we already store.

**Comment by wdanilo** [comment]
Mark,
both information `(line, col)` and `buffer offset` carry the same information "how far along are we". They store information about position encoded in different metrics. Surely you cannot convert between them directly, however you can between `(line,col,source)` and `(bufferOffset, source)`. Parser knows the source code, so the information about "how far along are we" would be stored twice (indirectly). Generally it would not be so bad, but we are talking about "core design" and I belive that "core design" should be kept simple, always. This way I just prefer solution with monad transformer (anyone could use it if they want to) or with keeping some kind of map between `offset` and `(line,col)`.

Do you see what I mean? If not, I'll try to explain it another way around. The topic I try to describe is not obvious one and depends on "preferences" - mine, yours, community. However the quality and of parsing library I use is very important for the product I'm working on.

**Comment by mrkkrp** [comment]
Yes, we can go line/column → offset if we have stream of tokens. Although I'd argue that at any given moment of time we only have *the rest of the stream* in the parser state, because already processed tokens are removed from it, so it's not really possible to convert between the position representations using only parser state.

If we want to have offset, storing it in parser state is simply the best way to do it, both from performance perspective and backward-compatibility perspective, IMO.

**Comment by wdanilo** [comment]
Mark, sure, go with it. I would just prefer more modular solution like the one to keep the "core" in the simplest possible form.

**Comment by mrkkrp** [comment]
This will be in the next release 5.2.0, unless benchmarks show that it makes things slower (not marginally slower, at least).

**Comment by mrkkrp** [comment]
This feature is now part of Megaparsec.
