### ISSUE TITLE
Mention import of empty in documentation

### ISSUE THREAD

**Issue by inktrap** [mrkkrp/megaparsec#171]
I would like to mention a small documentation issue:

[Parsing a simple imperative language ](https://mrkkrp.github.io/megaparsec/tutorials/parsing-simple-imperative-language.html) mentions ``empty`` and new users who want to use it should be informed that they have to 
~~~
import Control.Applicative (empty)
~~~

``empty`` is not imported in the example.

**Comment by mrkkrp** [comment]
Thanks, I've added a mention of `Control.Applicative` in the text.
