### ISSUE TITLE
Obtain last parsed character

### ISSUE THREAD

**Issue by wdanilo** [mrkkrp/megaparsec#173]
Hello! Is there any easy way to obtain last parsed character in Megaparsec? I can create my custom parser transformer which will remember the last char when `token` is called, but maybe there is something already built-in?

**Comment by mrkkrp** [comment]
Nope, nothing built-in, this is not a particularily popular use-case! Is this related to the Luna language?

**Comment by wdanilo** [comment]
I know it is not very popular but sometimes it is accessible out of the box, like in Trifecta (which remembers the last line for pretty errors). It is indeed related to Luna – if you'll like to talk more about it, just pm me via mail :)

**Comment by mrkkrp** [comment]
Since the question is kind of answered, I'll close this if you don't mind :-)
