### ISSUE TITLE
MonadParsec.token function is too restricted

### ISSUE THREAD

**Issue by wdanilo** [mrkkrp/megaparsec#175]
Hi! I want to implement a "history parser" which basically remembers each parsed token and pushes it to a list kept in state. The signature of `MonadParsec.token` prevents us from doing something like this.

It's current signature is `token :: (Token s -> Either <left> a) -> Maybe (Token s) -> m a` and we clearly see it could not use any context when evaluating the token handling function. A simple fix is sufficient here:  `token :: (Token s -> Either <left> (m a)) -> Maybe (Token s) -> m a` .

I know this is not very popular case, but even so, impossibility to define parser transformers that handle tokens is a design weakness.

Here is a scratch implementation of "history-wannable parser":

```
import qualified Text.Megaparsec as Parser
import           Text.Megaparsec hiding (parse, (<?>), Pos)
import           Text.Megaparsec.Prim (MonadParsec)

import Control.Monad.State (StateT, evalStateT, get, put)


-----------------------------
-- === HistoryParser === --
-----------------------------

-- === Definition === --

newtype HistoryParserT s m a = HistoryParserT (StateT [s] m a) deriving (Functor, Applicative, Alternative, Monad, MonadPlus, MonadIO)
makeWrapped ''HistoryParserT


-- === HistoryParsing === --

class Monad m => HistoryParsing s m | m -> s where
    getHistory :: m [s]
    putHistory :: [s] -> m ()

    default getHistory :: (m ~ t n, MonadTrans t, Monad n, HistoryParsing s n) => m [s]
    default putHistory :: (m ~ t n, MonadTrans t, Monad n, HistoryParsing s n) => [s] -> m ()
    getHistory = lift   getHistory
    putHistory = lift . putHistory

instance Monad m => HistoryParsing s (HistoryParserT s m) where
    getHistory = wrap'   get
    putHistory = wrap' . put


-- === Modification === --

modifyHistoryM :: HistoryParsing s m => ([s] -> m (a, [s])) -> m a
modifyHistoryM f = do
    s <- getHistory
    (a, s') <- f s
    putHistory s'
    return a

modifyHistoryM_ :: HistoryParsing s m => ([s] -> m ([s])) -> m ()
modifyHistoryM_ = modifyHistoryM . (fmap . fmap) ((),)

modifyHistory :: HistoryParsing s m => ([s] -> (a, [s])) -> m a
modifyHistory = modifyHistoryM . fmap return

modifyHistory_ :: HistoryParsing s m => ([s] -> [s]) -> m ()
modifyHistory_ = modifyHistoryM_ . fmap return


-- === Utils === --

recordToken :: HistoryParsing s m => s -> m ()
recordToken = modifyHistory_ . (:)

recordTokens :: HistoryParsing s m => [s] -> m ()
recordTokens = modifyHistory_ . (<>) . reverse


-- === Instances === --

instance MonadParsec e s m => MonadParsec e s (HistoryParserT (Token s) m) where
    failure           = wrap' .:. failure
    label s           = wrapped %~ label s
    hidden            = wrapped %~ hidden
    try               = wrapped %~ try
    lookAhead         = wrapped %~ lookAhead
    notFollowedBy     = wrapped %~ notFollowedBy
    withRecovery f    = wrapped %~ withRecovery (unwrap' <$> f)
    observing         = wrapped %~ observing
    eof               = wrap' eof
    -- token             = impossible
    -- tokens f ts       = ...
    getParserState    = wrap' getParserState
    updateParserState = wrap' . updateParserState
```

**Comment by mrkkrp** [comment]
Every design has its weaknesses :-) I don't know how I feel about this, at any rate, the speed with which you generate feature requests exceeds the speed at which the project is going progress. In near future version 5.2.0 will be released (in February I think), and its feature set is now fixed and quite conservative. I can't say about further releases, but they won't be fast-paced for sure.

I think for such custom stuff it may be easier to just keep an internal fork of Megaparsec, since even if Megaparsec gets these new features, it's not going to happen very soon.

**Comment by polux** [comment]
Not sure if this is the same feature request but I often need to reconstruct the string of what I just parsed. Ideally there would be some combinator

```
record :: Parser a -> Parser String
```

which would return the text accepted by its argument. (Or `Parser a -> Parser (a, String)` in case the result is required.) Is it possible to implement something like this with megaparsec today or is it what this feature request is about?

**Comment by mrkkrp** [comment]
@polux Not quite the same. There are ways to do what you describe, but they are inefficient. With the feature #170 (will be probably added in Megaparsec 5.2.0, which should be released in February) it will be easier and more efficient:

1. get current stream
2. get number of processed tokens so far
3. run parser
4. get new number of processed tokens
5. use the difference in number of processed tokens to grab the parsed text
   from previously saved stream

If you would like to open a feature request, please open a separate issue. This looks good to be added in version 5.3.0.

**Comment by polux** [comment]
Ah great! I missed #170. I was looking for something like this but only found how to get the position, from which it is hard to retrieve the actual token. I'll open a feature request, thanks!

**Comment by mrkkrp** [comment]
Closing this because currently `token` is not the single way to "watch" consumption of tokens. There are `tokens`, `takeWhileP`, `takeWhileP1`, and `takeP` as well. While it's clear where to put this watching functionality in `token`, it's not so clear where to put custom monadic code in those.
