### ISSUE TITLE
Get list of tokens recognized after a successful parse 

### ISSUE THREAD

**Issue by polux** [mrkkrp/megaparsec#176]
I often need to reconstruct the string of what I just parsed. Ideally there would be some combinator

```
record :: Parser a -> Parser String
```

which would return the text accepted by its argument. Or `Parser a -> Parser (a, String)` in case the result is required.

As noted by @mrkkrp in https://github.com/mrkkrp/megaparsec/issues/175#issuecomment-275858230 it will be easily implementable once #170 is released. I think it would be nice to have it exposed as part of megaparsec though.

**Comment by mrkkrp** [comment]
Added as `match` (the name `attoparsec` uses).

**Comment by polux** [comment]
Great, thanks!
