### ISSUE TITLE
Correct 'indentBlock' so it accepts input that does not end with a newline

### ISSUE THREAD

**Issue by mrkkrp** [mrkkrp/megaparsec#178]
As described in comments to #119, `indentBlock` currently requires the input to contain the final newline, but it would make sense to allow it be missing. For example, `"aaa\n  test\n"` is parsed OK, but `"aaa\n  test"` is rejected.

Note to self: as part of the fix, we should make sure that all indentation-sensitive combinators behave properly in this situation. New tests should be added.

**Comment by mrkkrp** [comment]
@liskin I consider it an outright bug now. Working on a fix and new tests.

**Comment by liskin** [comment]
Oh, I was meant to open an issue and postponed it and then forgot it. Sorry about that and thanks for not letting it slip into oblivion. :-)

**Comment by mrkkrp** [comment]
This is fixed now, 5.2.0 is on its way.

**Comment by liskin** [comment]
Thanks!
