### ISSUE TITLE
Something optional = expected ??

### ISSUE THREAD

**Issue by flip111** [mrkkrp/megaparsec#183]
I have a rather strange situation where i have this parser

```haskell
p_exponent :: Parser String
p_exponent = do
  ex <- trace "Exponent ex" $ M.string' "e"
  pp <- trace "Exponent eplus pp" $ optional_string "+"
  dd <- trace "Exponent dd" $ M.digitChar
  trace ("Exponent return " ++ ex ++ pp ++ [dd]) $ return $ ex ++ pp ++ [dd]
  where optional_string x = fmap (fromMaybe "") (optional (M.string' x))

test_p_exponent = M.parse (p_exponent <* M.eof) "" "E-9"
```

and when i run it i get:
```
λ> test_p_exponent 
P: Exponent ex
P: Exponent eplus pp
P: Exponent dd
Left (ParseError {errorPos = SourcePos {sourceName = "", sourceLine = Pos 1, sourceColumn = Pos 2} :| [], errorUnexpected = fromList [Tokens ('-' :| "")], errorExpected = fromList [Tokens ('+' :| ""),Label ('d' :| "igit")], errorCustom = fromList []})
it :: Either (M.ParseError Char M.Dec) String
```

The surprising thing to me is that expected is `'+'`, but the plus sign should be optional so why is it expected? I would expect the expected thing to be a digit and then get a `ParseError` that indicates that `'-'` does not match the parser `digitChar`

Looking from the debug output the `p_exponent` parser continues after the optional plus sign, because i see in the trace `Exponent dd`.

**Comment by mrkkrp** [comment]
The parse error says that `-` cannot be there, but `+` or a digit **can**. The the reason why `+` is included, is because it's a valid possibliity. IOW, the error message shows all opions how the input could be successfully completed, not only "required subset".

**Comment by flip111** [comment]
Ah ok thank you for your explanation, you mind if i open PR's for developer tips ?

**Comment by mrkkrp** [comment]
What sort of tips these would be?

**Comment by flip111** [comment]
Like the one you just gave me

**Comment by mrkkrp** [comment]
Hm, I'm not  sure where to put them, and I would be against putting them into Haddocks, because it's not really worth it and it would make the docs too "talkative", at least we're talking about this particular piece of info.

**Comment by flip111** [comment]
We could open a wiki on github https://github.com/mrkkrp/megaparsec/wiki i also would like to add some stuff about https://github.com/mrkkrp/megaparsec/issues/159

**Comment by mrkkrp** [comment]
Can you open a PR against https://github.com/mrkkrp/megaparsec-site instead? You can create a new tutorial called “Misc tips” or something and collect everything there. If you do, please use 4th level of difficulty for this (not because it's difficult, but because it's optional info that should go later in the list).

I'm also working on a new tutorial called “First steps with Megaparsec” as per #168, but I think this piece of info is unlikely to get there.

I don't like the idea of Wikies because it's hard to review what is being added/edited, as opposed to making all changes via PRs.
