### ISSUE TITLE
Can I do some processing with Stream?

### ISSUE THREAD

**Issue by jeiea** [mrkkrp/megaparsec#185]
I tried making C preprocessor with megaparsec and there's some [phase](https://gcc.gnu.org/onlinedocs/cpp/Initial-processing.html#Initial-processing) to processing.
In this case, we always need to check for whitespace substitution. I thought most preferred method is to make `Stream` instance, but due to the `uncons` and `updatePos` separation, it can't be done directly.

Can't those two function be merged? Or is there another desirable way?

I thought the ideal way to treat this problem is to make parser possible to be composed and to track source position. But it sounds like a fantasy even to myself.

**Comment by mrkkrp** [comment]
Could you please rephrase the question more clearly? Right now, I see you have some mental model of the problem, but I do not share it, so I can't even tell why you want `uncons` and `updatePos` combined.

> I thought the ideal way to treat this problem is to make parser possible to be composed and to track source position. But it sounds like a fantasy even to myself.

*Parser possible to be composed*? Well, parsers are certainly can be composed right now, and we do track the source position.

First of all, you should state clearly whether you have issues with parsing the definitions themselves or using the parsed definitions, etc.

I do answer questions here, but I can't do telepathy (yet)! :-D

**Comment by jeiea** [comment]
I'm thinking to use `Stream` to remove preprocessor's comment because it is always needed to be checked.
Maybe it'll be like
```haskell
class Ord (Token s) => Stream s where
  type Token s :: *
  progress       -- I don't know what's Proxy's role well.
    :: Pos       -- Tab width
    -> SourcePos -- Current position
    -> s         -- Current string. uncons's s.
    -> (Token s, s, SourcePos, SourcePos) -- The result of uncons and updatePos.
```
Then I can skip multiple tokens in `Stream` implementation.

And what I mean from 'composed' is to compose independent parsers in parallel maybe needless in most cases.
If I have a 'Initial processing' parser of the above link and a really necessary parser, then is already there any way to use the latter with the former's result with tracking the former's source position?

**Comment by mrkkrp** [comment]
I don't have a solution that would keep the positions in sync. The easiest thing is to do two passess, one for picking up the macro definitions and perhaps applying them, and second pass on the pre-processed text. But they will easily go out-of-sync.

Maybe using an external tokenizer and manipulating positions assigned to tokens could help?

**Comment by mrkkrp** [comment]
I can say for sure though that `Stream` is not the right place to try to do any pre-processing. It's a very simple interface allowing to consume streams to toknes one at a time, and that's about it I think.

**Comment by jeiea** [comment]
> Maybe using an external tokenizer and manipulating positions assigned to tokens could help?

If that gives more free to `Stream` part, I think it will be fine to my case.
I'm not sure too that it can be much help to general case. I guess it would be help to the case of variable length token.
Maybe my case is too special.

**Comment by mrkkrp** [comment]
> Then are you willing to make any change? Should I close this issue?

It's not clear what I can do without breaking compatibility, etc.

**Comment by mrkkrp** [comment]
Closing for now.
