### ISSUE TITLE
Confusing docs for try, string and tokens.

### ISSUE THREAD

**Issue by thomwiggers** [mrkkrp/megaparsec#186]
The documentation for `try` explains that you can use it to resolve problems with `string` parsers:

> try fixes this behavior and allows backtracking to work:
```
parseTest (try (string "let") <|> string "lexical") "lexical"
"lexical"
```

But in `tokens`: 

```
>>> parseTest (string "abc") "abd"
1:1:
unexpected "abd"
expecting "abc"
```
> This means, in particular, that it's no longer necessary to use try with tokens-based parsers, such as string and string'. This feature does not affect performance in any way.

**Comment by mrkkrp** [comment]
Documentation for `try` also has this:

> Please note that as of Megaparsec 4.4.0, string backtracks automatically (see tokens), so it does not need try. However, the examples above demonstrate the idea behind try so well that it was decided to keep them.

**Comment by thomwiggers** [comment]
Hm right. Is there no easy way to adapt the example to something that doesn't backtrack? That would probably eliminate any confusion.

**Comment by mrkkrp** [comment]
Probably there is. I'll take a look later this week.

**Comment by mrkkrp** [comment]
Just re-read the docs, and I still think we should keep the present example. Alternative example would by parsing two characters in a row in each branch but it's verbose and not so clear. Maybe we should make the note at the end more visible and explain better when you still need to use `try`?

**Comment by thomwiggers** [comment]
```
> parseTest ((symbol "a" *> symbol "d") <|> (symbol "a" *> symbol "c")) "ac"
1:2:
unexpected 'c'
expecting 'd'
```

Is perhaps slightly more contrieved but it does save the confusion. It also helps illustrate that it's actually often these kinds of combinations that you need `try`. But the emphasis probably also already helps.
