### ISSUE TITLE
eof runs my CPU considerably

### ISSUE THREAD

**Issue by aiya000** [mrkkrp/megaparsec#195]
Hi, thanks for giving megaparsec ! :smile:

I'm wrting S expression parser.  
eof function hanged up my CPU... (code in [here](https://github.com/aiya000/eliningen/blob/667be285e59cd5ba2dbbd5766644a1ef061ebfd8/src/Elin/Parser.hs)).

If I remove `endOfParse`, my CPU doesn't hang up :cry:  
(but parsing is failed)

Am I writing wrong code, or Does eof has bug ?

**Comment by mrkkrp** [comment]
There is no bug in `eof`. You're a victim of left-recursion. What happens is that `eof` matches repeatedly, parser state is not updated (nothing is consumed) and you run again and again.

If you want help with debugging your code, you should state clearly which exactly function you run, what input you provide.

**Comment by aiya000** [comment]
This is difficult and interesting...

I inserted two debug point.

- [L85](https://github.com/aiya000/eliningen/blob/d8dd11670fc5931bff6e0b3a73b1c28c3c8b46f7/src/Elin/Parser.hs#L85)
- [L105](https://github.com/aiya000/eliningen/blob/d8dd11670fc5931bff6e0b3a73b1c28c3c8b46f7/src/Elin/Parser.hs#L105)

The result is

```
listParser
eof

(also progress into infinite recurse (lol))
```

I understood that left recursive prints 👇

```
eof
eof
eof
eof
eof
eof
eof
eof
.
.
. (only eof)
```

Is this wrong ?

**Comment by aiya000** [comment]
@mrkkrp 

Sorry, I understood it !

Thanks for teaching it to me 👍
