### ISSUE TITLE
indentBlock error: indent tokens not parsed

### ISSUE THREAD

**Issue by nd2s** [mrkkrp/megaparsec#197]
I'm using `indentBlock` quite a lot and it usually works like a charm, but here I got some code that just doesn't want to work.

Minimal example:

```
module Test where

import           Control.Applicative
import           Control.Monad
import           Text.Megaparsec
import qualified Text.Megaparsec.Lexer as L
import           Text.Megaparsec.String

inp :: String
inp = "header\n\tfirstline\n\tsecondline\n\t\n"

test :: IO ()
test = parseTest block inp


block :: Parser [String]
block = do
    h <- blockHead
    ls <- L.indentBlock spaceC $
        return $ L.IndentSome Nothing return blockLine
    return $ h : ls

blockLine :: Parser String
blockLine = some letterChar

blockHead :: Parser String
blockHead = string "header"

spaceC :: Parser ()
spaceC = L.space (void spaceChar) empty empty
```

Calling `test` gives me:

```
2:9:
unexpected 'f'
expecting end of line
```

I can get this minimal example working if i parse the head line "inside" the `indentBlock` call like so:

```
block :: Parser [String]                                                        
block = L.indentBlock spaceC $ do                                               
    h <- blockHead                                                              
    return $ L.IndentSome Nothing (return . (h:)) blockLine
```

But I would need to parse the header line outside so I can decided what type of block to parse (different `IndentOpt` types; I don't want to use some wrapper type just for the `indentBlock` call). Is there a way of doing that? I am not sure what exactly is happening here.

**Comment by mrkkrp** [comment]
Normally `identBlock` handles header parsing itself, you just tell it how to parse hearder (as in the second example you show, that's the correct usage).

I think if you want to have different `a` and `b` in `IndentOpt m a b` depending on what you parsed as header, then you'll need `Either` or some custom sum type for that.

**Comment by nd2s** [comment]
Ok, then I'll use a sum type instead of trying to force something on it. Thanks for the answer!
