### ISSUE TITLE
Implement optional displaying of releavant region of input in error messages

### ISSUE THREAD

**Issue by mrkkrp** [mrkkrp/megaparsec#205]
For version 6, I want to have something like this:

```
my-file.txt:8:6:

x = 1a
     ^

unexpected 'a'
expecting newline or the rest of integer
```

Regarding implementation, I think we are not going to store input regions for this, so no changes to the parsing process should be necessary (as we don't want to make things slower, in fact version 6 is about making things faster). The most obvious thing (and robust) is to traverse original input updating position till we find the position from `ParseError`. Remembering where the most recent line begins will allow us to extract just the relevant line of input and display it.

I'm not sure how to do it better without making the feature fragile. It seems that we can't use total number of processed tokens to figure out where `ParseError` happened, because in some cases, for example when using `region` to overwrite error position, total number of processed tokens would be out-of-sync.

This feature should be optional.

**Comment by mrkkrp** [comment]
@recursion-ninja, any progress with this one?

**Comment by recursion-ninja** [comment]
@mrkkrp my weekend got away from me, so no there's no substantial progress. However, I have given it a fair bit of thought.

I'm not exactly sure how to implement it on an arbitrary stream of tokens. We would need a way to determine the relevant scope for a given parse error. It will be much easier to implement if constrained on `Token s ~ Char` so we can determine the beginning and end of a given line. 

There might be a way to generalize this for an arbitrary stream of tokens by passing in a "scoping" function as a parameter which signals when a new "scope" for a parse error in the stream has been consumed. For streams where `Token s ~ Char` this function would signal a new "scope" (line) has been entered when a `'\n'` or a `\r\n` has been consumed.

**Comment by mrkkrp** [comment]
Well, let's see. We are going to need functions from the [`Text.Megaparsec.Stream`](https://github.com/mrkkrp/megaparsec/blob/master/Text/Megaparsec/Stream.hs) module. Note that they work for any `Stream` and to consume some input, it must be an instance of `Stream`, so the methods of the class seem to be the right tool.

I think to print the relevant line, we are going to take the whole input as an argument. Since the feature should be optional, maybe it's best to have a separate function for this (similar to `parseErrorPretty`):

```haskell
parseErrorPretty'
  :: ( Ord (Token s)
     , ShowToken (Token s)
     , ShowErrorComponent e
     , Stream s )
  => s
  -> ParseError t e
  -> String
parseErrorPretty' = undefined
```

We could apply `take1_ :: s -> Maybe (Token s, s)` to `s` till we arrive at the right source position remembering where we last saw `'\n'`. Then it should be rather trivial to extract the line of interest and render it with this `^` thing under the offending position. Also we need to handle the case when the position cannot be found, we can't find exactly that position...

It looks like if we're comparing with `'\n'`, we are limiting ourselves to `Token s ~ Char`, but I think the trick I used with [`defaultAdvance1`](https://github.com/mrkkrp/megaparsec/blob/master/Text/Megaparsec/Stream.hs#L271-L285) can be attempted here again to allow the same algorithm to work with `Token s ~ Word8` (we are trying to support `Word8` out-of-the-box, so users can work with `ByteString`s just as easily). In that case maybe the constraint will be something like `Enum (Token s)`.

People who work with custom streams will need custom solution I guess, but that's OK.

Finally, traversing tokens one by one is not going to be very fast. I wonder if binary search can be used with `takeN_` and `advanceN` functions to grab part of input and advance position, then compare it with position from the parse error. `chunkLength $ takeWhile Nothing (const True)` can be used to estimate the length of the whole stream, etc.

Won't be active next couple of weeks because I'll be travelling a bit, so you have plenty of time to play with this :-)
