### ISSUE TITLE
Extend Stream type class to support extraction of blocks of stream

### ISSUE THREAD

**Issue by mrkkrp** [mrkkrp/megaparsec#206]
This is the main feature of version 6, and the main breaking change. I need to think about this more, but so far the idea is to equip `Stream` type class with a new associated type which would describe a “chunk” of stream:

```haskell
class Ord (Token s) => Stream s where

  type Token s :: *
  type Tokens s :: * -- NEW

  uncons :: s -> Maybe (Token s, s)
  streamTake :: Word -> s -> (Tokens s, s) -- NEW

  updatePos :: Proxy s -> Pos -> SourcePos -> Token s -> (SourcePos, SourcePos)
```

This will allow to take N tokens and get them packed in this `Tokens s` type, which will be `ByteString` for `ByteString`, `Text` for `Text`, `String` for `String`, but may be just `[Token s]` as well for custom `Stream` things.

Now with this feature we can grab part of input in its native form without repacking it to `String`. This will be used in `string`, `string'`, `match`, etc. Everywhere where we used `String` unconditionally but type of stream would suggest a different representation.

This will also make things faster. Thanks to semantics of `tokens`, we can just grab the same number of tokens as we have to match and then compare those “chunks”. If they do not match, we report an error, otherwise we advance position and return result. This should be much faster than taking tokens one by one, comparing them with other tokens from a linked list, then packing then into a linked list.

**Comment by recursion-ninja** [comment]
I made an initial attempt at implementing this [here](https://github.com/recursion-ninja/megaparsec/tree/stream-tokens).

It seems that the `MonadParsec` type-class function `tokens` should probably return the proposed new type `Tokens s` to make the parser run efficiently. Does this change to `MonadParsec` seem correct to you @mrkkrp ?

I ran into trouble modifying `pTokens` in the `Prim.hs` file because I don't have a working knowledge of the parser state updates. I'll try and work through it, but I'm having trouble discerning what some of the short variable names represent.

**Comment by mrkkrp** [comment]
Thanks for your efforts, but I wanted to work on this myself in a few days, when my current contract ends (I'll have free time yay!). There is a plan how to arrive at the version 6, and it includes many stages. This one is not the first, we need to merge a few other PRs before we get to this feature. Probably I should publish a roadmap or somethnig :-)

**Comment by recursion-ninja** [comment]
Yes, the more I tinkered with the proposed 6.0 changes, the more involved I realized the task is. I'll leave it in your capable hands. 

If you think of a more "self contained" contribution in the future you'd like help on, don't hesitate to shout out for help by tagging @recursion-ninja in the issue.

**Comment by mrkkrp** [comment]
Thank you, much appreciated!
