### ISSUE TITLE
Add something like a findFirst combinator?

### ISSUE THREAD

**Issue by siers** [mrkkrp/megaparsec#214]
I thought about it and wrote my own(`findFirst p = p <|> (anyChar *> findFirst p)`), then later also thought maybe I'd encounter via googling, which I did: https://stackoverflow.com/questions/29549435/parsec-how-to-find-matches-within-a-string

Maybe it would be worthwhile to add this to the lib? (or is it there and I couldn't find it?)

**Comment by mrkkrp** [comment]
May be written as `void (manyTill anyChar (lookAhead p)) *> p` but this will build the resulting list only to discard it. Also see this recent question: #212. I think maybe we could add more efficient helpers. May be call them `skipManyTill`, `skipSomeTill`?

Just a guess, I think this will be faster:

```haskell
skipManyTill :: Alternative m => m a -> m end -> m end
skipManyTill p end = go
  where
    go = end <|> (p *> go)
{-# INLINE skipManyTill #-}
```

**Comment by recursion-ninja** [comment]
I also ended up writing something similar, though I don't think it's the most efficient:

```
-- |                                                                                                                    
-- @anythingTill end@ consumes zero or more characters until @end@ is matched,                                          
-- leaving @end@ in the stream and returning the prefix before the match.                                                                                         
anythingTill :: MonadParsec e s m => m a -> m [Token s]                                                                 
anythingTill c = do                                                                                                     
    ahead <- optional . try $ lookAhead c                                                                               
    case ahead of                                                                                                       
      Just _  -> pure []                                                                                                
      Nothing -> somethingTill c                                                                                        
                                                                                                                        
                                                                                                                        
-- |                                                                                                                    
-- @somethingTill end@ consumes one or more characters until @end@ is matched,                                          
-- leaving @end@ in the stream and returning the prefix before the match.                                                                                         
somethingTill :: MonadParsec e s m => m a -> m [Token s]                                                                
somethingTill c = do                                                                                                    
    _ <- notFollowedBy c                                                                                                
    (:) <$> anyToken <*> anythingTill c 


anyToken :: MonadParsec e s m => m (Token s)                                                                            
anyToken = token Right Nothing
```

I had the combinators return the "prefix" before the desired thing was matched.

Adding something like this to a module would be nice. Whether or not it returns the prefix or just discards the prefix and returns the desired match, both would be welcome. I think there is a general need for this sort of functionality in most non-trivial parsers.

**Comment by mrkkrp** [comment]
Yeah, this will be added, not in Megaparsec itself though, but in a package `parser-combinators` which will define all the stuff for any instances of `Applicative` and `Alternative`. Megaparsec 6 will depend on that package then and re-export stuff from there.

> Whether or not it returns the prefix or just discards the prefix and returns the desired match, both would be welcome.

For grabbing prefix we already have `manyTill` and `someTill`.

Chances are in Megaparsec 6 there will be very fast alternatives to these combinators, like `takeWhile`:

```haskell
takeWhile :: MonadPasec e s m => (Token s -> Bool) -> m (Tokens s)
```

This will essentially call `takeWhile` for underlying steam, which should be a lot faster for things like `Text` and `ByteString`.

**Comment by mrkkrp** [comment]
Added as `skipManyTill` and `skipSomeTill` in [`parser-combinators`](https://hackage.haskell.org/package/parser-combinators). Megaparsec 6 will depend on that package, but you can use it directly even now.
