### ISSUE TITLE
Question about the expression parser

### ISSUE THREAD

**Issue by ozgurakgun** [mrkkrp/megaparsec#218]
I'd like to use the expression parser to parse a language of arithmetics. I am having trouble setting up unary minus and power though. I will use these two operators and multiplication to explain my problem.

First of all, the expected behaviour.

```
"-3*2" --> (-3) * 2
"3*-2" --> 3 * (-2)
"-3^2" --> -(3 ^ 2)
"3^-2" --> 3 ^ (-2)
```

This can feel a bit weird, but if you check your favourite calculator, you'll see that this is expected behaviour. So `-` binds stronger than `*`, and stronger than `^` only when it is the second operand... This is quite a bizarre requirement, but keep in mind that there is no other sensible parsing for when the second operand has a `-` in it.

Looking at the third example, `^` must bind stronger than `-`.  But if I specify this, the fourth one does not parse.

[Here is a gist](https://gist.github.com/ozgurakgun/223f7a7b5ebc37a11c3d893210a46d06) with a bit of code to reproduce.

I hope this is clear.

**Comment by mrkkrp** [comment]
You need first to rearrange precedence:

```haskell
table = [ [ InfixR (char '^' >> return Pow) ]
        , [ InfixL (char '*' >> return Mult) ]
        , [ Prefix (char '-' >> return Negate) ]
        ]
```

Then you need to allow to handle that minus sign as part of the term. One solution should be to alter `term` definition like this:

```haskell
sc :: Parsec Dec String ()
sc = skipMany spaceChar

term = Val <$> signed sc integer <?> "term"
```

Now it works for me:

```
λ> parseTest (expr <* eof) "-3*2"
(-(3) * 2)
λ> parseTest (expr <* eof) "3*-2"
(3 * -(2))
λ> parseTest (expr <* eof) "-3^2"
-((3 ^ 2))
λ> parseTest (expr <* eof) "3^-2"
(3 ^ -2)

```

You could also make `term` wrap things with `Negate` if it's preferable.

**Comment by ozgurakgun** [comment]
Oh, interesting. So you end up parsing example-3 with the expression parser, and example-4 with the term parser. Thanks for the quick reply!

I thought there would be a way of parsing both 3&4 with the expression parser when `^` was specified to bind tighter than unary minus (since there is no other valid parsing of 3^-2).

**Comment by mrkkrp** [comment]
You would need to write a custom helper for expression parsing in that case. Switching precedence like this is not common, our existing helper is certainly was not designed for this. The method I propose should work fine though.

**Comment by ozgurakgun** [comment]
Indeed, your method does work. Thanks for providing it!

> Switching precedence like this is not common

I agree that this is bizarre, but evidently, it is not uncommon. As an example, Google's calculator parses them this way too. See [-3^2](https://www.google.co.uk/search?q=-3^2) and [3^-2](https://www.google.co.uk/search?q=3^-2).

**Comment by mrkkrp** [comment]
Since the question seems to be answered, I'm closing this.
