### ISSUE TITLE
Make numeric parsers polymorphic in returned type

### ISSUE THREAD

**Issue by mrkkrp** [mrkkrp/megaparsec#219]
Attoparsec does this with `decimal`. Can be handy.

**Comment by mrkkrp** [comment]
Also, it turns out that numeric parers are often bottleneck in many parsers, so we should make them really fast in version 6 if we want to compete with Attoparsec.

**Comment by recursion-ninja** [comment]
I've noticed that all the `nump` and `scientific` parsers call `read` internally. It's my understanding that `read` will "re-parse" the valid string we have already parsed and then convert the string to the appropriate value. Do you think that manual construction of the `Integer` and `Scientific` values would be more efficient than calling `read`?

I'm willing to explore this. Let me know your thoughts on the matter.

**Comment by mrkkrp** [comment]
Yes, I actually just started on this. I benchmarked and profiled some parsers implemented in Attoparsec and Megaparsec here:

https://github.com/mrkkrp/parsers-bench

And found that parsers like `decimal` can be a nasty bottleneck, so the idea is to optimize all numeric parsers heavily. Probably there will be no `read` at all, rather something like what Attoparsec does. I'm also writing a blog post about latest changes including this one.

> I'm willing to explore this. Let me know your thoughts on the matter.

Looks like I'm again grabbing all the work for myself :-| If you want to work on something, I think #205 is a good candidate that is not related to what I'm doing right now. You can go ahead and open a PR for it if you want and we'll take it from there.

**Comment by recursion-ninja** [comment]
I'll look into #205.
