### ISSUE TITLE
Bug in 'manyTill'

### ISSUE THREAD

**Issue by mrkkrp** [mrkkrp/megaparsec#23]
While writing tests for `Text.Megaparsec.Combinator` I ran into the following bug:

```haskell
λ> parseTest (manyTill letterChar (char 'c')) "ab"
parse error at line 1, column 1:
unexpected 'a'
expecting 'c'
```

this error message is wrong. It should be:

```haskell
parse error at line 1, column 3:
unexpected end of input
expecting 'c' or letter
```

It's worth noticing that Parsec doesn't suffer from this:

```haskell
λ> parseTest (manyTill letter (char 'c')) "ab"
parse error at (line 1, column 3):
unexpected end of input
expecting "c" or letter
```

Current implementation however is functionally the same as Parsec's:

```haskell
-- Megaparsec

manyTill :: Stream s m t =>
            ParsecT s u m a -> ParsecT s u m end -> ParsecT s u m [a]
manyTill p end = (end *> return []) <|> someTill p end

someTill :: Stream s m t =>
            ParsecT s u m a -> ParsecT s u m end -> ParsecT s u m [a]
someTill p end = (:) <$> p <*> manyTill p end

-- Parsec

manyTill :: (Stream s m t) => ParsecT s u m a -> ParsecT s u m end -> ParsecT s u m [a]
manyTill p end      = scan
                    where
                      scan  = do{ end; return [] }
                            <|>
                              do{ x <- p; xs <- scan; return (x:xs) }
```

I've checked it, changing Megaparsec's `manyTill` to Parsec's `manyTill` doesn't solve the problem. This means there a bug on lower level.

While it is sad that `Text.Megaparsec.Prim` still has bugs, I'm glad they at least don't get through our tests.

I'll report here cause of the issue once I've that fixed.

**Comment by tulcod** [comment]
This is "fixed" by reverting `mergeError` to the original Parsec implementation:

```haskell
mergeError :: ParseError -> ParseError -> ParseError
mergeError e1@(ParseError pos1 msgs1) e2@(ParseError pos2 msgs2)
    -- prefer meaningful errors
    | null msgs2 && not (null msgs1) = e1
    | null msgs1 && not (null msgs2) = e2
    | otherwise
    = case pos1 `compare` pos2 of
        -- select the longest match
        EQ -> ParseError pos1 (msgs1 ++ msgs2)
        GT -> e1
        LT -> e2
```

Producing:
```
> parseTest (manyTill letterChar (char 'c')) "ab"
parse error at line 1, column 3:
unexpected end of input
expecting letter
end of input or 'c'
```
although I'm not sure why it expects end of input: that's what it got.

**Comment by mrkkrp** [comment]
@tulcod, Yes, I've performed reorganization of error messages, how they work in general. Parsec used very hairy stuff. You can read about it in #14 and #19. New system uses clear principles of error processing (see #14) and also there is hint system to handle other aspect of error message construction (see #19). Original Parsec used fair bit of magic, empty error message string represented "end of input" message, etc. Now everything is explicit and different parts of system interact in clearly defined way. When I just made the changes there were many weird bugs, but now most of them are fixed.

Knowing this you probably understand my desire to finish what I started and fix this bug without reverting to old hairy system. I suspect it's about an argument to some continuation in one of the primitive combinators. I've fixed a coupe of such bugs recently. For example: d45c2c0 and fc5abbc. I'm sure I can handle this too.

**Comment by mrkkrp** [comment]
This is because we currently prefer earlier error messages in `mergeError`. When I chose this behavior, source code of `Text.Megaparsec.Prim` was not that clear as it is now. Currently
`mergeError` is only used in `parserPlus`, or you maybe more familiar with different spelling of this function — `(<|>)`. This implements alternative.

Since `mergeError` is only used to join two error messages, one occurred in `n` (if we consider `n <|> p`) with different message produced in `p`. Difference is visible only when `p` moves in input stream, i.e. consumes input, so message produced by `n` becomes ealier. `n <|> p`
chooses earlier error [here](https://github.com/mrkkrp/megaparsec/blob/master/Text/Megaparsec/Prim.hs#L360):

```haskell
parserPlus :: ParsecT s u m a -> ParsecT s u m a -> ParsecT s u m a
{-# INLINE parserPlus #-}
parserPlus m n = ParsecT $ \s cok cerr eok eerr ->
  let meerr err =
        let ncerr err' = cerr (mergeError err' err) -- ← here it happens
            neok x s' hs = eok x s' (hs <> toHints err)
            neerr err' = eerr (mergeError err' err)
        in unParser n s cok ncerr neok neerr
  in unParser m s cok cerr eok meerr
```

Solution: reconsider logic used when two error messages are merged. Since it's only used in “alternatives”, we should prefer latest error message instead. Change implementation of `mergeError` in `Text.Megaparsec.Error`, add detailed description why this logic should be used, so future readers of the code can clearly understand purpose of `mergeError`. Possibly correct
tests for this function in `tests/Error.hs`.
