### ISSUE TITLE
Using Megaparsec.Lexer on non-Char?

### ISSUE THREAD

**Issue by doppioandante** [mrkkrp/megaparsec#235]
Hello, I have an already existing lexer generated from alex which output [Token], is there any way to parse them?
Should I use use `type Parser = Parsec Dec [Token]` ?
The doc mentions:
By default this module is set up to parse character data. If you'd like to parse the result of your own tokenizer you should start with the following imports:

import Text.Megaparsec.Prim
import Text.Megaparsec.Combinator

Then you can implement your own version of satisfy on top of the token primitive, etc.

But it isn't really clear to me.. should I also have [Token] be an instance of Stream Token?
Will I be able to use functions from Text.Megaparsec.Lexer on [Token] instead of String?

**Comment by mrkkrp** [comment]
I'm sort of away from civilization for a week. I'll answer later. In short, yes you need the instance and you can't use the lexer module because it's for character streams.

**Comment by mrkkrp** [comment]
Yes, start with `type Parser = Parsec Dec [Token]`. Then you'll need to write primitives you need. For `Char` streams there is already `Text.Megaparsec.Char`, but we can't provide anything for your custom token type. You build stuff on top of primitives like `token` and `tokens`, etc. Lexer needs to match on things like white space, and so it can only work on streams with token types `Char`.

**Comment by mrkkrp** [comment]
Closing if you don't mind.
