### ISSUE TITLE
How to add custom message to errors in megaparsec-6

### ISSUE THREAD

**Issue by hpdeifel** [mrkkrp/megaparsec#238]
Hi,

A use case I had for custom error messages in parsec and megaparsec-5 was to add a custom string to the end of an error message to provide additional context or an explanation while still showing expected and unexpected tokens.

It's not obvious to me how to replicate this with megaparsec-6, as I seem to have the choice of either a custom message *or* unexpected and expected tokens. I could of course add those to my custom error type, but I wanted to make sure that I didn't miss an easier way, first.

**Comment by mrkkrp** [comment]
Here is a complete example with Megaparsec 6:

```haskell
module Main (main) where

import Data.Set (Set)
import Data.Void
import Text.Megaparsec
import Text.Megaparsec.Char
import qualified Data.Set as E

data MyWrapper = MyWrapper
    (Maybe (ErrorItem Char)) -- unexpected part
    (Set (ErrorItem Char))   -- expected part
    String                   -- custom data, e.g. a message
  deriving (Eq, Ord, Show)

instance ShowErrorComponent MyWrapper where
  showErrorComponent (MyWrapper us es msg) =
    parseErrorTextPretty (TrivialError undefined us es :: ParseError Char Void)
    -- parseErrorTextPretty does not look at position
    ++ msg

type Parser = Parsec MyWrapper String

myParser :: Parser String
myParser = many (char 'a') <* eof

addContext :: String -> Parser a -> Parser a
addContext msg = region f
  where
    f (TrivialError pos us es) =
      FancyError pos (E.singleton $ ErrorCustom (MyWrapper us es msg))
    f err = err -- other options are possible, but this is an easy one

main :: IO ()
main = parseTest' (addContext "C'est la vie!" myParser) "aaabc"
```

Try it:

```
Hours of hacking await!
λ> :main
1:4:
  |
1 | aaabc
  |    ^
unexpected 'b'
expecting 'a' or end of input
C'est la vie!
λ>
```

**Comment by mrkkrp** [comment]
Basically if you want to modify a trivial error, you need to wrap. This is a bit harder, but overall I think the separation adds a bit more discipline and safety.

**Comment by hpdeifel** [comment]
Alright, thank you for the answer and you work on megaparsec!

**Comment by mrkkrp** [comment]
If the question in answered, can we close the issue?

**Comment by hpdeifel** [comment]
Yes, sure
