### ISSUE TITLE
Removal of several parsers from 'Text.Megaparsec.Combinator'

### ISSUE THREAD

**Issue by mrkkrp** [mrkkrp/megaparsec#24]
OK, this is an important announcement. I'm considering the possibility of
removal of the following parsers from `Text.Megaparsec.Combinator`:

* `chainl`
* `chainl1`
* `chainr`
* `chainr1`
* `sepEndBy`
* `sepEndBy1`

Chaining functions are useless and misleading. What they do is actually
better performed by `Text.Megaparsec.Expr`, it's obvious from examples in
their descriptions. I guess they were written before the module existed, so
the author of Parsec tried to provide more functionality this way.

User who encounters these combinators will think that this is how
expressions should be parsed, so he may start writing his code using these
tools instead of `Text.Megaparsec.Expr`.

`sepEndBy` and its variant `sepEndBy1` are not that useful too. These things
can be easily implemented in terms of existing combinators (however the
author of Parsec preferred to re-implement the whole thing, strange…) if
needed (although I think it's not that often needed):

```haskell
-- | @sepEndBy p sep@ parses /zero/ or more occurrences of @p@,
-- separated and optionally ended by @sep@. Returns a list of values
-- returned by @p@.

sepEndBy p sep = sepBy p sep <* optional sep

-- | @sepEndBy1 p sep@ parses /one/ or more occurrences of @p@,
-- separated and optionally ended by @sep@. Returns a list of values
-- returned by @p@.

sepEndBy1 p sep = sepBy1 p sep <* optional sep
```

Note that it's not only easy to write the combinators using the existing
ones, but `sepBy p sep <* optional sep` is also clearer than `sepEndBy`. In
fact I had to read description of that function to understand what it really
does.

----

Please argue and provide your arguments if you want to save the
combinators.

**Comment by mrkkrp** [comment]
Frankly I don't see much use in `skipMany` and `skipSome` too, but I'm not sure what to do with them.

**Comment by tulcod** [comment]
I know that keeping API compatibility is not your top priority, but do you have any specific reason to remove them? Keeping them will make switching from Parsec to Megaparsec easier.

I agree with the points you make (indeed, the `chain*` and `sepEnd*` combinators seem to quite simply be a relic of the pre-`Expr` API design, although I'm not quite convinced about `skipMany` and `skipSome`, but then again I do agree that these are just as easily implemented manually), but - as much as we want to provide the sanest API possible - I think that *at this stage* it is important to keep some (conceptual) compatibility with Parsec.

Would you be satisfied if these were all marked deprecated instead?

**Comment by mrkkrp** [comment]
@tulcod, I think about Megaparsec as new library (that has strong connections with Parsec, but mainly to the point when all what Parsec can do can be easily done with Megaparsec too, not more, well and just because Megaparsec is a fork of Parsec anyway), so deprecation is a wrong term here. Megaparsec is already quite different, and this is our chance to clean up all the details. I don't think availability of `sepEndBy` will make any difference for those who will want to switch.

After all Parsec will be used after Megaparsec release, of course. People who need to work with legacy code won't switch. Have you noticed that Megaparsec requires at least GHC 7.10?

If I wanted to make switching from Parsec to Megaparsec easier, I wouldn't do many good things.

And less functions is actually good, it's easier to maintain and test (for maintainers) and it's clearer what to use for user.

**Comment by mrkkrp** [comment]
@tulcod, What I can do for those who will want to switch, is write a tutorial explaining important details. I don't think switching will take much effort, users won't need to think (that's difficult part!), so it will be mainly mechanical (renaming, flipping argument order).

**Comment by mrkkrp** [comment]
@tulcod, I've decided to keep `skipMany` and `skipSome` though.

**Comment by tulcod** [comment]
I'm not sure what you're "cleaning up" here, since there is no real mess to speak of. Okay, these functions are not strictly necessary, but is a building with too much support "dirty"? If there would be something broken about them, I would support their removal 100%, especially now, but as far as we know they aren't.

I agree, Megaparsec is already quite different. If you want Megaparsec to be adopted by many projects, then you should not make it too different. Removing too many functions will just confuse people who are used to Parsec. (People say that this is why C++, as a "successor", but really a fork, of C, became popular. Although I agree that that is the other extreme.)

Marking the functions "deprecated" expresses that you think their interface or implementation is dirty, and that they should be avoided, but that if people really can't be bothered to understand your reasoning, they're welcome to use them. But "disclaimer applies". This, I think, expresses what you're trying to address.

I think a tutorial would be extremely helpful.

**Comment by mrkkrp** [comment]
@tulcod, To be honest I don't believe many projects that already use Parsec will switch. The logic "it doesn't worth the trouble, Parsec works as is" will be prevalent I think. When I started the project I wanted to see if I can create good parser combinator library taking Parsec as starting point. So I think users of Megaparsec are mainly new projects, but these things are difficult to predict.

All what you're saying is reasonable and I'm actually glad you express different opinion. I need to think about this for a while.

**Comment by mrkkrp** [comment]
@tulcod, OK I won't remove them… right now. Instead I will put them in separate section in source file with label “deprecated”. Every function from this list will be marked as deprecated in documentation and examples that show usage of chaining functions for expression parsing will be
removed. Implementations of the functions will be mostly saved “as is”, but no tests will be written for these functions. You can omit benchmarks for them.

In text major release `4.1.0.0` or `4.2.0.0` we will eliminate them. By the time, people will have switched already, so they probably will have to rewrite some pieces of code or stick with older versions of Megaparsec (although it's not worth it).

**Comment by mrkkrp** [comment]
I remember seeing a label “DEPRECATED” in Haddock-generated documentation. I cannot find what to use to get this markup now. Haddock docs are silent about this sort of thing. [Search query “haddock deprecated”](https://duckduckgo.com/html?q=haddock+deprecated) returns results varying from blogs about fishing to Wikipedia article “Religion and Schizophrenia”. This is crazy.

@tulcod, Do you know how to mark function deprecated in Haddock?

**Comment by tulcod** [comment]
I'm fairly sure it understands the [`DEPRECATED` pragma](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/pragmas.html).

**Comment by mrkkrp** [comment]
@tulcod, I didn't know it's implemented on GHC level. Thank you!

**Comment by mrkkrp** [comment]
I think we should also swap `count` and `count'` in Megaparsec, since Megaparsec's `count'` does the same thing as Parsec's `count`. Let's make switching a little bit easier for Parsec users.

**Comment by bartavelle** [comment]
Just realized there already was an issue discussing this ... how do I solve [this problem](http://stackoverflow.com/questions/10475337/parsec-expr-repeated-prefix-postfix-operator-not-supported) with megaparsec without resorting to `chainl1` ?

**Comment by bartavelle** [comment]
> (however the author of Parsec preferred to re-implement the whole thing, strange…)

It's not strange, the implementation of `sepBy1` can't work with `sepEndBy`:

    sepBy1 p sep = (:) <$> p <*> many (sep *> p)

Once you find a `sep`, you need another `p` in the `many`.

**Comment by mrkkrp** [comment]
@bartavelle, first of all, that problem demonstrates certain flaw in Parsec. Please open a separate issue asking to improve `makeExprParser` to support repeating opeartors. My opinion is that you should not resort to this sort of hack just to make your expression parser work.

**Comment by mrkkrp** [comment]
@bartavelle, that problem will be addressed in 4.3.0 approximately, those combinators won't be removed until this is implemented. See #64.

**Comment by jbapple** [comment]
> @tulcod, What I can do for those who will want to switch, is write a tutorial explaining important details. I don't think switching will take much effort, users won't need to think (that's difficult part!), so it will be mainly mechanical (renaming, flipping argument order).

Did this tutorial ever get written?

**Comment by mrkkrp** [comment]
@jbapple  No, there isn't one specifically about migration—the closest things are [the Megaparsec tutorial][1], which I have just brought up to date, and the "Megaparsec vs Parsec" section of the [README][2], which lists the main differences between the two libraries. The [CHANGELOG][3] is also useful if you need to pin down when something was renamed or moved.

In practice most of the friction comes down to three things: the extra `e` type parameter for the custom error component (`Void` if you do not need one), stream polymorphism via `Tokens s` instead of `String`, and the fact that parse now returns a `ParseErrorBundle` that you pretty-print with `errorBundlePretty`. Once those are in place, the rest of a typical Parsec parser tends to carry over unchanged.

[1]: https://markkarpov.com/tutorial/megaparsec
[2]: https://github.com/mrkkrp/megaparsec/blob/master/README.md
[3]: https://github.com/mrkkrp/megaparsec/blob/master/CHANGELOG.md
