### ISSUE TITLE
Parsing function application

### ISSUE THREAD

**Issue by byorgey** [mrkkrp/megaparsec#245]
Let me first say thanks for the great library---using it is a joy.

For a long time, with both `parsec` and more recently with `megaparsec`, I have used a certain "trick" for parsing expressions involving Haskell-like function application, where I use `makeExprParser` with a high-precedence "operator" parsed as `symbol ""`.  Here's a simple example (ignore the fact that it makes no sense to have function application when the only other expression syntax is for natural numbers and addition):

```
{-# LANGUAGE CPP #-}

import Control.Monad (void)
import Control.Applicative (empty)
import Text.Megaparsec
import Text.Megaparsec.Char
import Text.Megaparsec.Expr
#if MIN_VERSION_megaparsec(6,0,0)
import qualified Text.Megaparsec.Char.Lexer as L
#else
import qualified Text.Megaparsec.Lexer as L
#endif
import Data.Void

data Expr = Lit Integer | Plus Expr Expr | App Expr Expr
  deriving Show

type Parser = Parsec () String

sc :: Parser ()
sc = L.space (void spaceChar) empty empty

symbol :: String -> Parser String
symbol = L.symbol sc

integer :: Parser Integer
integer = L.lexeme sc L.decimal

parens :: Parser a -> Parser a
parens = between (symbol "(") (symbol ")")

parseExpr = makeExprParser parseAtom table
  where
    table = [ [InfixL (App  <$ symbol "")]
            , [InfixR (Plus <$ symbol "+")]
            ]

parseAtom :: Parser Expr
parseAtom =
      Lit <$> integer
  <|> parens parseExpr

main :: IO ()
main = do
  let res = parse parseExpr "" "(3 + 2)"
  case res of
    Right e  -> print e
    Left err -> print err
```

The above works with `megaparsec-5.3.1` (as in, the above `main` method outputs `Plus (Lit 3) (Lit 2)`), but as of `megaparsec-6` it generates a parse error instead. In fact, using `git bisect` I was able to identify the exact commit at which this stops working, namely, 45f30ae (which in the end is probably not all that helpful, seeing as that looks like a giant commit rewriting major parts of the library).

I realize that the correct answer may be that this was never "supposed" to work in the first place.  In that case I would love some pointers as to what would be a more sensible way to write this kind of parser.

**Comment by mrkkrp** [comment]
Thanks, this is due to a bug actually. The bug is in the `tokens` primitive. When matching empty collection of tokens (empty string in your case), we currently use `cok` continuation (consumed OK), while we should use `eok` ("empty" OK, meaning we didn't consume anything).

Fix is coming. 6.1.1 will be probably out today. Thanks for the report again!

**Comment by mrkkrp** [comment]
Version 6.1.1 is on Hackage, your trick should work again with it.

**Comment by byorgey** [comment]
Works great!  Thanks for the quick fix!
