### ISSUE TITLE
Is there a butNot combinator

### ISSUE THREAD

**Issue by jvanbruegge** [mrkkrp/megaparsec#247]
I looked through the Hackage documentation and was not able to find something like this, so I assume not (then this would be a feature request):
My use case is that I parse something that is quiet general but is not allowed to be a reserved word (which I have a second parser for). So basicly:
```haskell
literal = literalName `butNot` reservedWord
literalName = some printChar
reservedWord = string "hello"
```
`butNot` would take two parsers and succeed and return the result of the first one, if the second one (on the same input as the first) fails.

Is there a combination of existing operators that can do something similar?

**Comment by mrkkrp** [comment]
This is a relatively common use case, two solutions are shown in this SO answer (although they deal with checks in the form of predicates, not parsers, which is more common):

https://stackoverflow.com/questions/23964405/parsec-error-message-at-specific-location/45636176#45636176

----

BTW, `reservedWord` should probably be like this:

```haskell
reservedWord = string "hello" <* notFollowedBy printChar
```

So you don't parse `"hello"` as a keyword when it's just a prefix of an identifier.

----

Back to the idea of adding `butNot`. I see no problem with running the right-hand parser and if it fails running left-hand parser as usual. However, if the right-hand parser succeeds, it's not clear what sort of parse error we should generate. You see, even if `reservedWord` has a label attached to it, we only have access to it when it fails, so when it succeeds the best thing we can do is to pick first token from input stream and say that it's unexpected. I think this is what `notFollowedBy` has to do right now, but with `notFollowedBy` we really have no choice.

So I'd say you better use one of the two approaches from that SO answer and check it like this: ``literalCandidate `notElem` listOfAllKeywords``, then fail using `fail`, `failure`, or `fancyFailure` depending on what level of sophistication you desire to achieve with respect to parse errors.

**Comment by jvanbruegge** [comment]
You are right, using a predicate is probably better than using a parser. The stackoverflow answers work quite good:
```hs
data Identifier = Identifier String
                deriving (Show, Eq)

data ReservedWord = Keyword Keyword
                  | FutureReservedWord FutureReservedWord
                  | NullLiteral
                  | BooleanLiteral Bool
                  deriving (Show, Eq)

data Keyword = Break | Case | Catch | Continue | Debugger | Default | Delete | Do | Else
                | Finally | For | Function | If | In | Instanceof | New | Return | Switch
                | This | Throw | Try | Typeof | Var | Void | While | With
                deriving (Show, Eq, Enum)

data FutureReservedWord = Class | Const | Enum | Export | Extends | Import | Super
                        | Implements | Interface | Let | Package | Private | Protected
                        | Public | Static | Yield
                        deriving (Show, Eq, Enum)

identifier :: Parser Identifier
identifier = withPredicate (not . isReservedKeyword) "Cannot use a reserved words as identifier" identifierName >>= return . Identifier

identifierName :: Parser String
identifierName = do
    start <- identifierStart
    rest <- many (identifierStart <|> digitChar)
    return $ start:rest
        where identifierStart = letterChar <|> oneOf ['$', '_']

withPredicate :: (a -> Bool) -> String -> Parser a -> Parser a
withPredicate f msg p = do
    r <- lookAhead p
    if f r then p else fail msg

isReservedKeyword :: String -> Bool
isReservedKeyword s = s `elem` (toList Break) || s `elem` (toList Class) || s `elem` ["null", "true", "false", "undefined"]
        where toList a = fmap (fmap toLower . show) [a ..]
```
```
> parseTest identifier "aosidkjasd"
Identifier "aosidkjasd"
```
```
> parseTest identifier "var"
1:1:
Cannot use a reserved words as identifier
```
