### ISSUE TITLE
huge slowdown compared to parsec

### ISSUE THREAD

**Issue by LeanderK** [mrkkrp/megaparsec#248]
i switched from parsec to megaparsec and noticed a severe slowdown. This is probably my fault, since i have a somewhat complicated setup (i parse a stream of tokens, not characters) and have written my own Stream instance.
The Stream instance is [here](https://github.com/exemplator/java-parser/blob/bench2/src/Language/Java/Parser.hs#L75).
A comparison of the slowdown can be seen [here](https://github.com/exemplator/java-parser/blob/bench2/bench.html) for megaparsec and [here](https://github.com/exemplator/java-parser/blob/bench2/benchOld.html) for parsec. 
Here is an overview over for the profiling: https://gist.github.com/LeanderK/bf471e4cbf0d049f99976ad41ded7882

What has changed? I switched from parsec to megaparsec and replaced `L` with `Located` (in Position).

The parser is not very optimised yet (many try-statements etc.), i first want to regain speed compared to parsec and then start working on optimising other parts.

**Comment by mrkkrp** [comment]
Hi, thanks for bringing this up. It's true that I benchmarked parsers that consume only the default stream types: `String`, strict and lazy `Text`, strict and lazy `ByteString`, so I'm not sure about the case of custom streams.

I see the benchmarks are not identical, so it's kinda difficult to see real difference. Can you provide the same report made with Parsec vs Megaparsec (the same set of benchmarks)?

**Comment by LeanderK** [comment]
i am aware that the benchmarks are not ideal. I am very busy right now, but i might find some time today, if not probably tomorrow.
I don't think much has changed beside adding the last 2 files. But to be 100% sure i have to run these again.

**Comment by mrkkrp** [comment]
Closing due to the lack of activity. Feel free to reopen when you have the benchmark results we have talked about.
