### ISSUE TITLE
some haddocks missing

### ISSUE THREAD

**Issue by ghorn** [mrkkrp/megaparsec#249]
I was looking for the haddocks for `skipMany` and found they were unavailable: http://hackage.haskell.org/package/megaparsec-6.1.1/docs/doc-index-All.html

This might be an issue with re-exports from internal modules.

**Comment by mrkkrp** [comment]
I guess it happens because these functions come from a separate package called `parser-combinators`, not from an internal module. Not sure what I can do to fix this, maybe we should ask the question on Haddock issue tracker?

**Comment by mrkkrp** [comment]
Looks like this is a Haddock issue and similar problems have been reported in the past. Closing because it's not a problem with Megaparsec per se.

**Comment by mrkkrp** [comment]
Opened an issue on Haddock's issue tracker: haskell/haddock#682.
