### ISSUE TITLE
Lexer.float consumes integer numbers

### ISSUE THREAD

**Issue by nau** [mrkkrp/megaparsec#250]
It's a quite weird that float parser consumes integer literals like `45`.
In megaparsec 5 I'd have a parser like
    ```try floatLit <|> integerLit```
Now floatLit consumes integers and returns Scientific. Hence I can't easily distinguish 4.0 and 4 because Scientific.floatingOrInteger returns Integer for both.
Is there a simple workaround for that? 
Anyway, I'd rather prefer the previous behavior. IFAIR, this is the way most parsers that I used work.
And it most likely breaks everyone's parsers.

**Comment by recursion-ninja** [comment]
Integers are a subset of the real numbers. If a parser matches all real numbers, it will consquently match all integers. If the real value is also an integral value then the more restrictive type (the integral value) should be returned in that case. This makes sense to me.

If you really want to distinguish between the real valued and also integral valued strings `42.0`, `42`, and `4.2e1` I think you should use the `match` combinator and monadic bind to introspect the match parse result.

**Comment by nau** [comment]
It's smart to consider real life (read practical aspects of the library usages) when designing API.
I claim that in most cases users would expect float parser to not parse 42, and would not like to do some tricks to solve this quite usual task.
Also, there are approximately zero programming languages where int <: float, and usually when you parse these values you want different types.
Basically, megaparsec 6 have broken a lot of parsers for no particular reason, and I don't see any benefits of this decision.
@mrkkrp, please, consider moving float parser to previous behavior. I'm sure you know that many usages of megaparsec are some programming language parsers and this change breaks most of them. Just try to add floats to your https://markkarpov.com/megaparsec/parsing-simple-imperative-language.html :)

**Comment by mrkkrp** [comment]
I won't comment on which behavior is better, I'll just note that it's not possible to change it now (in version 7 perhaps, but I have no idea when it'll be released).

To do what you want, try to parse integer making sure it's not followed by dot or E, then if this fails use 'float'.

Hope it helps.

**Comment by mrkkrp** [comment]
@nau, I'll get back to this when I'm back home from my current trip in Italy. Thanks for you feedback.

**Comment by nau** [comment]
@mrkkrp, don't worry, I ended up copy/pasting previous implementations of these parsers.
I assume none noticed this problem mostly because latest Haskell LTS contain megaparsec 5, and megaparsec 6 included only in nightly snapshots on Stackage.
As soon as people start to upgrade you'll see more of this kind of questions :)

**Comment by mrkkrp** [comment]
@nau Megaparsec 6.2.0 is on Hackage with `float` that consumes only floating point literals as per Haskell language report, like in version 5. Your comments make sense and it was a mistake to allow `float` accept integers, thanks.

**Comment by nau** [comment]
Thank you!
