### ISSUE TITLE
The documentation on parsers is outdated in `6.*.*`

### ISSUE THREAD

**Issue by ShrykeWindgrace** [mrkkrp/megaparsec#252]
Hi,

since the update of signatures of parsers like `char` (from `Char -> m Char` to `Token s -> m (Token s)`), it is borderline impossible to understand and use them, especially if you are a beginner switching from Parsec.
Consider this code:
```
module Main where

import Text.Megaparsec.Char (char)

main :: IO ()
main = putStrLn "test"

semicolon = char ';' --taken from Megaparsec haddock
```
It would not compile (latest `stack` with lts-9.6) with
```
* Couldn't match expected type `Text.Megaparsec.Stream.Token s0'
                  with actual type `Char'
      The type variable `s0' is ambiguous
    * In the first argument of `char', namely ';'
      In the expression: char ';'
      In an equation for `semicolon': semicolon = char ';'
```
After some wandering around the documentation, one might put `Token` constructors somewhere in the definition of `semicolon`, or try to add explicit signature for this function. I did not find a working combination.

I also tried to play with examples in posts related to the release of `6.*.*` to no avail. The direct copypaste `parseTest (many spaceChar <* many (char 'b') <* eof) "  a"` 
will fail in ghci with
```
    * Ambiguous type variable `e0' arising from a use of `parseTest'
      prevents the constraint `(Text.Megaparsec.Error.ShowErrorComponent
                                  e0)' from being solved.
```

**Comment by mrkkrp** [comment]
It's true that the types are more polymorphic in Megaparsec. In the examples you list, the type signatures were omitted to reduce visual noise. It is however rather trivial to add top-level signatures and solve the problem that way.

I explicitly explain the issue in the documentation:

https://hackage.haskell.org/package/megaparsec-6.2.0/docs/Text-Megaparsec.html

That means that you just need to define a type synonym first:

```haskell
type Parser = Parsec Void Text
```

And then you can do this:

```haskell
semicolon :: Parser Char
semicolon = char `;`
```

----

> one might put `Token` constructors somewhere in the definition of semicolon

`Token` is a function on type level, there is no `Token` constructor in Megaparsec.

**Comment by ShrykeWindgrace** [comment]
Shame on me, I should have paid more attention=) Thank you!

**Comment by mrkkrp** [comment]
No problem, feel free to open issues if you run into any trouble using the library :-)
