### ISSUE TITLE
[question] Equivalent "integer" Parsec in Megaparsec

### ISSUE THREAD

**Issue by lalo** [mrkkrp/megaparsec#254]
integer in parsec is defined as

> This lexeme parser parses an integer (a whole number). This parser is like natural except that it can be prefixed with sign (i.e. '-' or '+'). Returns the value of the number. The number can be specified in decimal, hexadecimal or octal. The number is parsed according to the grammar rules in the Haskell report.

and natural is defined as

> This lexeme parser parses a natural number (a positive whole number). Returns the value of the number. The number can be specified in decimal, hexadecimal or octal. The number is parsed according to the grammar rules in the Haskell report.

as per [Text Parsec Token](https://hackage.haskell.org/package/parsec-3.1.11/docs/Text-Parsec-Token.html)

I've defined the following

```
integer' :: Parser Integer
integer' = lexeme L.decimal

integer = natural <|> L.signed sc (dbg "inside_sign" integer')

hexadecimal :: Parser Integer
hexadecimal = lexeme $ char '0' >> char' 'x' >> L.hexadecimal

octal :: Parser Integer
octal = lexeme $ char '0' >> char' 'o' >> L.octal

natural = (dbg "hex" hexadecimal) <|> (dbg "octal" octal)
```

and when trying to parse the number 2147483647 and a simple `0`

I get the following debug info:

```
hex> IN: "2147483647,<newline>    UInt32Min = 0,< <…>
hex> MATCH (EERR): <EMPTY>
hex> ERROR:
hex> tests/schema/defaults.bond:13:16:
hex> unexpected '2'
hex> expecting '0'

octal> IN: "2147483647,<newline>    UInt32Min = 0,< <…>
octal> MATCH (EERR): <EMPTY>
octal> ERROR:
octal> tests/schema/defaults.bond:13:16:
octal> unexpected '2'
octal> expecting '0'

inside_sign> IN: "2147483647,<newline>    UInt32Min = 0,< <…>
inside_sign> MATCH (COK): "2147483647"
inside_sign> VALUE: 2147483647

hex> IN: "0,<newline>    UInt32Max = 0xFFFFFFFF,< <…>
hex> MATCH (CERR): '0'
hex> ERROR:
hex> tests/schema/defaults.bond:14:18:
hex> unexpected ','
hex> expecting 'X' or 'x'

enum> IN: "enum EnumType1<newline>{<newline>    En <…>
enum> MATCH (CERR): "enum EnumType1<newline>{<newline>    En <…>
enum> ERROR:
enum> tests/schema/defaults.bond:14:18:
enum> unexpected ','
enum> expecting 'X' or 'x'
```

I'm guessing `hexadecimal` is consuming the token `0` and this in turn avoid the rest of the parsers to be executed (in theory `integer'` should successfully parse it). What confuses me is that the behavior of the combinator `<|>` of a failing parser should not consume the token but the debug info I'm seeing shows that it is being consumed.

Any advice on how to approach this? It seems general enough for it to be an existing implementation of an integer parser that parses hex, dec, oct, zeros and signed numbers maybe you will point me to an existing one. Any how, what am I missing?

**Comment by mrkkrp** [comment]
Hi, `l (<|>) r` does not even try `r` if `l` fails consuming input. You need to use `try` to enable backtracking (also read documentation for `try`):

```haskell
hexadecimal = lexeme . try $ char '0' >> char' 'x' >> L.hexadecimal
-- the same for octal
```

**Comment by lalo** [comment]
Thanks, forgot about `try`. Closing this question. Thank you for your work, I'm enjoying Megaparsec.
