### ISSUE TITLE
Make highlighting of problematic part of input continuous

### ISSUE THREAD

**Issue by mrkkrp** [mrkkrp/megaparsec#265]
So far we can only highlight a point in input with `^` (in `parseErrorPretty'`, `parseTest'` and similar). We would like to do something like:

```
1:1:
  |
1 | blah foo bar
  | ^^^^
```

**Comment by recursion-ninja** [comment]
I have an almost complete implementation of this in my fork. There was some trickiness with getting it to work on any stream type that I think I have almost resolved.
 
I can prioritize finishing this over winter break if you'd like my assistance.

**Comment by mrkkrp** [comment]
Sure, if you would like to contribute this feature, go right ahead.
