### ISSUE TITLE
Why does Stream require Ord?

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [mrkkrp/megaparsec#268]
I used Megaparsec to write [a shallow embedding](https://github.com/JeffreyBenjaminBrown/Tidal/blob/parseOps/Sound/Tidal/Epic/Parse/CustomStreamDemo/Functions.hs) that lets a user parse a function of type Func = Float -> Float from a custom Stream consisting of a sequence of Funcs and unary and binary operators on Funcs. I had to make the Tokens unlawful instances of Ord, because a true ordering on the complete space of functions from Floats to Floats would (I believe) require infinite computing power.

Why do Tokens have to be Ord? Is that just for speed, or is it a safety thing? I made == and <= always return False, in the hopes that that means Megaparsec would never (because it thought they were equal) substitute a term it had already parsed for a term it was in the middle of parsing. I've tested the code and it seems to work but I don't know whether I'm inviting downstream problems.

(Yesterday I started [a Reddit discussion about this question](https://www.reddit.com/r/haskell/comments/7mytnb/insincere_instances_in_megaparsec_dangerous/).)

**Comment by mrkkrp** [comment]
This is just a way to avoid specifying `Ord` manually for some functions. Perhaps the constraint could be put in the definition of the `MonadParsec` class instead. `Ord` is necessary because we want to be able to store tokens in parse errors and there they are kept in `Set`s, which require the constraint.

**Comment by mrkkrp** [comment]
This also automatically ensures that tokens are comparable for equality because this is assumed by many basic combinators. The `Ord (Tokens s)` part could be replaced with `Eq (Tokens s)` I think.

**Comment by JeffreyBenjaminBrown** [comment]
All my parsers use satisfy rather than equality testing, so I think the second argument won't bite. It does seem a little worrying that my tokens will have trouble being kept in parse errors, though.

Someone on Reddit suggested I just copy the code from Megaparsec.Expr and don't call it a parser. I would also have to duplicate `some` and `between`. It seems much easier to use Megaparsec than to rebuild the relevant parts of it, but I guess I'll do that if I run into problems.

**Comment by mrkkrp** [comment]
Closing for now then.
