### ISSUE TITLE
Why does the following go into some infinite loop?

### ISSUE THREAD

**Issue by nanonaren** [mrkkrp/megaparsec#271]
```
import Data.Char (isDigit)
import Data.Void
import Text.Megaparsec
import qualified Text.Megaparsec.Char.Lexer as L
import Text.Megaparsec.Char (satisfy, space)

main = print $ runParser stream "file" "What is the value of 10 and 20?"

stream = choice [whole_number, unknown]

lexeme :: Parsec Void String a -> Parsec Void String a
lexeme = skipManyTill space

whole_number = do
  n <- lexeme L.decimal
  return (show n)

unknown :: Parsec Void String String
unknown = some $
  satisfy (not . isDigit)
```

It gets stuck when running `main`. The `choice` combinator seems to be the issue. The individual parsers work fine.

**Comment by mrkkrp** [comment]
`skipManyTill p end` runs `p` repeatedly till `end` matches. `p` is `space` in your case, which consumes *many* (that is, possibly zero) space characters. So `p` matches without consuming input and so it's run by `skipManyTill` ad infinitum. Try running `whole_number` on something like `"What"`, which is actually happening with your `stream` (unfortunate naming, it's rather a `parser` than `stream`).

**Comment by nanonaren** [comment]
Ah okay. I wondered why the comment in the lexer module said make sure the space parser does not succeed on empty input. Yes, running `whole_number` on "What" also gets stuck. Thanks.
