### ISSUE TITLE
getting bad parse error report

### ISSUE THREAD

**Issue by bdmagnuson** [mrkkrp/megaparsec#274]
I posted this on stackoverflow first but it's not really a good fit for that forum since there are a fair number of moving parts here and I didn't want to post a "github link <--- fix my bug plz kthxbye" so there's a lot of explantation and code snippets.

That said I'm having a issue with the parser reporting bad information when a parse error is encountered and I'm hoping for a bit of guiadance.

I'm parsing in two stages.  The first stage handles include/ifdef/macro directives and chunks the input up into `[Span]` items which define their start/end points in the original inputs along with the body text. This stream is then parsed by the second stage into my AST for subsequent processing.

Each element of the AST carries it's source position and any semantic error caught after parsing prints the **correct** error position regardless of include depth.  This part is crucial since it demonstarates that the correct info resides somewhere at least and is present after parsing.

The problem is given a parse error in the second stage, from an included file, it reports a bogus error with a location at the top level rule.  A parse error in the initial file works fine.  The presence of any directives will divide even the initial file into multiple chunks so it's not a 'single chunk' vs.  'multiple chunks' issue.

Given the fact that the AST is receiving the correct locations  I'm stumped as to how the parser is reporting bad info when parse errors are encountered since it doesn't even know about includes, dealing exclusivly with Spans

I'm included my stream instance (largely cribbed from your blog posts) and (set|get)(Position|Input) code since these seem like the relevant bits.  I feel like there must be some bit of megaparsec housekeeping that I'm not doing or that my Stream instance is invalid for some reason.  If this isn't enough I can start working on packing this up into a gist or something to demonstate the problem directly.

Thanks for you time.

    data Span = Span
      { spanStart :: SourcePos
      , spanEnd   :: SourcePos
      , spanBody  :: T.Text
      } deriving (Eq, Ord, Show)

    instance Stream [Span] where
      type Token  [Span] = Span
      type Tokens [Span] = [Span]
      tokenToChunk  Proxy = pure
      tokensToChunk Proxy = id
      chunkToTokens Proxy = id
      chunkLength   Proxy = foldl1 (+) . map (T.length . spanBody)
      chunkEmpty    Proxy = all ((== 0) . T.length . spanBody)

      positionAt1 Proxy pos (Span start _ _) = trace ("pos1" ++ show start) start
      positionAtN Proxy pos [] = pos
      positionAtN Proxy _ (Span start _ _:_) = trace ("posN" ++ show start) start

      advance1 Proxy _ _ (Span _ end _) = end
      advanceN Proxy _ pos [] = pos
      advanceN Proxy _ _ ts = let Span _ end _ = last ts in end

      take1_ []     = Nothing
      take1_ s      = case takeN_ 1 s of
                        Nothing -> Nothing
                        Just (sp, s') -> Just (head sp, s')

      takeN_ _ [] = Nothing
      takeN_ n s@(t:ts)
        | n <= 0 = Just ([t {spanEnd = spanStart t, spanBody = ""}], s)
        | n <  (T.length . spanBody) t = let (l, r) = T.splitAt n (spanBody t)
                                             sL = spanStart t
                                             eL = foldl (defaultAdvance1 (mkPos 3)) sL (T.unpack (T.tail l))
                                             sR = defaultAdvance1 (mkPos 3) eL (T.last l)
                                             eR = spanEnd t
                                             l' = [Span sL eL l]
                                             r' = (Span sR eR r):ts
                                         in Just (trace (show n) l', r')
        | n == (T.length . spanBody) t = Just ([t], ts)
        | otherwise = case takeN_ (n - T.length (spanBody t)) ts of
                         Nothing -> Just ([t], [])
                         Just (t', ts') -> Just (t:t', ts')

      takeWhile_ p s = fromJust $ takeN_ (go 0 s) s
        where go n s = case take1_ s of
                          Nothing -> n
                          Just (c, s') -> if p c
                                          then go (n + 1) s'
                                          else n

Find include and swap to it:

    "include" -> do
         file <- between dquote dquote (many (alphaNumChar <|> char '.' <|> char '/' <|> char '_'))
         s    <- liftIO (Data.Text.IO.readFile file)
         p    <- getPosition
         i    <- getInput
         pushPosition p
         stack %= (:) (p, i)
         setPosition (initialPos file)
         setInput s

And if we reach the end of input pop stack and continue:

    parseStream' :: StreamParser [Span]
    parseStream' = concat <$> many p
       where p = do
              b <- tick <|> block
              end <- option False (True <$ hidden eof)
              h <- use stack
              when (end && (h /= [])) $ do
                popPosition
                setInput (h ^?! ix 0 . _2)
                stack %= tail
              return b

**Comment by mrkkrp** [comment]
I won't be able to look at this earlier than this weekend, so wait a bit.

**Comment by mrkkrp** [comment]
I just started looking at your code and your `Stream` instance appears to be incorrect:

* `chuckLength` should return number of tokens in a chunk, i.g. number of `Span`s in `[Span]`.
* `chunkEmpty` should only return `True` when its input is `[]`.
* `takeN_` similarly, could be simpler!

Maybe you could take inspiration from this:

```
data Span = Span
  { spanStart :: SourcePos
  , spanEnd   :: SourcePos
  , spanBody  :: NonEmpty Char
  } deriving (Eq, Ord, Show)

instance Stream [Span] where
  type Token [Span] = Span
  type Tokens [Span] = [Span]
  tokenToChunk Proxy = pure
  tokensToChunk Proxy = id
  chunkToTokens Proxy = id
  chunkLength Proxy = length
  chunkEmpty Proxy = null
  positionAt1 Proxy _ (Span start _ _) = start
  positionAtN Proxy pos [] = pos
  positionAtN Proxy _ (Span start _ _:_) = start
  advance1 Proxy _ _ (Span _ end _) = end
  advanceN Proxy _ pos [] = pos
  advanceN Proxy _ _ ts =
    let Span _ end _ = last ts in end
  take1_ [] = Nothing
  take1_ (t:ts) = Just (t, ts)
  takeN_ n s
    | n <= 0   = Just ([], s)
    | null s   = Nothing
    | otherwise = Just (splitAt n s)
  takeWhile_ = DL.span
```

This is more or less what you need with this approach.

That said, I think you're approaching the problem incorrectly here. You see, when you have an input stream in this `[Span]` form, the assumption is that you got this stream as a result of lexing. I.e. your `Span`s are operators, symbols, literals, etc. In your case it's not so, the chunks are too big, you'll have to build your parser not in terms of these chunks, but by looking inside them, so you'll have non-idiomatic solution, and you're likely to run into troubles.

I'd advise doing all this in a single run using `pushPosition` and `popPosition`, these should do the trick nicely (do tell us if they work for you!). If you don't want to do it that way, I (if I were you) would take an approach similar to C. Pre-processor should just concatenate files (you do it in a separate stage, before parsing) and to get correct error positions you could introduce something like commands that set current source position, like with have in Haskell:

```
{-# LINE 100 #-}
```

(I'm not sure about exact syntax, but something like this does exist.) And so your concatenating code should put these markers correctly. Then in parser you pick them up and update parsing position accordingly. Then you do parsing in a single run.

If you'll still need my help, please provide a full reproducing example, as a complete module, what you get, and what you expect to get instead. I'm glad to help, but my time is rather limited these days, sorry.

**Comment by bdmagnuson** [comment]
First, thanks for making the effort to look at this.  I know time is precious.

Taking things in order.

I did modify to `chunkLength` and `chunkEmpty` to your suggested implementation.  No joy.

Regarding my `Stream` typeclass abuse I do agree that the way I'm going about this does run against the 'grain of intent' of the class.  I end up having to write my own lexer which pulls apart the `Span` bits and behaves generally like a `Char` lexer.  Getting everything to typecheck was a bit of a challenge!  It's all just so close to working that I was hoping a few more whacks with the hammer would get that square peg to fit.

As for the preprocessor directives, when I was only supporting includes I was doing precisely as you suggest and using push/pop position.  This worked exactly as expected.  I do have to say that the position stack is of somewhat limited utility though since I still have to maintain my own stack of input and it's trivial to just make that stack a tuple of the position with the remaining input and just use setPosition/setInput.

It's when I wanted to support \`define macros that I ran into difficulty.  Some users have tried to detect the macro and adjust the input with the macro expansion but that messes up source positions later on if the expansion is of different length (i.e. all the time).  So the idea was that the 1st stage parser would detect the macro instances and includes and chop the original input into a small number of rather large `Span`s which would get pulled apart by my existing parser.

Extending the position indicators idea only slightly I could simply put indicators book-ending each include and after each macro expansion to fix up the position.

However, since these can more or less occur anywhere I'll have to wrap my subparsers with a combinator that first checks for this indicator and then runs the original parser.  Seems pretty straightforward actually.  I'll likely pursue this.

That said, if you are still willing I'll try to pack up everything into as minimal a testcase as I can manage since despite my sins it does seem like it should work.

**Comment by mrkkrp** [comment]
> That said, if you are still willing I'll try to pack up everything into as minimal a testcase as I can manage since despite my sins it does seem like it should work.

If you think my help is necessary, then sure go ahead and pack it, I'll take a look.

**Comment by bdmagnuson** [comment]
Let's go ahead and close this one out.  I ended up implementing the above and it's working out fine.  While doing that I managed to get the same parse error (where it was pointing up to the top rule).  This was caused by an overzealous `try` that caused the whole parse to 'run back to momma'.  As what I was attempting was hacky at best anyway we can drop it.
