### ISSUE TITLE
Consider dropping stacks of source positions in version 7

### ISSUE THREAD

**Issue by mrkkrp** [mrkkrp/megaparsec#275]
It's not clear to me whether anyone is using that feature, but I see that it adds a lot of noise and complexity. What needs to be done:

* see if any major project uses the feature
* ask some people (perhaps make a poll on Twitter) if they use the feature (most people probably do not even know that we support that)
* if it's not used, drop it in version 7

**Comment by bdmagnuson** [comment]
Not sure if the question I just posted precipitated this, but for the record I was managing the stack myself and only switched to push/pop position as a debug attempt in case there was some hidden magic beyond the obvious functionality.

**Comment by mrkkrp** [comment]
Dropped in 7120bae9b27f4367ea802935217f71a78c3c2756. Closing.
