### ISSUE TITLE
Backtracking with Scientific Numbers

### ISSUE THREAD

**Issue by Tuplanolla** [mrkkrp/megaparsec#278]
Let `units = string "J" <|> string "eV"` and
`work = runParser (liftA2 (,) scientific units) "<interactive>"`.
Now `work "42.13J"` produces the expected result,
but `work "42.13eV"` fails unexpectedly.
This happens, because `scientific` does not
correctly restore the backtracking state
after attempting to read `"42.13e+0"`.
The same thing applies to `work "42..."`.

Applying the following patch
to `Text/Megaparsec/Char/Lexer.hs` should take care of the issue.

    499,500c499,500
    <   SP c e' <- option (SP c' 0) (dotDecimal_ (Proxy :: Proxy s) c')
    <   e       <- option e' (exponent_ e')
    ---
    >   SP c e' <- option (SP c' 0) (try (dotDecimal_ (Proxy :: Proxy s) c'))
    >   e       <- option e' (try (exponent_ e'))

**Comment by mrkkrp** [comment]
Thanks, this will be taken care of soon.

**Comment by mrkkrp** [comment]
I just released version 6.4.1 with the fix.
