### ISSUE TITLE
sepBy/manyTill missing

### ISSUE THREAD

**Issue by flip111** [mrkkrp/megaparsec#289]
https://hackage.haskell.org/package/megaparsec-6.5.0/docs/Text-Megaparsec.html#v:parse

https://markkarpov.com/megaparsec/parsing-simple-imperative-language.html

On those two pages there is a mention of `sepBy` and `sepBy1`. However i can't find these functions in megaparsecc 6.5.0 documentation.

https://hackage.haskell.org/package/megaparsec-6.5.0/docs/Text-Megaparsec-Char-Lexer.html#v:charLiteral

https://hackage.haskell.org/package/megaparsec-6.5.0/docs/doc-index-M.html

manyTill is missing too

**Comment by mrkkrp** [comment]
They all are here: https://hackage.haskell.org/package/parser-combinators. Since version 6.

**Comment by mrkkrp** [comment]
The combinators are re-exported for you from `Text.Megaparsec`.

**Comment by flip111** [comment]
Is it possible to link to that documentation in more places ? It's difficult to find i think

**Comment by mrkkrp** [comment]
Well it's almost at the top already: https://hackage.haskell.org/package/megaparsec-6.5.0/docs/Text-Megaparsec.html, section about re-exports.

**Comment by flip111** [comment]
Maybe make a list of functions that are re-exported and put them in the documentation so people can search by function name.

**Comment by mrkkrp** [comment]
Then I’ll need to remember to keep the export list in sync with the `parser-combinators` package, which is error-prone.

**Comment by recursion-ninja** [comment]
@flip111 Note that if you look at the haddock documentation for `[Text.Megaparsec`](https://hackage.haskell.org/package/megaparsec-6.5.0/docs/Text-Megaparsec.html) you can select the [`index`](https://hackage.haskell.org/package/megaparsec-6.5.0/docs/doc-index.html) link in the upper right hand corner. This takes you to a page where you can search _every_ exported function of the package from _every_ module combined either by letter or view the all functions on a single page by selecting [`All`](https://hackage.haskell.org/package/megaparsec-6.5.0/docs/doc-index-All.html). 

It is possible to discover the exported functions by using the standard Haddock documentation.

**Comment by mrkkrp** [comment]
Closing because I don’t see what action should be taken here. We already have a section in the docs about the re-export.
