### ISSUE TITLE
More documentation needed on how to debug and fix memory issues

### ISSUE THREAD

**Issue by jwiegley** [mrkkrp/megaparsec#291]
The [hnix](https://github.com/haskell-nix/hnix/issues/200) project recently switched to `megaparsec`, because Trifecta was consuming far too much memory. `megaparsec` is doing much better, but there's still room for improvement. I'm seeing 4 GB of allocations across a very short run, which I'm expecting in the neighborhood of 10-20 megabytes.

I've read the Web docs available on what could be going wrong and how to track it down, but I'm running out of ideas. Is this something you can help us with? We're still an order of magnitude slower than C++ Nix, but I have a feeling we could be faster if we get these allocations under control. Thanks!

**Comment by mrkkrp** [comment]
The project is very interesting, glad you decided to try Megaparsec for this!

Yeah, improvements in this area would be great. I need more information though.

* First, what version of Megaparsec are you using?
* Have you tried to run this with profiling (I guess you have), what does it say?

Although I did some work on improving memory usage, etc. over time, still it's much worse than C/C++ level. Maybe we could use the `hnix` project to find out which parts of Megaparsec suck and fix them.

----

P.S. I'll also be starting an experiment that can be described as "Megaparsec re-write powered by backpack", I created a repo here https://github.com/mrkkrp/megabackheck, maybe in future this will be a better option for you (yeah, I may still come up with a better name for the project).

**Comment by jwiegley** [comment]
- We're using `megaparsec` 6.4.1

- Here is the profiling output after running our tests (takes 32s normally, about 5 minutes with profiling enabled, parsing around 1.2 million lines in 12k files): [hnix-tests.zip](https://github.com/mrkkrp/megaparsec/files/1949955/hnix-tests.zip)

- The heap profile: [hnix-tests.pdf](https://github.com/mrkkrp/megaparsec/files/1949962/hnix-tests.pdf)

I'd love to work with you on improving the performance, since `megaparsec` is really the best game in town for our project's needs. I wonder if something akin to [parsec-free](http://hackage.haskell.org/package/parsec-free) rewritten for `megaparsec` would aid in analysis and backtrack debugging.

**Comment by mrkkrp** [comment]
Anyway, I'll try to find time this weekend and see what can be improved.

**Comment by mrkkrp** [comment]
> I'm seeing 4 GB of allocations across a very short run, which I'm expecting in the neighborhood of 10-20 megabytes.

How can I reproduce this?

**Comment by jwiegley** [comment]
@mrkkrp The easiest way is to have Nix installed, and to follow the steps in the README file about profiling.

If you don't have Nix, then make sure you've updated the submodules for hnix, and clone this repository somewhere: https://github.com/NixOS/nixpkgs/

Now you can run just the parser over all of its files after building `hnix`:

    find .../nixpkgs -name '*.nix' -type f -print | hnix --parse-only -f -

It's possible that the `hnix` build might even require `nix` to be installed. If that's the case, edit `Builtins.hs` and search for the `derivationStrict` entry in the builtins table.  Just comment the whole thing out and rebuild, since builtins are only used during evaluation.

**Comment by mrkkrp** [comment]
Great, I’m on NixOS so there should be no problems.

**Comment by jwiegley** [comment]
@mrkkrp Here's the JSON version: http://ftp.newartisans.com/pub/hnix-tests.prof.xz

**Comment by jwiegley** [comment]
@mrkkrp Also, if you want just one file that shows slowness rather than parsing them all, try `nixpkgs/pkgs/top-level/all-packages.nix`. This takes about 1.1 seconds to parse, while the C++ parser can do so about an order of magnitude faster.

**Comment by mrkkrp** [comment]
The project does not compile for me:

```
[32 of 36] Compiling Nix.Reduce       ( src/Nix/Reduce.hs, dist/build/Nix/Reduce.o )

src/Nix/Reduce.hs:79:1: warning: [-Wunused-top-binds]
    Defined but not used: ‘gatherNames’
   |
79 | gatherNames = cata $ \case
   | ^^^^^^^^^^^
[33 of 36] Compiling Nix.XML          ( src/Nix/XML.hs, dist/build/Nix/XML.o )
[34 of 36] Compiling Nix.Builtins     ( src/Nix/Builtins.hs, dist/build/Nix/Builtins.o )

src/Nix/Builtins.hs:122:50: error:
    • Exception when trying to run compile-time code:
        data/nix/corepkgs/derivation.nix: openFile: does not exist (No such file or directory)
      Code: do let ...
               addDependentFile f
               Success expr <- runIO $ parseNixFile f
               ....
    • In the untyped splice:
        $(do let f = "data/nix/corepkgs/derivation.nix"
             addDependentFile f
             Success expr <- runIO $ parseNixFile f
             [| cata Eval.eval expr |])
    |
122 |     , add0 TopLevel "derivation"                 $(do
    |                                                  ^^^^...
[36 of 36] Compiling Paths_hnix       ( dist/build/autogen/Paths_hnix.hs, dist/build/Paths_hnix.o )
```

The file `data/nix/corepkgs/derivation.nix` seems to be missing. I was just following the instructions in the "Getting started" section of readme.

**Comment by mrkkrp** [comment]
Ah sorry, of course there are submodules. I'll return to this tomorrow.

**Comment by mrkkrp** [comment]
Is there any reason you don't use new Cabal commands like `new-build` and `new-test` in the readme? The Gitter chat doesn't work for me (says the chat does not exist), otherwise I could communicate more interactively through that perhaps?

**Comment by jwiegley** [comment]
No real reason not to use `new-build`, I've just never used it before.

**Comment by jwiegley** [comment]
Do these optimization flags replicate the effect of "moving it all into one module":

```
when:
  - condition: flag(optimize)
    ghc-options:
      - -fexpose-all-unfoldings
      - -fspecialise-aggressively
      - -O2
```

And the `Lightning` features sound like all that we'd need. :)

**Comment by mrkkrp** [comment]
As I understand these flags are applied to the entire project. I think this will make GHC very busy and compilation times will be horrible without much benefit compared to moving everything in one module or using inlining. But try it.

**Comment by jwiegley** [comment]
You're right, I'll just move it all into one module.

**Comment by mrkkrp** [comment]
I'm not sure if this needs to stay open, because I think there is no obvious continuation for the discussion. I'm going to close for now, but you can re-open if you wish. Megaparsec 7 will be 20-30% faster I think if a change that I plan to make goes well, not sure if that's good enough for `hnix`, but certainly that will be quite an achievement and will make us even with Attoparsec on most benchmarks.
