### ISSUE TITLE
How to use custom token type?

### ISSUE THREAD

**Issue by mattgreen** [mrkkrp/megaparsec#295]
Thanks for a wonderful library! For a project I'm doing I'd really prefer to handle lexing myself, but I'm having trouble adapting the library to work with non `String`/`Text` datatypes. It seems that in version 6 the `Stream` class was greatly expanded and I get stumped trying to create an instance for it :(.

Is there a simple example of this somewhere I could build off of?

Thank you!

**Comment by mrkkrp** [comment]
Here is an example with source positions attached to tokens: https://github.com/mrkkrp/megaparsec/blob/master/tests/Text/MegaparsecSpec.hs#L1773-L1802. Does it help?

**Comment by mattgreen** [comment]
That looks perfect. I'll try that out. Thank you for a fast response!

**Comment by BebeSparkelSparkel** [comment]
@mrkkrp can you update the link?

**Comment by mrkkrp** [comment]
@BebeSparkelSparkel I don't think we have this in the same form in the tests. The `Stream` type class is different enough 
now for these tests to be of no use (as tests and as examples), but here you go:

https://github.com/mrkkrp/megaparsec/blob/f49b9b479b836feb0ae4105b0f6fe68056fa23f2/tests/Text/MegaparsecSpec.hs#L1773-L1802

**Comment by BebeSparkelSparkel** [comment]
Ok thanks
