### ISSUE TITLE
expected tokens source location

### ISSUE THREAD

**Issue by flip111** [mrkkrp/megaparsec#298]
For debugging purposes would it be possible to supply info about the source location where an expectation comes from. For example when i have a parse error any of these can be expected:

```
,
--
M.Label: white space
M.EndOfInput, possibly tokens that did not match have been consumed (watch debug output)
```

Would also be interesting to know which chain of parser functions have been considered to come up with these expectations.

**Comment by mrkkrp** [comment]
`dbg` should give you an idea what happened before you got the parse error.

**Comment by flip111** [comment]
With dbg i get something like

```
Name> IN: "some text"
Name> MATCH (COK): "some match"
Name> VALUE: some haskell data type
```

Perhaps change `VALUE:` to `VALUE (source.hs:60):` to point to the definition of that type ?

**Comment by mrkkrp** [comment]
In any case, `dbg` is sufficient I think. We certainly can't add more instrumentation inside of `ParsecT` because that'll likely make it slower. On the contrary I'm trying to find a way to simplify things so we match Attoparsec's performance in version 7.

**Comment by flip111** [comment]
Ok i trust you know best ... but for me it's still difficult to navigate the syntax tree. Maybe because all the times in the `VALUE:` part are compressed into one line and not displayed as a tree. You can close this issue if you think there can be no further improvement to the dbg function.

**Comment by flip111** [comment]
Maybe it's possible to get the last `VALUE:` from the `ParseError` ? then this result can be further analyzed

**Comment by flip111** [comment]
Perhaps it's possible to get the last value of `VALUE:` so it can be further analyzed ?

**Comment by flip111** [comment]
I also don't understand the order in which `dbg` shows things.

I have a bunch of parser rules. This is one:
```haskell
parser = trace "AssociationElement" $ do
    fp <- trace "AssociationElement 1" $ o $ do
      f <- n93
      a <- txt "=>"
      return (f, a)
    ap <- trace ("AssociationElement 2: " ++ show fp) $ n93
    return $ AE fp ap
```

Debug.trace: from top rule to bottom rules
```
ActualParameterPart
AssociationList
AssociationElement
AssociationElement 1
FormalPart
FormalDesignator
Name
AssociationElement 2: Nothing
ActualPart
ActualDesignator
Name
```

megaparsec dbg: from bottom rule, to top rule
```
Name
FormalDesignator
FormalPart
AssociationElement 1  <-- why is this 1 and not 2 ?
Name
ActualDesignator
ActualPart
AssociationElement 2: Nothing  <-- why is this 2 and not 1 ??
AssociationElement
AssociationList
ActualParameterPart
```

**Comment by flip111** [comment]
I also notice when the parser is stuck in a loop `dbg` doesn't output anything but `trace` does.

**Comment by mrkkrp** [comment]
See source code of `dbg`. We put tracing along continuations, because knowing which continuation is followed is useful when debugging. Vanilla `Debug.trace` just traces evaluation of its argument.

**Comment by flip111** [comment]
Is it possible to get the values printed as `VALUE: <something>` as part of the parse error data? That way the build up structures can be further analyzed.

**Comment by flip111** [comment]
When i on stdout:

```
Name> IN: "some text"
Name> MATCH (COK): "some match"
Name> VALUE: <myValue>
```

Can `myValue` be made available in https://hackage.haskell.org/package/megaparsec-6.5.0/docs/Text-Megaparsec-Error.html#t:ParseError ?
I don't know how to explain this better :(

**Comment by mrkkrp** [comment]
Ah, OK. No I don't think this is possible. `ParseError`s get accumulate this sort of thing or we'll be quite inefficient.

**Comment by mrkkrp** [comment]
I think we can close this one now.
