### ISSUE TITLE
Is is possible to make use `makeExprParser` for languages that allow overloaded operators

### ISSUE THREAD

**Issue by CMCDragonkai** [mrkkrp/megaparsec#299]
In Haskell you can write your own operators and give them fixity and associativity declarations.

Is it possible to use `makeExprParser` to help deal with this kind of syntax?

If not, what would be right way to approach it?

**Comment by mrkkrp** [comment]
No, `makeExprParser` can't be used for this because it expects that you know precedence beforehand.

Apparently decisions on precedence should be delayed until we have that info from e.g. `infixr` and friends, but I haven't done anything like this myself (or had need to).

**Comment by mrkkrp** [comment]
@aspiwack kindly provided the following comment on your issue:

> Yann Régis-Gianas says that we shouldn't dynamically change the parser in a file. So all fixity should be specified as an argument to the parser somehow, but just once.
> (but monadic combinators handle such dynamic update pretty well)

**Comment by mrkkrp** [comment]
So if you go with that approach, why not, you could use `makeExprParser`.

**Comment by CMCDragonkai** [comment]
@mrkkrp Can you elaborate on what you mean by "dynamically change the parser in a file". Do you mean you could dynamically change the parser and change how the `makeExprParser` works as you parse the a source file and subsequent imported source files?

**Comment by mrkkrp** [comment]
You can't dynamically change `makeExprParser` but you could write your parser in a way that depends on some sort of state that could be changed dynamically and so behavior of your parser would be able to change dynamically.

**Comment by mrkkrp** [comment]
I guess the question has been answered. Closing, reopen if necessary.

**Comment by CMCDragonkai** [comment]
I suppose the `table` that is passed into the `makeExprParser` can be the state that we are propagating. As we encounter new operators, that table gets updated with new operators. Then the parser itself gets changed by running `makeExprParser` again. I'm still not entirely sure how to do this though. Would be nice as a tutorial though.
