### ISSUE TITLE
Adding support for `binDigitChar` and `binary`

### ISSUE THREAD

**Issue by ghallak** [mrkkrp/megaparsec#301]
I noticed that the library has functions for parsing decimals ([`digitChar`](https://hackage.haskell.org/package/megaparsec-6.5.0/docs/Text-Megaparsec-Char.html#v:digitChar) and [`decimal`](https://hackage.haskell.org/package/megaparsec-6.5.0/docs/Text-Megaparsec-Char-Lexer.html#v:decimal)), hexadecimals ([`hexDigitChar`](https://hackage.haskell.org/package/megaparsec-6.5.0/docs/Text-Megaparsec-Char.html#v:hexDigitChar) and [`hexadecimal`](https://hackage.haskell.org/package/megaparsec-6.5.0/docs/Text-Megaparsec-Char-Lexer.html#v:hexadecimal)), and octals ([`octDigitChar`](https://hackage.haskell.org/package/megaparsec-6.5.0/docs/Text-Megaparsec-Char.html#v:octDigitChar) and [`octal`](https://hackage.haskell.org/package/megaparsec-6.5.0/docs/Text-Megaparsec-Char-Lexer.html#v:octal)), but not for parsing binaries (`binDigitChar` and `binary`).

Is there a reason for why those functions are not implemented?

**Comment by mrkkrp** [comment]
I guess no one bothered to add one so far!

**Comment by ghallak** [comment]
It will be nice to have, and easy to implement. Should I try to implement it?

**Comment by mrkkrp** [comment]
Go ahead!

**Comment by mrkkrp** [comment]
Resolved by f3e26a42231dfac748045325a7f45ba07a04f069.
