### ISSUE TITLE
Add "commit" combinator

### ISSUE THREAD

**Issue by simonmichael** [mrkkrp/megaparsec#315]
The 6.0.0 changelog said:

> - Changed signatures of failure and token, they only can signal trivial errors now.
> - Added a new method of MonadParsec type class called fancyFailure for signalling non-trivial failures. Signatures of some functions (failure, token) have been changed accordingly.

What does trivial/non-trivial here mean.. anything to do with backtracking ?

In hledger we sometimes want to throw a final parse error and guarantee that's what the user will see, with no further backtracking. We think fail doesn't do this, and we are [wondering](https://github.com/simonmichael/hledger/issues/853#issuecomment-413513794) if failure/fancyFailure do it. 

hledger benefits hugely from megaparsec, thanks for the excellent package and support.

**Comment by mrkkrp** [comment]
OK, let's see if I can clarify. There are two kinds of errors: trivial and fancy ones. When two parse errors happen exactly at the same location (for example you failed to match `'a'`, hasn't consumed anything, then failed to match `'b'` -- another alternative), they are merged together. Trivial errors only can be merged with trivial errors and fancy errors only can be merged with other fancy errors. Fancy errors overwrite trivial errors if they happen at the same position.

> In hledger we sometimes want to throw a final parse error and guarantee that's what the user will see, with no further backtracking.

There is no way to disable backtracking, but I suspect that most errors are trivial, and if you use `fancyFailure` in this case, it'll overwrite any other trivial errors that happened at the same position, and so the user will see only that fancy error.

I agree there are cases when disabling backtracking is desirable. Maybe we could add something for this in version 7... Too tried right now to think properly, maybe on the weekend.

**Comment by mrkkrp** [comment]
Going to keep this one as a feature request for the `commit` function.

**Comment by mrkkrp** [comment]
As I'm working on version 8 now, I once again decided not to add `commit`. I'm closing this one, but #381 seems to be relevant, so maybe you'll be interested in that.

**Comment by neongreen** [comment]
> I once again decided not to add commit

Why?

**Comment by mrkkrp** [comment]
@neongreen See [here](https://github.com/mrkkrp/megaparsec/pull/361#issuecomment-546610846).
