### ISSUE TITLE
How to get rid of "rest of"

### ISSUE THREAD

**Issue by anuyts** [mrkkrp/megaparsec#316]
The solution to issue #35 introduces labels starting with "rest of". From the discussion there, I understand:

* that these have to do with the use of `many` and `some`,
* that the appearance of such labels can be avoided by the parser developer.

I would like to understand what I as a parser developer can do to get rid of these "rest of"-labels in favour of something more clarifying.

**Comment by mrkkrp** [comment]
"rest of" appears when you have something like this:

```haskell
myThing = (many digitChar) <?> "thing" -- results in "expecting rest of thing"
```

How to avoid it:

* Don't use `label` or `(<?>)`.
* `digitChar` itself should have a descriptive label. Then you'll get "expecting <that label>".

Actualy this "rest of" thing is an ugly hack. I wonder if we could get rid of it in version 7.

**Comment by mrkkrp** [comment]
If you have ideas how to do things better in these cases, please comment.

**Comment by mrkkrp** [comment]
`many` and `some` are not special in any way, we just adjust this specific case when something that can fail with consumed input (and being able to consume even more) and the whole thing labelled. In that case we do a bit of intervention and prepend `"the rest of "` to the top-level label.

In your example, `label "thing"` is mostly useless, you could as well remove it and get the desired behavior.

**Comment by anuyts** [comment]
But the same effect seems to occur in more complicated parsers:
```haskell
myThing = label "thing" $ do
    string "blah"
    string "blah"
    many $ label "digit" digitChar
    eof
```
Although I haven't tested this specific example, I think when applying this parser to the string "blahblah1234a", the error message will mention "rest of 'thing'", rather than "'digit' or 'end-of-input'".

**Comment by anuyts** [comment]
Also, even in the simpler case
```haskell
myThing = (label "thing" $ some $ label "digit" digitChar) <* eof
```
the label "thing" is not useless: if a bigger parser requires a `myThing` and it fails, then what I want to hear is that it failed to encounter a "thing", not a "digit", as more parsers may start with a digit.

**Comment by mrkkrp** [comment]
I'll try to attack this problem when other issues planned for Megaparsec 7 are resolved. This certainly deserves re-thinking.

**Comment by mrkkrp** [comment]
This must be resolved now.
