### ISSUE TITLE
Add more descriptive errors for elabel and ulabel

### ISSUE THREAD

**Issue by luc-tielen** [mrkkrp/megaparsec#325]
When writing a test earlier today, I used `elabel` with `""` (silly I know, but it was a WIP 😅), but it gave me a non-descriptive error which basically boiled down to:

```
uncaught exception: ErrorCall
NonEmpty.fromList: empty list
```

A quick search through to the codebase shows that both `ulabel` and `elabel` directly use `NE.fromList` without checking if the list is indeed empty.
Best to add empty list check before constructing those labels?

I could add the change myself, but what is the behaviour you prefer? Raising custom exception on empty label?

**Comment by mrkkrp** [comment]
I think in this case simple `error` is enough (this is what `NE.fromList` uses anyway), it's a programmer error and these helpers are for testing anyway, so creating a custom exception for this looks like an overkill to me.

Please go ahead with the PR! :)

**Comment by mrkkrp** [comment]
You could do something like this:

```
error "Text.Megaparsec.Error.Builder.elabel: empty label"
```
