### ISSUE TITLE
Adding streaming (IO) to megaparsec

### ISSUE THREAD

**Issue by rehno-lindeque** [mrkkrp/megaparsec#332]
Hi, I'm interested in taking a stab at implementing proper streaming inside of megaparsec. In other words, I'd like to replicate attoparsec's [feed](http://hackage.haskell.org/package/attoparsec-0.13.2.2/docs/Data-Attoparsec-ByteString.html#v:feed) or something equivalent to it.

Have you given any consideration to what something like this could theoretically look like in megaparsec? I'm rather apprehensive about the implications for backtracking and discarding old chunks (without losing backtracking). Also on how to represent the stream and state, handling end-of-chunk input versus end-of-stream input etc.

Sketching something similar to `feed` from attoparsec results in:

```haskell
data ParseProgress e s m a
  = IncompleteParse (s -> m (State s,  Either (ParseErrorBundle s e) a))
  | CompletedParse (State s, Either (ParseErrorBundle s e) a)

initParseProgress
  :: ParsecT e s m a
  -> ParseProgress e s m a
initParseProgress = _

feedParser
  :: Monad m
  => ParseProgress e s m a   -- ^ Initial parser or incomplete parse result
  -> s                       -- ^ Additional input to feed
  -> m (ParseProgress e s m a)
feedParser = _
```

But obviously this, by itself, is still rather naive, and possibly sub optimal as an api.

I've begun to wonder whether I'd need to / be able to wrap some monad transformer around `ParsecT` with an alternative instance of `MonadParsec` in order to get at the internals like ap and bind without slowing things down in the original implementation. (Still working to absorb how things work at the moment...).

It also occurred to me that `ParsecT` already provides `MonadIO` and `updateParserState`, which made me think that some kind of `yield` function in the api might be possible instead of feeding input to it externally. However, there's still remaining issues for backtracking and end-of-input. Also, I'm not entirely sure how people would want this to look for pipes / conduit / io-stream / etc, since that looks rather different to attoparsec.

Sorry, I hope that is not too much rambling. I wanted to see if you already had some idea of what direction you would want this to go (if anywhere).

**Comment by mrkkrp** [comment]
The feature would be good, definitely. I'm sorry, but I simply don't have time to see how this can be done right now, but I'll add this to my todo list. Megaparsec is not designed for incremental parsing, so it may be tricky to achieve incrementality without making it slower.

`stateInput` is dropped as we go, but there is also `PosState` which typically retains the input. If we're parsing chunk by chunk, that shouldn't be too bad.

**Comment by mrkkrp** [comment]
I'll try to take a look maybe next weekend. I have literally only few free hours per week and don't get to do much open source, but this should change in a month or so.

**Comment by mrkkrp** [comment]
OK, I managed to look at this a bit today. We'd need to be able to produce a similar function which can take more input and then produce result. Presumably adding one more continuation inside of `ParsecT` could allows us have it.

Then there appears to be two modes of operation:

* Report "unexpected end of input, expecting X"
* or return result indicating incomplete input.

Then, the API should be changed, or new API introduced to allow to have at least three possible outcomes: success, parse error, incomplete input.

All the primitives should be also changed to use the new continuation and be able to resume parsing. The parsing state and stuff will be suspended in a closure so perhaps theoretically it could work.

You can try if you're crazy enough, but the performance will be probably worse and the code will be quite messy in the end. I don't know if we really want this in Megaparsec. I warned you, so don't blame me if you end up spending lots of time working on this and in the end it won't get in the library :-D

**Comment by rehno-lindeque** [comment]
Oh thank you very much! I'm on vacation myself, but planning to try it out sporadically. I don't mind even just working on a prototype to test the viability of it.

**Comment by rehno-lindeque** [comment]
I'm more or less just getting started exploring this.

> Presumably adding one more continuation inside of ParsecT could allows us have it.
> 
> Then there appears to be two modes of operation:
> 
> * Report "unexpected end of input, expecting X"
> * or return result indicating incomplete input.

Just some notes (not sure whether this is already clear to you):

`ParsecT` would necessarily need to take a form similar to 

```haskell
newtype ParsecT e s m a = ParsecT
  { unParser :: {- .... -} -> s -> m b
  }
```

...and each continuation would need to end in `s -> m b` for this to work. *(unless an end-of-input token is used as I mention down below)
 
```haskell
(a -> State s   -> Hints (Token s) -> m b) -- consumed-OK
```

E.g. For the "consumed-OK" case, consider `many (char 'x')`. It's ambiguous whether the parse is going to be complete at the end of the chunk without peeking at the following chunk. 

That is... unless megaparsec introduced an artificial end-of-input token, and parsers like `many` tests for it. Then one could have a "consumed-OK" continuation as well as a "consumed-incomplete" continuation.

**Comment by mrkkrp** [comment]
What is the status of this? Should we close?

**Comment by rehno-lindeque** [comment]
Yes, sorry @mrkkrp but I had to step away from it for a time and lost all the mental context needed to solve the remaining issues. It may be more complex than it's worth.

**Comment by rehno-lindeque** [comment]
If anyone did want to look at this again, I'll leave these (very rough) attempts here for reference:

* https://github.com/rehno-lindeque/megaparsec/compare/master...rehno-lindeque:experiment-cont2
* https://github.com/rehno-lindeque/megaparsec/compare/master...rehno-lindeque:experiment-cont3
* https://github.com/rehno-lindeque/megaparsec/compare/master...rehno-lindeque:experiment-cont6
