### ISSUE TITLE
Add non-greedy versions of some and many

### ISSUE THREAD

**Issue by anchpop** [mrkkrp/megaparsec#333]
This is a very common need. Imagine wanting to translate the regular expression `start.+?end` into megaparsec - currently, this is an annoying hassle. Not only that, but it's a common need as well! Imagine trying to extract multiline C comments or HTML tags or many other situations.

My current usecase is making a markdown clone, so I'm trying to parse`3*4` into `[PureText "3*4"]` but `3*4*` into `[PureText "3", Emphasis(PureText "4")]`. I can't seem to think of a way to do this that wouldn't be made dramatically simpler with the addition of non-greedy `some`.

**Comment by recursion-ninja** [comment]
The functionality you're requesting doesn't seem too onerous to implement with the given combinators. First try to parse emphasized text, then if that failed try to parse non-emphasized text. Backtracking is required if a `'*'` character is encountered, so we must use the `try` combinator. 

```
nonGreedy = many $ try emphasis <|> textual
textual = PureText <$> some anySingle
emphasis = single  '*'
         *> (Emphasis . PureText <$> some (anySingleBut '*')) 
         <* single '*'
```

Making explicit the order in which possible parsing results are tried and how and when backtracking is performed is the current library philosophy. I suspect that the correct precedence and backtracking policies of these are likely different for everyone's parsers and may be difficult to generalize. I could be wrong though.

**Comment by anchpop** [comment]
recursion-ninja, thanks! But how flexible is the technique you use? How difficult would it be to modify it for slightly different use-cases, like not breaking emphasis on backslash-escaped asterisks?

**Comment by mrkkrp** [comment]
You also may be interested in this project:

https://github.com/mmark-md/mmark

Parsing Markdown correctly is not an easy task, with any library, let me warn you :)

**Comment by anchpop** [comment]
Luckily I don't need to parse it accurately, this is just a bit of a learning exercise for me

**Comment by mrkkrp** [comment]
Can we close this or is there anything else to discuss?

**Comment by anchpop** [comment]
If the consensus is that non-greedy combinators would not be a useful/necessary/idiomatic addition, then yes

**Comment by recursion-ninja** [comment]
@mrkkrp is *very* correct in stating that writing a markdown parser is difficult. Per @anchpop's request, I have attempted to demonstrate how the above example would be extended to include a `Bold` text parsing functionality.

```
-- First try to parse the bold segment, 
--   it is the most constrained with '**', 
--     backtrack on failure
-- Next try to parse the emphasis segment, 
--   it is the second most constrained with '*', 
--     backtrack on failure
-- Lastly try to parse "raw" textual segments, 
--   on failure the entire parse was a failure.
nonGreedy = many $ try outerBold <|> try outerEmphasis <|> textual

-- This can have '*' in it.
textual = PureText <$> some anySingle

-- This can't have '*' in it
restrictedTextual = PureText <$> some anySingleBut '*'

-- This can have '*' in it, but not two that are adjacent "**".
veryRestrictedTextual = PureText <$> some anySingle 
                                  <*  notFollowedBy (single '*' *> single '*')

outerEmphasis = single  '*'
         *> (Emphasis <$> some (try innerBold <|> restrictedTextual) 
         <* single '*'

innerEmphasis = single  '*'
         *> (Emphasis <$> restrictedTextual
         <* single '*'

outerBold  = single  '*'
         *> single  '*'
         *> (Bold <$> some (try innerEmphasis <|> veryRestrictedTextual) 
         <* single '*'
         <* single '*'

innerBold =   = single  '*'
         *> single  '*'
         *> (Bold <$> veryRestrictedTextual) 
         <* single '*'
         <* single '*'
```

As you can see in the above example, a combinatorics explosion has started. This is because markdown is not a nice, recursively defined grammar. We can have: 
 * A bold segment in an emphasized section
   ✓ `Emphasis [Bold Textual]`
 * An emphasized segment inside a bold section
   ✓`Bold [Emphasis Textual]`
  * But not a bold segment inside an emphasized segment inside an another bold segment.
   ✗`Bold [Emphasis [Bold Textual]]`
  * Nor an emphasized segment inside a bold segment inside another emphasized segment.
   ✗`Emphasis [Bold [Emphasis Textual]]`

This markdown specification requires us to explicitly parse the inner and outer bold/emphasis segments differently because their internal sub-components are different. Again we do this with explicit precedence being used with the `(<|>)` combinator and note when backtracking must be used with the `try` combinator.

All this being said, markdown is a very gruesome grammar to parser. i don't believe that these parsing conditions are the norm (in my anecdotal experience). I could be wrong about this, I have a sample size of 1.

I'm not sure what a non-greedy combinator would look like or how it would interact with the greedy combinators. If you have some more technical input on how the non-greedy combinator would work semantically, there might be some use cases that weren't immediately apparent to me.

**Comment by anchpop** [comment]
@recursion-ninja, I managed to get it working without a combinatoric explosion:

```haskell
anyCharNotFollowedBy :: [String] -> Parser Char
anyCharNotFollowedBy stringsThatCantFollow = do
    nextChar <- lookAhead $ try anyChar
    if nextChar == '\\'
        then do 
            anyChar
            anyChar
        else do
            for_ stringsThatCantFollow (notFollowedBy . string)
            anyChar

-- top level parser
markdownNodesP :: Parser [MarkdownNode]
markdownNodesP = do
    nodes <- some (markdownNodeP allOptions)
    pure $ condenseTextual nodes

markdownNodeP :: Set FormatOption -> Parser MarkdownNode
markdownNodeP options = do
    foldl1Def empty (<|>) $ formatsToCombinator options) <|> try (textualP formatMarkers) <|> try (textualP formatEndingMarkers
    where 
        removedOptions = allOptions \\ options 
        formatStartingMarkers = map formatStart $ toList options
        formatEndingMarkers = map formatEnd $ toList removedOptions
        formatMarkers :: [String]
        formatMarkers = formatStartingMarkers ++ formatEndingMarkers




textualP :: [String] -> Parser MarkdownNode
textualP formatMarkers = do
    text <- some . try . anyCharNotFollowedBy $ formatMarkers
    pure . Textual . T.pack $ text


emphasisP :: Set FormatOption -> Parser MarkdownNode
emphasisP options = do
    _ <- string (formatStart currentOption)
    innerNode <- some . markdownNodeP . delete currentOption $ options
    _ <- string (formatEnd currentOption)
    pure $ Emphasis (innerNode)
    where currentOption = EmphasisOption

strongP :: Set FormatOption ->  Parser MarkdownNode
strongP options = do
    _ <- string (formatStart currentOption)
    innerNode <- some . markdownNodeP . delete currentOption $ options
    _ <- string (formatEnd currentOption)
    pure $ Strong (innerNode)
    where currentOption = StrongOption



-- utility functions
data FormatOption = StrongOption | EmphasisOption deriving (Eq, Ord, Read, Show)
allOptions :: Set FormatOption
allOptions = fromList [StrongOption, EmphasisOption]

formatStart :: FormatOption -> String
formatStart StrongOption = "**"
formatStart EmphasisOption = "*"

formatEnd :: FormatOption -> String
formatEnd StrongOption = "**"
formatEnd EmphasisOption = "*"

formatToCombinator :: FormatOption -> (Set FormatOption -> Parser MarkdownNode)
formatToCombinator StrongOption = strongP
formatToCombinator EmphasisOption = emphasisP

formatsToCombinator :: Set FormatOption -> [Parser MarkdownNode]
formatsToCombinator options =
    map (try . ($ options) . formatToCombinator) (toList options)

    
condenseTextual :: [MarkdownNode] -> [MarkdownNode]
condenseTextual [] = []
condenseTextual nodes = foldr (\x acc -> case x of
                                            Strong t -> (Strong $ condenseTextual t):acc
                                            Emphasis t -> (Emphasis . condenseTextual $ t):acc
                                            Strikethrough t -> (Strikethrough . condenseTextual $ t):acc
                                            Underscore t -> (Underscore . condenseTextual $ t):acc
                                            _ -> prependNodeToList x acc) [] nodes

prependNodeToList ::  MarkdownNode -> [MarkdownNode] -> [MarkdownNode]
prependNodeToList x [] = [x]
prependNodeToList (Textual t) ((Textual t'):xs) = (Textual $ t <> t'):xs 
prependNodeToList x xs = x:xs
```
