### ISSUE TITLE
What happened to `parseErrorPretty'`?

### ISSUE THREAD

**Issue by jwiegley** [mrkkrp/megaparsec#338]
In megaparsec 7.x, there is no longer a `parseErrorPretty'` function, and `parseErrorPretty` only shows `offset=X:` rather than a source line and context. Are users of megaparsec expected to roll their own context display function? Did the source display code from 6.x move into another module?

**Comment by mrkkrp** [comment]
This should answer the question: https://markkarpov.com/post/megaparsec-7.html#parse-errors-story

**Comment by TikhonJelvis** [comment]
Going from `parseErrorPretty` to `errorBundlePretty` was the biggest thing I had to change when upgrading my own parsing code to Megaparsec 7.

Is there a guide somewhere that lays out the changes between 6 and 7 and how to migrate?

**Comment by mrkkrp** [comment]
There is only that blog post, in most cases the migration should be straightforward (just replace `ParseError` with `ParseErrorBundle` and that's it). For more involved cases, it depends. If you have `ParseError` you can add it into `ParseErrorBundle` you get in the end of parsing and display the whole thing when necessary.

**Comment by mrkkrp** [comment]
> How do I determine what these should be at parse time?

You do not need to do that at parse time.

OK, if I understand correctly, you can create `ParseState` at the beginning of parsing similar to [how it's done here](https://github.com/mrkkrp/megaparsec/blob/master/Text/Megaparsec.hs#L269). This will give you `ParseErrorBundle` without errors basically. Then when you have `ParseError` you just keep it (it has offset inside and that's all you need to remember for an error) and when you need to display it you just plug that `ParseError` into `ParseErrorBundle` and display it with `errorBundlePretty`. That function will automatically locate correct line of input based on offsets from `ParseError`s, etc, etc, and display things nicely.

**Comment by jwiegley** [comment]
I don't have a ParseError, though. I use `getSourcePos` to capture the current parse position before and after parsing a construct. Then I save this in an annotation along with the construct. Later, when evaluation fails at this point in the tree, I report the "range" of the construct to indicate to the user where the problem might be. So, it's not a ParseError at all, but an evaluation error relative to a parsed entity. I'm trying to use megaparsec to report the source location nicely.

**Comment by mrkkrp** [comment]
All right, actually you could (ab-)use the existing machinery for your purposes.

* Store offset and length of span instead.
* Then you can construct a `ParseError` with custom component rendering what you want to present to the user, [this method](https://hackage.haskell.org/package/megaparsec-7.0.4/docs/Text-Megaparsec-Error.html#v:errorComponentLen) controls length of highlighted span.
* Insert it into `ParseErrorBundle` and display it.

Voilà! Well, this is roughly what I would do.

**Comment by jwiegley** [comment]
Ok, how do I get the current offset? Here's what I have now (which isn't working):

```haskell
annotateLocation :: Parser a -> Parser (Ann SrcSpan a)
annotateLocation p = do
  st  <- getParserState
  let begin = pstateSourcePos (statePosState st)
  res <- p
  end <- getSourcePos
  pure $ Ann (SrcSpan begin end (pstateOffset (statePosState st))) res
```

**Comment by mrkkrp** [comment]
How about:

```haskell
annotateLocation :: Parser a -> Parser (Ann SrcSpan a)
annotateLoctaion p = do
  begin <- getOffset
  res <- p
  end <- getOffset
  pure $ Ann (SrcSpan begin end) res -- SrcSpan should be adjusted a bit I guess to store offsets
```

Or `SrcSpan` could contain offset where thing begins and length directly...

**Comment by jwiegley** [comment]
Well, I need the offset, but I also need to know which file it occurred in, since the constructs within a tree may come from many different place. Is there a cheaper way to get "just the file" than `getSourcePos`?

**Comment by jwiegley** [comment]
There's also the problem now of saving that `PosState` somewhere, and making sure it reaches the same place that the related constructs do at error reporting time during evaluation.

At this point, I'm beginning to think it's easier to write my own line reporting library, which only needs the file, start/end lines and columns, and span of interest.

**Comment by mrkkrp** [comment]
> Well, I need the offset, but I also need to know which file it occurred in, since the constructs within a tree may come from many different place. Is there a cheaper way to get "just the file" than getSourcePos?

File name do not change, so you can just get current state and then use `sourceName . pstateSourcePos . statePosState` to get it.

> There's also the problem now of saving that PosState somewhere, and making sure it reaches the same place that the related constructs do at error reporting time during evaluation.

I mentioned this several times, you don't need to do anything. Just construct `PosState` when you start parsing. Megaparsec will traverse and locate everything by itself given offsets you provide. `PosState` **is not parser state when error happened**. Try to read source code of `getSourcePos` and see `reachOffset` and friends to understand what is going on.

**Comment by jwiegley** [comment]
What I mean is, once I get this initial `PosState`, prior to parsing, it needs to be passed down to where evaluation detects and error and needs to report the problem. I can't just stick a `PosState` into the construct annotation, however, because it's not `Hashable`. So I end up with two pieces of information, held in two places, that must be consistent brought together at the right time.

Since I have file/line/col in hand already, I'll create a solution that uses this information alone. It's all I need, really, and it will make the code immune to further infrastructure changes like this in future.
