### ISSUE TITLE
An embedded tutorial

### ISSUE THREAD

**Issue by neongreen** [mrkkrp/megaparsec#34]
Megaparsec might be able to replace Parsec much faster if it has a tutorial (not just a list of distinctions between `parsec` and `megaparsec`) – this way instead of everyone saying “okay there's Megaparsec but maybe use Parsec instead because all tutorials cover it and they aren't that different” we might end up with “okay there's Parsec but Megaparsec comes with an extensive tutorial so look at it instead”. So, I offer to write such a tutorial, and then we could put it in `Text.Megaparsec.Tutorial`.

(The reason I'm making this an issue instead of just silently writing it and then making a pull request is that I don't want a repetition of the situation with [Tekmo and lens tutorial](https://github.com/ekmett/lens/pull/552). So, if e.g. @mrkkrp has strong opinions on how it should be written, it would be better to hear them early on instead of ending up with something written in [my usual idiosyncratic style](http://artyom.me/aeson) and then having the pull request rejected.)

**Comment by mrkkrp** [comment]
@neongreen, Great idea. I was thinking about creating a web page (we can use GitHub project pages to host it) describing Megaparsec. This would contain manual, instructions how to switch for Parsec users, etc. I plan to address the need for this “auxiliary” material after initial release of the library.

As I understand you're proposing something built-in into source. This is interesting, although I have to admit (to my shame) that I see such thing for the first time. I don't have anything against it and thus such a pull request will be probably merged, not rejected. You can start working on the tutorial, but I encourage you open pull request earlier so I and other people can comment as it progresses and result won't be something surprising.

**Comment by neongreen** [comment]
> built-in into source

Yep, like [the pipes tutorial](https://hackage.haskell.org/package/pipes-4.1.6/docs/Pipes-Tutorial.html) that everyone seems to love.

**Comment by mrkkrp** [comment]
@neongreen, Do you have any plan of things/sections to include in this tutorial?

**Comment by neongreen** [comment]
* a tiny introduction to monadic parsers
* writing some parser (don't know what yet)
* adding `<?>` stuff to it (+ what error messages can be expected in which situations)
* most `Alternative` combinators must be mentioned at least in passing
* parsing a language (gotta mention `identGuard` at some point)
* backtracking state + warnings or something else that uses `WriterT` + `ParsecT IO` or something (not long explanations, just something like “look what kind of thing you might want to do and here's how to do it”) (while I'm at it, there should definitely be a FAQ section at the end)
* speeding up parsers (if you've got any tricks to share, please do)

I will only point at `Text.Megaparsec.Expr` instead of explaining it, but then the example in the module should be made compilable right from the start (currently it's not). Perhaps there should also be a ready-to-hack-on example in `Text.Megaparsec.Lexer`.

I'm not sure where should the border between “this is something that should be explained in the library documentation” and “this is something that the user can ask on IRC or wherever” lie, but I'm pretty sure it's further than most library authors think it should be.

**Comment by winterland1989** [comment]
First, congratulations for all your work! I'm writing a toy language compiler when i came across issues with parsec, and then i found here.

The old parsec actually doesn't have any good tutorial included, i always look for something like `language-lua`, `language-ecmascript` and follow the packages, so i guess we can have an example on how to construct a simple toy language, and focus on basic concept.

That's just my personal idea, i would say the moment i'm starting writing parsers is the moment i understand basic LL(1) parser concept and the `try` backtrace combinator.

**Comment by mrkkrp** [comment]
@winterland1989, Hi, I also like the idea of gradually building something like this learning things along the way. There probably will be several tutorials. I intend to write one (not embedded, as separate article), but first I want to see what @neongreen is up to.

**Comment by neongreen** [comment]
Re: several tutorials: I don't know how good Write Yourself A Scheme In 48 Hours is, but people keep recommending it to others, so I wonder whether spending some effort updating it to use Megaparsec could be a good idea.

**Comment by mrkkrp** [comment]
@neongreen, Yeah, I remember I liked something called “Parse simple imperative language” as well. Many things can be easily converted I think.

**Comment by mrkkrp** [comment]
I would like to include this in Megaparsec 4.1.0, which is next version of the library. I've added milestone to this issue.

**Comment by mrkkrp** [comment]
@neongreen, Can you report your progress on this?

**Comment by mrkkrp** [comment]
@neongreen, Do you still intend to write the tutorial? There is no rush, I just need to know status of this issue.

**Comment by neongreen** [comment]
@mrkkrp 

Ouch, sorry. Yes, I still intend to write the tutorial. There isn't much progress, but I will push something in a couple of days.

**Comment by PierreR** [comment]
My current biggest puzzlement is the fact that migrating from `parsec` to `megaparsec´ (almost) means dropping `parsers´ somehow. 

Can you keep both without writing boilerplate. Here is [an example.](https://github.com/bartavelle/language-puppet/commit/74fb7f6dcfacd3139fd785e8f3de7d9657caf095)

**Comment by mrkkrp** [comment]
@PierreR, dropping `parsers` can be good. One downside of `parsers` that is depends on `attoparsec` and `parsec`, so by using it you you depend on useless code. In ideal world `attoparsec` and `parsec` should depend on `parsers` not the other way around. Megaparsec has modest dependencies and should be self-sufficient.

**Comment by PierreR** [comment]
@mrkkrp I understand the downside of `parsers` but I would argue it is still quite useful ;-) I will try to figure out out difficult it would be in the `language-puppet` example (link available in my first post). If you have some tips, please let me know.

**Comment by PierreR** [comment]
A part from my specific use case, I meant to say that it would be nice if the tutorial helps the migration from `parsers&parsec` to `megaparsec` only. I have the feeling that it is quite easy to convert a `parsec` only project into `megaparsec` but for any non trivial parsing `parsers` will be used as well.

**Comment by mrkkrp** [comment]
Closing the issue, discussion should continue in #58.
