### ISSUE TITLE
Megaparsec with Data.Text

### ISSUE THREAD

**Issue by krajoli** [mrkkrp/megaparsec#340]
Are there any plans of making Megaparsec work with Data.Text?

**Comment by TikhonJelvis** [comment]
Megaparsec already supports parsing `Text`. 

You can use Megaparsec with any type that's an instance of the [`Stream`](http://hackage.haskell.org/package/megaparsec-7.0.4/docs/Text-Megaparsec-Stream.html#t:Stream) typeclass, which includes the following types by default:

  * `String`
  * lazy `Text`
  * strict `Text`
  * lazy `ByteString`
  * strict `ByteString`

Have you had specific issues or errors trying to work with `Text`?

**Comment by krajoli** [comment]
I was expecting a module named Text.Megaparsec.Text.Lexer similar to Text.Megaparsec.Char.Lexer. Is there a README somewhere on how to use a non String lexer? Sorry did not find a suitable forum to post this query so had to open an issue.

**Comment by TikhonJelvis** [comment]
Spelling things out explicitly for anyone who finds this issue in the future: the functions in `Text.Megaparsec.Char` work with any type `s` that is an instance of `Stream` with `Char` tokens (that is, `Token s` is `Char`). That is what the constraints on the functions specify:

```
newline :: (MonadParsec e s m, Token s ~ Char) => m (Token s)
```

The `Stream` constraint comes from the definition of `MonadParsec`, and the `Token s ~ Char` line explicitly specifies that the tokens have to be `Char`.

These functions will work with `String` as well as strict or lazy `Text`.

`Text.Megaparsec.Byte` and `Text.Megaparsec.Byte.Lexer` are similar except they require `Token s` to be `Word8` and work with strict or lazy `ByteSting`s.

**Comment by AlistairB** [comment]
Hi,

It seems like it mostly does, except that `Control.Monad.Combinators` combinators will sometimes force it to use `String`. Not sure if this is unavoidable/desirable for some reason.
