### ISSUE TITLE
[Question] Type for `manyUnaryOp = foldr1 (.) <$> some singleUnaryOp`

### ISSUE THREAD

**Issue by AllanWang** [mrkkrp/megaparsec#341]
May I ask what the type is for 

```
manyUnaryOp = foldr1 (.) <$> some singleUnaryOp
```

?

It's in the docs for `makeExprParser`, and I'm still a bit new to haskell so I'm not sure how to use it.

**Comment by mrkkrp** [comment]
`singleUnaryOp` should be something like `a -> a` so its domain and codomain match for this to work. Type of `some singleUnrayOp` will be `Parser [a -> a]` then, and after folding we get `Parser (a -> a)`.

**Comment by AllanWang** [comment]
I guess my question is what `Parser(a -> a)` is, since all my parsers are `Parser a`. May I get an example for something like c pointers? (any number of `*`)

**Comment by mrkkrp** [comment]
It is a parser which returns a function as its result. If you have `Parser String` then once you run that parser you get `String`, similarly, once you run something like `Parser (String -> String)` you get a function which you can apply to a `String` and get a `String` in the end.

If you define your AST like this:

```haskell
data MyAST
  = Foo
  | Bar
  ...
  | Dereference MyAST
```

Then the type of `Dereference` is `MyAST -> MyAST` (you give it part of your AST like maybe `(1 + my_ptr)` and it returns AST representing `*(1 + ptr)`. So your parser is going to have the type `Parser (MyAST -> MyAST)`, which means that you'll parse a function which can add layer(s) of dereferencing to given `MyAST` value.

**Comment by AllanWang** [comment]
Thanks. I ended up figuring out an example:

```
manyUnaryOp :: String -> Prefix -> Parser (Expr -> Expr)
manyUnaryOp s m = foldr1 (.) <$> some (wrap s m)
wrap :: String -> Prefix -> Parser (Expr -> Expr)
wrap s m = do
  void (symbol s)
  return (Unary m)
example :: Parser (Expr -> Expr)
example = manyUnaryOp "!" Not
```
