### ISSUE TITLE
Access to the parser state on error

### ISSUE THREAD

**Issue by KeesBleijenberg** [mrkkrp/megaparsec#342]
I run a megaparsec parser in a State monad.

```haskell
type VWParser e a  = StateT ParserState (ParsecT e String Identity) a
data VWError = VWError String deriving (Eq, Data, Typeable, Ord, Read, Show)
instance ShowErrorComponent VWError where showErrorComponent (VWError msg) = "VW-error: " ++ msg   -- Necessary for any pretty printing and tests in ghci??
type MyParserState =  MyParserState {warnings :: [Warning]}

parseVWs :: String -> ParseVWResult  
parseVWs toParse = 
    let ps  = MyParserState {
                    warnings=[]
              }
    in  case runParser (runStateT vwParser ps) "" toParse of 
            Right (vws, resultParserState) -> ....
            Left  e -> .....
```
            
If I run parseVWs and I get a error at line 10, I want to show the error and (!) the warnings added to the parserstate in lines 1..9
But if the parse result is a left, I don't have access to the MyParserState. I could run vwParser line by line and collect the warnings, but that would mess up the row info in functions like parseErrorPretty. What can I do?

Kees

**Comment by mrkkrp** [comment]
A thing to note here is that wrapping `ParsecT` in `StateT` gives you backtracking state, while putting `StateT` into `ParsecT` gives you non-backtracking state. If the distinction is not important in your case, you could use this monad for parsing:

```haskell
type Parser e a = ParsecT e String (State ParserState) a
```

Then when you need to run it you first use [`runParserT`](https://hackage.haskell.org/package/megaparsec-7.0.4/docs/Text-Megaparsec.html#v:runParserT) and get `State ParserState (Either (ParseErrorBundle String e) a)`, which you can then run with [`runState`](https://hackage.haskell.org/package/mtl-2.2.2/docs/Control-Monad-State-Strict.html#v:runState) to get both `ParserState` and `Either` thing out of it.

Another approach would be to actually return parsed warnings as part of normal output. For example, if you parse, say, a `Node` then you add an additional field to it indicating warnings that happened while parsing the node.

**Comment by KeesBleijenberg** [comment]
A lot of very usefull suggestions. Thanks!

**Comment by mrkkrp** [comment]
If you don't mind, I'll close this then.

**Comment by KeesBleijenberg** [comment]
Hi Mark,

A question, just before closing:

You suggested: .... Another approach would be to actually return parsed warnings as part of normal output. For example, if you parse, say, a `Node` then you add an additional field to it indicating warnings that happened while parsing the node.

If I understand correctly, you don't want to use a state monad for the warnings, but return the warnings as part of the result. When I get a error (a Left) I don't have access to that result with the warnings. 

Kees

**Comment by mrkkrp** [comment]
> If I understand correctly, you don't want to use a state monad for the warnings, but return the warnings as part of the result. When I get a error (a Left) I don't have access to that result with the warnings.

Yes true, but I think it makes sense to show just errors if they are present, and when there are no errors, then you could show warnings. Anyway, it's just a possible solution.
