### ISSUE TITLE
Why does `reachOffset` return two `SourcePos`s?

### ISSUE THREAD

**Issue by seagreen** [mrkkrp/megaparsec#344]
It returns a `(SourcePos, String, PosState s)` which contains one `SourcePos` as the first element of the tuple, and another as the `pstateSourcePos` field of `PosState`.

Will these ever be different, and if not can the function be changed to return a `(String, PosState s)`?

**Comment by mrkkrp** [comment]
This is a good catch. I just checked the source code and indeed, they seem to be always the same. We could change the signature in next major version of the library (no, I don't know when that'll happen :) ).

**Comment by seagreen** [comment]
Sounds good. Definitely agree there's no rush to fix this, it's not really hurting anything.
