### ISSUE TITLE
Move docs and tutorials to github

### ISSUE THREAD

**Issue by Recognized** [mrkkrp/megaparsec#347]
markkarpov.com is not available.

**Comment by mrkkrp** [comment]
What do you mean “not available”? I can access the site. If you’re referring to availability of source code, then it’s on GitHub, here: https://github.com/mrkkrp/markkarpov.com.

**Comment by Recognized** [comment]
Sorry, I was looking for tutorials on megaparsec and all links that I've found lead to https://markkarpov.com, which I cannot access using my internet provider. But using a proxy solved this issue.

**Comment by mrkkrp** [comment]
Huh, that's strange. I guess my site has become too controversial for Russia!
