### ISSUE TITLE
Creating error messages from `throwError`

### ISSUE THREAD

**Issue by AllanWang** [mrkkrp/megaparsec#349]
I noticed in https://github.com/mrkkrp/megaparsec/pull/152/files that there seems to be support for `throwError`.

I was wondering if there is an easy way to throw error messages (similar to `<?> msg`), when using non exhaustive pattern matching.

For instance, if I have a function `Int -> Parser a`, where I only want to handle some integers, I'd need to either make my own type to make the matching exhaustive (`t -> Parser a`), or check beforehand using `oneOf` and then use `undefined` or `error`. Is there a better way of doing this?

**Comment by mrkkrp** [comment]
`throwError` will work independently, it'll be like another way to fail: not very useful I guess. This is obvious if you check the instance:

```haskell
instance (Stream s, MonadError e' m) => MonadError e' (ParsecT e s m) where
```

`e` and `e'` are different types!

> I was wondering if there is an easy way to throw error messages (similar to `<?> msg`), when using non exhaustive pattern matching.

The `(<?>)` does not throw anything. It just gives a name, "label", to the thing it's attached to.

> Is there a better way of doing this?

Depends what that `Int` means. If it comes as a result of other monadic action, then I'd use something from [this section](https://markkarpov.com/megaparsec/megaparsec.html#how-to-signal-a-parse-error).

In general, I see you're a bit confused, so this tutorial may be helpful: https://markkarpov.com/megaparsec/megaparsec.html. If you manage to read it all, most of your questions will be answered.

**Comment by AllanWang** [comment]
Thanks. Using `customFailure` solved it
