### ISSUE TITLE
Is there any reason for the `Tokens` type family

### ISSUE THREAD

**Issue by tysonzero** [mrkkrp/megaparsec#353]
It seems like `Tokens a` is always just equal to `a`, is this additional (seemingly unused?) flexibility worth the complexity and worsened type inference?

**Comment by mrkkrp** [comment]
The reason is explained here: https://markkarpov.com/megaparsec/megaparsec.html#character-and-binary-streams.

> is this additional (seemingly unused?) flexibility worth the complexity and worsened type inference

It's hard to tell.

**Comment by mrkkrp** [comment]
Closing because nothing is happening here.
