### ISSUE TITLE
Returning multiple parse errors in a ParseErrorBundle

### ISSUE THREAD

**Issue by digama0** [mrkkrp/megaparsec#359]
In the changelog for v7.0, when `ParseErrorBundle` was introduced, it says:

> By default there will be only one `ParseError` in such a bundle, but it's possible to add more parse errors to a bundle manually.

But there doesn't seem to actually be any easy way to manually collect and report multiple non-fatal errors during parsing, which if I understand it is the whole point of `withRecovery`. Currently I'm doing the following:

```haskell
type ParsecST e s m = ParsecT e s (StateT [ParseError s e] m)

-- this is defined but private in Text.Megaparsec
initialPosState :: String -> s -> PosState s
initialPosState name s = PosState
  { pstateInput = s
  , pstateOffset = 0
  , pstateSourcePos = initialPos name
  , pstateTabWidth = defaultTabWidth
  , pstateLinePrefix = ""
  }

runParserST :: forall m s e a. Monad m =>
  ParsecST e s m a -> String -> s -> m (Either (ParseErrorBundle s e) a)
runParserST p n s = merge <$> runStateT (runParserT p n s) [] where
  merge :: (Either (ParseErrorBundle s e) a, [ParseError s e]) ->
      Either (ParseErrorBundle s e) a
  merge (a, []) = a
  merge (Right _, e : es) = Left (build es e [] (initialPosState n s))
  merge (Left (ParseErrorBundle (l :| ls) pos), e : es) =
    Left (build es e (l : ls) pos)
  build :: [ParseError s e] -> ParseError s e ->
    [ParseError s e] -> PosState s -> ParseErrorBundle s e
  build [] l ls = ParseErrorBundle (l :| ls)
  build (e : es) l ls = build es e (l : ls)

logNonFatalError :: Monad m => ParseError s e -> ParsecST e s m ()
logNonFatalError e = lift (modify (e :))
```

But this doesn't really look like user code to me. It would be much nicer if the monad supported a function like `logNonFatalError` for storing a parse error previously collected via `withRecovery`, which would then appear as additional errors in the bundle.

Am I going about this wrong? How do you envision people generating a `ParseErrorBundle` with multiple errors?

**Comment by mrkkrp** [comment]
This is a valid feature request. Indeed, the change in version 7 only gives you `ParseErrorBundle` which can be pretty-printed, etc. But does not give you a standardized way with to collect parse errors.

What you do is OK, it's a possible solution. I do it a bit differently [here](https://github.com/mmark-md/mmark/blob/master/Text/MMark/Parser.hs) but the way bundles are "populated" is essentially the same: you add new stuff after you finished parsing.

**Comment by odanoburu** [comment]
> But there doesn't seem to actually be any easy way to manually collect and report multiple non-fatal errors during parsing, which if I understand it is the whole point of withRecovery. 

I just ran into the same problem while trying to apply the ideas in https://markkarpov.com/megaparsec/fun-with-the-recovery-feature.html to another problem, so I second this request :)

**Comment by mrkkrp** [comment]
I’ll see about this. I want some new features related to parse errors, so maybe it’s time to make version 8 ;)

**Comment by mrkkrp** [comment]
I think we'll need to add a new primitive which will "register" parse errors without affecting parsing. Then at the end we'll need to check those accumulated errors and add them to the collection of parse errors. If parsing ends successfully but the collection of registered errors is not empty, final result should still be a failure.

@digama0 @odanoburu Does it look like a satisfactory solution to you?

**Comment by odanoburu** [comment]
yes! :+1:
