### ISSUE TITLE
Possible Issue with Labels

### ISSUE THREAD

**Issue by JKTKops** [mrkkrp/megaparsec#363]
edit: I still find the below behavior unexpected, however it definitely happens because `guardIndentation` consumes a token. If instead `satisfy` and `token` are wrapped in `try` (which I believe may actually be necessary to get correct behavior out of the hints, so this was a mistake on my part) then expected tokens always appear. If the token consumption means this is expected, feel free to close the issue.

I'm not actually sure that this is unexpected, since the hints for a parser are supposed to be quite volatile. But it was certainly unexpected behavior for me!

I'm working on using `Alex` along with `Megaparsec` to parse Haskell source as part of a for-fun project. The built-in combinators for source location would be "good enough," but since Alex has already consumed all the whitespace it would be rather tiresome to use `lineFold` and intersperse calls to the space consumer inside every parser, since virtually everything can be linefolded. And that interacts quite badly with the possibility that anything that _could_ be linefolded could also be part of an explicit layout context.

Instead, I decided to have `Alex` emit a token whenever a line may need to be checked for indentation (see Haskell Report section 9.3 for details, but not that important). I then wrote my own primitive parsers as follows.

```Haskell
-- From a different file
data Lexeme = Located SrcSpan Token
data Token = ...

-- Parser file
import Text.Megaparsec hiding (Token, satisfy, token)
import qualified Text.Megaparsec as P

satisfy :: (Token -> Bool) -> Parser Lexeme
satisfy f = optional guardIndentation >> P.satisfy (p . unLoc)

guardIndentation = do
  P.token ({- test for `TokIndent` -}) Set.empty
  {- get layout information and use indentGuard -}

token t = satisfy (== t) <?> pprint t
```

The idea is that `guardIndentation` will fail immediately if the next token isn't `TokIndent`, but if it succeeds, then it will perform the indentation check.

When running parsers using `token`, no expected values are shown if (and only if) `guardIndentation` succeeded. For example (`testParser` runs the lexer and then invokes the parser):

```
> testParser (token TokModule) "where"
Left "1:1:
  |
1 | where
  | ^
unexpected `where'
"
```

However:

```
> testParser (token TokModule >> token TokModule) "module where"
Left "1:8:
  |
1 | module where
  |        ^
unexpected `where'
expecting `module'
"
```

So somehow my indentation guard is causing hints to be erased, even though the label should apply after it has already succeeded. If, on the other hand, I define

```
token t = optional guardIndentation >> P.token testTok expected
  where testTok l = if unLoc l == t then Just l else Nothing
        expected = Set.singleton (Tokens (noLocation t :| []))
```

Then hints are not erased.

It's very possible I'm doing something wrong here (outside of using my own layout sensitivity scheme).

**Comment by mrkkrp** [comment]
Sorry for the delay. I usually make a note when I see an issue that I want to reply to later, but in your case I forgot to make such a note.

If you look here: https://github.com/mrkkrp/megaparsec/blob/master/Text/Megaparsec/Internal.hs#L444

You'll see that successful consuption of a token erases the hints unconditionally, hence `memtpy`. This follows from an assumption that a token cannot be zero length. Maybe this assumption is not a good one to make though!

**Comment by JKTKops** [comment]
Yes I figured it worked like this. I switched back to `Parsec` (hopefully only temporarily, until ver. 8) for my project as my custom token type was causing too much headache.

If that assumption were not made, what would an alternative be? I think there would have to either be a backdoor into `eok` or a considerably more involved definition for `Stream` (although there is an open issue that I saw about other possible improvements to `Stream`). On the other hand, this example is unfortunately not a use case for this lack of assumption; that version of the parser would fail when escaping indentation contexts and trying the next one, because the indentation token had been consumed. It needed `try` :)

**Comment by mrkkrp** [comment]
> If that assumption were not made, what would an alternative be?

If we can have a way to tell length of a token (there is a PR for that, but I haven't reviewed it yet), then we could take 0 length tokens into account properly in `pToken`.

> On the other hand, this example is unfortunately not a use case for this lack of assumption; that version of the parser would fail when escaping indentation contexts and trying the next one, because the indentation token had been consumed. It needed try :)

Do you mean to say that with `try` around `guardIndentation` it works as expected?

**Comment by JKTKops** [comment]
The try surrounds the whole parser, not just `guardIndentation`, and then yes it works as expected.

When escaping a layout context, the expected messages from the inner context are erased (in `Parsec`, I'm not sure how `Megaparsec` behaves). For example, the definition for `z` here is acceptable at either indentation 4 or 16. The error would be something to the effect of "expected let binding at indentation 4." But it forgets that "let binding at indentation 16" was also acceptable.
```haskell
let x = do let y = f x
     z = 2
in foo x z
```

(this is not syntactically valid, but the parser will accept this and the compiler will reject the program later.)

But I don't think `Megaparsec` and `Parsec` handle hints in the same way, and it's possible that this isn't happening because of `satisfy`.

**Comment by mrkkrp** [comment]
What I'm going to do is: when I finish the changes for making working with custom streams easier I'll ping you and check with you if those changes help with your code or not.

**Comment by JKTKops** [comment]
Sure! I have the code I wrote for `megaparsec` saved in my repo so I'll be able to try stuff quickly (hopefully).

**Comment by mrkkrp** [comment]
I'm closing this one for now.
