### ISSUE TITLE
Why does Lexer.charLiteral parses single quote?

### ISSUE THREAD

**Issue by suhdonghwi** [mrkkrp/megaparsec#365]
```haskell
charLiteral :: Parser Char
charLiteral = between (char '\'') (char '\'') L.charLiteral
```

I wrote this parser to parse character literal in my language, but the parser above parses `'''` successfully. I expected it to fail because `L.charLiteral` parses according to the grammar rules defined in the Haskell report, and Haskell does not  accept `'''` as character literal.

Why does this happen?

**Comment by mrkkrp** [comment]
This is a good question. Under the hood `charLiteral` uses [`readLitChar`](https://hackage.haskell.org/package/base-4.12.0.0/docs/Data-Char.html#v:readLitChar) which promises, I quote:

> Read a string representation of a character, using Haskell source-language escape conventions, and convert it to the character that it encodes.

However, if we try it on unescaped single quote, it succeeds:

```
>>> Char.readLitChar "'"
[('\'',"")]
```

This could be a bug in `base`, or the documentation should be updated to mention this exception. Do you want to try to open an issue [here](https://gitlab.haskell.org/ghc/ghc/issues)?

In the meantime you could try to look ahead to check for single quote and fail accordingly.

**Comment by mrkkrp** [comment]
Have you opened an issue as I suggested?

**Comment by suhdonghwi** [comment]
I am sorry for being late. I think documentation of Haskell is not wrong, because it mentions that  `readLitChar` reads "string representation of a character". In Haskell, a single quote is allowed in string literal such as `"'"`.

**Comment by mrkkrp** [comment]
I see, let’s close this one then.
