### ISSUE TITLE
Is output of megaparsec parser streaming?

### ISSUE THREAD

**Issue by chshersh** [mrkkrp/megaparsec#367]
This is just a question about how `megaparsec` works. I wasn't able to find a direct answer in the documentation, so I will appreciate a lot if you have time to answer my question!

Consider the following parsers:

```haskell
type Parser = Parsec Void Text

fooParser :: Parser Foo

rootParser :: Parser [Foo]
rootParser = many fooParser <* eof
```

I would like to be able to parse a list of `Foo` in a streaming fashing and feed it to some function

```haskell
processFoos :: [Foo] -> SomeMonad Bar
```

And I would like to avoid storing the whole list of `Foo` in memory, so it can be consumed lazily and, ideally, the parsing also should stop if `SomeMonad` finishes it work earlier.

So, the question is: will this work out of the box? And if not, what can I do to achieve the desired behaviour?

**Comment by mrkkrp** [comment]
Output of parsing indicates also whether parsing succeeded or not. How can you know this before you consumed all input (and built the whole spine of the list)?

If you want to be able to feed chunks of input incrementally, I think the only library that can do it is Attoparsec right now.

**Comment by TikhonJelvis** [comment]
Would it be possible to implement your own `many` combinator that works in a streaming fashion? I'm imagining a function that calls `runParser'` repeatedly, manually passing around the parser state and handling errors in whatever way fits your streaming requirements.

I'm not sure this would work though—it depends on exactly how `runParser'` works with your particular parser, and I don't have a computer handy to play around with the idea.

**Comment by mrkkrp** [comment]
It should be possible. Important pre-requisite would be making sure that the parser inside of `many` is wrapped with `try` so it backtracks on failures so that unconsumed input is available in the next iteration. But then if something just doesn't parse, it will hang?

**Comment by chshersh** [comment]
In my use case, I have a file that contains lines (well, almost, but let's assume for simplicity that this is the case) and I want to parse every line independently one after another and stop on a first parsing error or at the end of the file. I want to assemble a list of `Foo` into a single `Bar` or return failure if parsing failed. I'm not sure about the best way to design a streaming parser. I assume that it should be possible to return a list of things like

```haskell
[Foo1, Foo2, Foo1, Foo3, Foo2, Failure]
```

Where `Failure` is a special marker that indicates that parsing has failed, so, parsing always succeeds and you can observe the failure only after you try to process the list and see this `Failure` constructor.

I'm also aware of the fact that `Parsec` is a monad transformer. So probably it should be possible to use something like `ParsecT (StateT Bar Either a)`, but I assume that this approach comes with performance drawbacks.

**Comment by mrkkrp** [comment]
If I were you, I'd not try to rely on laziness. You could perhaps write a parser for dealing with a single line and then glue everything together with a streaming library.

**Comment by chshersh** [comment]
@mrkkrp That's an interesting solution. Unfortunately, in my case I don't have exactly lines, some items can spawn multiple lines. But I got the answer to my question and I understand `megaparsec` better now. Thanks for your time!
