### ISSUE TITLE
MonadZip ParserT

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [mrkkrp/megaparsec#382]
Is there a way to run two different parsers on the same tokens?

My case is that I want to extract the raw data and parse to a data type to test my serializer. Example:

```DXF
0
SECTION
0
POINT
1
1.0
2
2.0
0
ENDSEC
```
I would then like to write a parser `Parser (ByteString, Point)` that would yield `("0\nPOINT\n1\n1.0\n2\n2.0", Point 1.0 2.0)` then run the point through my serializer to test if it is isomorphic with my parser.

**Comment by mrkkrp** [comment]
Use [`match`](https://hackage.haskell.org/package/megaparsec-7.0.5/docs/Text-Megaparsec.html#v:match).

**Comment by BebeSparkelSparkel** [comment]
Perfect!
