### ISSUE TITLE
Propositions for Megaparsec's site

### ISSUE THREAD

**Issue by mrkkrp** [mrkkrp/megaparsec#39]
I think now we can concentrate on tutorials and other materials. In particular, we can use GitHub project pages to host some useful information related to the project.

Here is what I think such a site should contain:

* Link to GitHub repository (“fork me on GitHub” or something like this).

* Link to Hackage page of the project.

* An article explaining how to switch from Parsec to Megaparsec;

* A couple of tutorials.

If you have propositions, tell me.

----

There is also an idea to edit `README.md` file. It should define Megaparsec not in terms of Parsec, but as something self-sufficient that non-Parsec user can understand. Comparison against Parsec should be moved to dedicated section. It's a good idea to add hyperlinked table of contents at the beginning.

**Comment by mrkkrp** [comment]
I'm currently considering building little site using Hakyll static site generator. The site can be placed in different repository and only ready-for-deployment version will be put in `gh-pages` branch in this repository. Another option is to keep the site entirely outside of this repo.

Another option is to create `tutorial` directory and put tutorials there in plain markdown format.

What do you think?

**Comment by achudnov** [comment]
I think `gh-pages` is fairly reliable, so I'd go with that. A guide for porting code from Parsec 3 to Megaparsec would be a great idea.

**Comment by mrkkrp** [comment]
The site is operational now. Here is the first tutorial: https://mrkkrp.github.io/megaparsec/tutorials/parsing-simple-imperative-language.html
