### ISSUE TITLE
Something wrong in Megaparsec TUTORIAL

### ISSUE THREAD

**Issue by acapi** [mrkkrp/megaparsec#392]
“Catching parse errors in running parser”.

```
xxx.hs:29:62: error:
    • Couldn't match type ‘Token Char’ with ‘Char’
      Expected type: Maybe (ErrorItem (Token Char))
        Actual type: Maybe (ErrorItem Char)
    • In the fourth argument of ‘TrivialError’, namely ‘us’
      In the first argument of ‘parseErrorTextPretty’, namely
        ‘(TrivialError @Char @Void undefined us es)’
      In the first argument of ‘(++)’, namely
        ‘parseErrorTextPretty (TrivialError @Char @Void undefined us es)’
   |
29 |     parseErrorTextPretty (TrivialError @Char @Void undefined us es)    |
```

**Comment by mrkkrp** [comment]
Indeed, it should be `TrivialError @Text @Void ...`. I've pushed a fix for the tutorial. Thanks for reporting this!

**Comment by mrkkrp** [comment]
Just to clarify: the `@Char` type annotation used to be correct for older versions of Megaparsec, but now this type parameter stands for the stream type (`Text` in that case), not just token type (`Char`), so the type application should have been updated accordingly.
