### ISSUE TITLE
How to configure tab size?

### ISSUE THREAD

**Issue by xhliu** [mrkkrp/megaparsec#394]
The default tab size is 8. It differs from my editor setting and thus reports wrong column number for lines with tabs when error. How do I change it now that `setTabWidth` is removed since megaparsec 7.0.0?

Also, why was it removed?

**Comment by mrkkrp** [comment]
It was removed because in the newer versions of Megaparsec the calculation of column and line numbers is done on demand (e.g. when you explicitly request it or when you're pretty-printing the error messages) so changing tab width arbitrarily during the parsing doesn't play with that very well (we would need to remember when and how tab width was changed!).

The solution is to use `runParser'` or `runParserT`` and change tab width in the initial state you provide.

**Comment by xhliu** [comment]
@mrkkrp I tried with megaparsec 8.0.0
```
initialState :: String -> Int -> s -> State s e
initialState src tabWidth s = State
  { stateInput  = s
  , stateOffset = 0
  , statePosState = PosState
    { pstateInput = s
    , pstateOffset = 0
    , pstateSourcePos = initialPos src
    , pstateTabWidth = mkPos tabWidth
    , pstateLinePrefix = ""
    }
  , stateParseErrors = []
  }

runParser' p $ initialState src 2 code
```
`errorBundlePretty` still yields tab size of 8, even though it is set to 2. What am I missing?

**Comment by mrkkrp** [comment]
In what sense `errorBundlePretty` "yields" tab size of 8? Here is a complete program:

```haskell
module Main (main) where

import Data.Void
import Text.Megaparsec
import Text.Megaparsec.Char

initialState :: String -> Int -> s -> State s e
initialState src tabWidth s = State
  { stateInput  = s
  , stateOffset = 0
  , statePosState = PosState
    { pstateInput = s
    , pstateOffset = 0
    , pstateSourcePos = initialPos src
    , pstateTabWidth = mkPos tabWidth
    , pstateLinePrefix = ""
    }
  , stateParseErrors = []
  }

run ::
  Parsec e s a ->
  s ->
  Either (ParseErrorBundle s e) a
run p input = snd $ runParser' p $ initialState "" 2 input

parser :: Parsec Void String Char
parser = do
  space
  char 'a' <* eof

main :: IO ()
main =
  case run parser "\tb" of
    Left bundle -> putStrLn $ errorBundlePretty bundle
    Right x -> print x
```

If I run it with Megaparsec 8.0.0, this is the output:

```
1:3:
  |
1 |   b
  |   ^
unexpected 'b'
expecting 'a' or white space
```

Note that before `b` we have a tab and it is displayed with tab width 2.

**Comment by xhliu** [comment]
Thanks. It is working like a charm and I was looking at the wrong output.
