### ISSUE TITLE
[question] is using getParserState/setParserState safe during parsing ?

### ISSUE THREAD

**Issue by complyue** [mrkkrp/megaparsec#396]
To implement dynamically-declared operators with precedence, I find myself have to do some hackish custom backtracking with `getParserState/setParserState` like this:

https://github.com/complyue/edh/blob/5d488889aa60def6e9b8116cdeed71932f31e469/edh/src/Language/Edh/Parser.hs#L562-L574

I wonder there may be better ways to do this, or it as is the way to go?

I can't decide even after read the tutorial a few times, please give some comment or clue?

**Comment by mrkkrp** [comment]
I have never implemented dynamically-declared operators with precedence. Can you describe in words the essence of your method?

**Comment by complyue** [comment]
I use a `Map Text Int` as the inner state monad of ParsecT (which is [here](https://github.com/complyue/edh/blob/5d488889aa60def6e9b8116cdeed71932f31e469/edh/src/Language/Edh/Control.hs#L21-L27)), and during parsing, on encountering of an operator declaration/override statement, this map is checked and possibly updated to reflect the known precedence of all operators.

I restrict the operators to be left-associative infix only in language design, this simplifies parsing a bit, so I only consume operators with higher precedence at righ-hand-side of a valid operator, and after it completes parsing, supply it as the left-hand-side expression to the formerly postponed operator with equal-or-lower precedence.

however to decide whether to postpone or consume, I have to parse the pending operator's symbol first, look it up against the map in state. then if the decision is postpone, I have to put it back to be parsed later. I currently do it [here](https://github.com/complyue/edh/blob/5d488889aa60def6e9b8116cdeed71932f31e469/edh/src/Language/Edh/Parser.hs#L562-L574) like said, and seems work fine.

but I'm not sure this is the way to go without further concerns.

**Comment by mrkkrp** [comment]
I’d say if it works for you there is nothing wrong with it.

**Comment by complyue** [comment]
sure, thanks for your review.

and especially thanks for making megaparsec, wonderful!
