### ISSUE TITLE
How to return multiple errors using registerParseError and withRecovery in megaparsec8?

### ISSUE THREAD

**Issue by xhliu** [mrkkrp/megaparsec#397]
["Since version 8, reporting multiple parse errors at once has become much easier."](https://github.com/mrkkrp/megaparsec#error-messages). Any example of doing this, which is also discussed in #359?

**Comment by mrkkrp** [comment]
It should be as simple as using `withRecovery` and then calling `registerParseError` in the recovering callback. Have you tried it?

**Comment by xhliu** [comment]
So the resulting `ParseErrorBundle` will contain all recoverable errors, which can feed into `errorBundlePretty`? It would be really great to see an example documenting this usage, even if it's trivial.

A follow-up question: in the example https://markkarpov.com/megaparsec/fun-with-the-recovery-feature.html, the source file is delimited by newline and the parsing is linear. But parsing generally forms a tree structure, i.e., AST. How does `withRecovery` work in this tree case?

**Comment by mrkkrp** [comment]
All registered errors as well as fatal errors will be combined into a single bundle for you. You only need to call `registerParseError` and the rest should just work.

> How does withRecovery work in this tree case?

You need to be able to skip reliably to next "good" fragment of input, I'm afraid.

**Comment by mrkkrp** [comment]
Would you like further clarifications or it can be closed?
