### ISSUE TITLE
Complete QuickCheck test suite

### ISSUE THREAD

**Issue by mrkkrp** [mrkkrp/megaparsec#4]
It's probably not possible to write such a thing quickly, at least not with 100% coverage. However, we could cover 30% or more for a start improving coverage latter. What's really important is that `megaparsec` should be perceived as bug-free and robust software. To achieve this, good testing is necessary.

Service like [Coveralls](https://coveralls.io/) can be used to measure coverage.

----

Here is the plan:

- [X] prepare test-suite infrastructure
- [X] `Text.Megaparsec.Pos`
- [X] `Text.Megaparsec.Error`
- [x] `Text.Megaparsec.Prim`
- [x] `Text.Megaparsec.Combinator`
- [X] `Text.Megaparsec.Char`
- [x] `Text.Megaparsec.Expr`
- [x] `Text.Megaparsec.Perm`
- [x] `Text.Megaparsec.Token`

**Comment by mrkkrp** [comment]
There are some (temporary, I hope) problems with Coveralls integration. For some reason, `hpc-coveralls` doesn't quite work for `megaparsec`. I've opened an issue here: https://github.com/guillaume-nargeot/hpc-coveralls/issues/48

I hope we'll soon make it work.

**Comment by albertnetymk** [comment]
According to the icon on REAME, coverall is still not working. How about using another one, say https://codecov.io?

**Comment by mrkkrp** [comment]
@albertnetymk, I could try to make it work. Do you know, does it interlude built-in integration with Haskell's HPC or I'll need to find another third party tool?

**Comment by mrkkrp** [comment]
@albertnetymk, oh I see it has something out of the box. Great, I'll try it, thanks!

**Comment by mrkkrp** [comment]
@albertnetymk, no this fails in similar way, `codecov-haskell: command not found` it says. Perhaps we should try with `language: haskell` as the author (both these tools by the same author, by the way) suggests. Although `multi-ghc-travis` advises against use of `language: haskell`, oh my.

**Comment by albertnetymk** [comment]
I feel the last comment you wrote on [issue](https://github.com/guillaume-nargeot/hpc-coveralls/issues/48) suggested that `hpc-coveralls` might not work so well with ghc 7.10. In the [README](https://github.com/guillaume-nargeot/hpc-coveralls/blob/master/hpc-coveralls.cabal), it says that it's only tested up to 7.8.

On related question, though, is that the folder structure of `dist/hpc`. On my box, it's:

```
├── dyn
│   └── mix
│       └── megaparsec-4.0.0
│           └── megap_7pF0tieR4WDH9AHy2eIXTp
└── vanilla
    ├── html
    │   ├── megaparsec-4.0.0
    │   │   └── megap_7pF0tieR4WDH9AHy2eIXTp
    │   ├── old-tests
    │   │   └── megap_7pF0tieR4WDH9AHy2eIXTp
    │   └── tests
    │       └── megap_7pF0tieR4WDH9AHy2eIXTp
    ├── mix
    │   ├── megaparsec-4.0.0
    │   │   └── megap_7pF0tieR4WDH9AHy2eIXTp
    │   ├── old-tests
    │   └── tests
    └── tix
        ├── megaparsec-4.0.0
        ├── old-tests
        └── tests
```
Therefore,

```
$ codecov-haskell old-tests
codecov-haskell: Couldn't find the file dist/hpc/tix/old-tests/old-tests.tix
```
I wonder if you encounter this problem.

ENV:
ghc: 7.10.1
cabal: 1.22.2.0
odecov-haskell: 0.4.0.2

**Comment by mrkkrp** [comment]
@albertnetymk, No I've excluded `old-tests` directory with `--exclude-dir=old-tests` flag. I think we can use Coveralls just fine now. The error message allows to suppose that it's a minor problem and once we know how to tell `hpc-coveralls` not to look for `Megaparsec.String` file this will be solved. I'm waiting comment from @guillaume-nargeot.

**Comment by guillaume-nargeot** [comment]
I'm almost done adding support for cabal 1.22 / ghc 7.10 to hpc-coveralls.
Will let you know once it's done.

**Comment by mrkkrp** [comment]
@guillaume-nargeot, What's about that issue with missing file for `Text.Megaparsec.String`? I think it's not related to GHC version. (See comment on the issue thread in `hpc-coveralls`.)

**Comment by guillaume-nargeot** [comment]
I can't get back to you on this today, but I will look into it.
Sorry for the delay in fixing these issues.

**Comment by mrkkrp** [comment]
@guillaume-nargeot, It seems like the problem is solved now, we have a functioning badge now (although more directories should be excluded from testing, I guess).

**Comment by mrkkrp** [comment]
Current coverage is 61%, that's not bad compared with initial state of Parsec testing. I guess it will be about 70–75% by the moment of release.

**Comment by mrkkrp** [comment]
Finally, it's done. 116 tests covering 85% of code.
