### ISSUE TITLE
takeWhileJustP

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [mrkkrp/megaparsec#403]
It would be nice to have a `takeWhileJustP :: Maybe String -> (Token s -> Maybe a) -> m [a]`

**Comment by mrkkrp** [comment]
I think the same thing can be achieved by using `takeWhileP` and then mapping the results. If you have the `Token s -> Maybe a` function, you already can provide `Token s -> Bool` which `takeWhileP` wants and at the same time you also know how to remap things afterwards.

I'm reluctant to introduce new primitives at this ponit.
