### ISSUE TITLE
[Question] Example of streaming lexing?

### ISSUE THREAD

**Issue by sorenbug** [mrkkrp/megaparsec#406]
Is there an example of streaming lexing into parsing, and not just building up a list of tokens?

#367 Is a little relevant I think because of Megaparsec's built-in `Lexer` functionality.

**Comment by mrkkrp** [comment]
What kind of streaming do you want to implement? As I mention in #367, Megaparsec is not a streaming/incremental parsing library. It expects all input to be available before the parsing begins.

**Comment by sorenbug** [comment]
Ah, I misunderstood #367. Sorry 😅
