### ISSUE TITLE
Suggestion for adding `horizontalSpace` or equivalent

### ISSUE THREAD

**Issue by dschrempf** [mrkkrp/megaparsec#408]
Hi!

`space` includes newlines and carriage returns. Often, I need to parse horizontal space. Usually, I write a function like so

```
horizontalSpace :: Parser ()
horizontalSpace = skipMany $ char (c2w ' ') <|> tab
```

(Here I use `Byte`, and so need to convert the space `Char` to `Word8`. I borrow the `c2w` function from the `bytestring` package. Do you think this (or something equivalent) would fit into the library?

Thanks,
Dominik

**Comment by mrkkrp** [comment]
In my experience `space` is only used to construct a kind of general "space consumer" which handles different kinds of comments and whitespace. To make it accept only whitespace without newlines it is enough to pass the correct parser as the first argument of `space`, for example this one:

```haskell
sc1 :: MonadParsec e Text m => m ()
sc1 = void $ takeWhile1P (Just "white space") isSpace

isSpace :: Char -> Bool
isSpace x = x == ' ' || x == '\t'
```

But then, it is unlikely that you want to use `space` with this kind of parser, because then you probably don't want to take mulitline comments (and single-line too?) into account. So the function `sc1` can be used as it is.

What I'm trying to say is that `space` covers a very specific use case and you can already control whether or not it'll accept newlines, even though without newlines it is not so useful IMO.

**Comment by dschrempf** [comment]
Thanks for your comment. Maybe I was not clear enough. I don't want to change the behavior of `space`. I was just asking, if adding a function for parsing "horizontalSpace" (or equivalent) would make sense, since I am ending up writing this function every single time I use megaparsec. Your implementation for `Text` is also great!

For example, I often need to parse a (horizontal) white space separated list of numbers into a vector.

**Comment by mrkkrp** [comment]
That’s exactly how I understood you. What I said is that you already can do that either by defining something like `sc1` or by passing the correct space consumer to `space`.

**Comment by dschrempf** [comment]
I am sorry, but I don't understand your point. Of course, I can define a function that parses horizontal space. That's what I keep doing. I am asking if this function can be included into the library. This would also clarify that `space` parses all white space including vertical one, and the new version `hspace` or `horizontalSpace` (or any meaningful name we can come up with) parses horizontal space only.

**Comment by mrkkrp** [comment]
> `space` parses all white space including vertical one,

This statement is not true. What it parses depends on what you pass to it (the first argument).

> and the new version `hspace` or

I think we should not name like this. This would suggest that it is somehow related to `space`, which it is not.

> I am asking if this function can be included into the library

What would be the definition of that function?

**Comment by dschrempf** [comment]
Hm, I think we are talking about different functions. I guess, you are referring, for example, to `Text.Megaparsec.Byte.Lexer.space`. I was reffering to `Text.Megaparsec.Byte.space`, which does not take extra arguments, and is actually very similar to the function that you posted. Please correct me, if I am wrong.

In my opinion, the module `Text.Megaparsec.Byte` could benefit from a function `Text.Megaparsec.Byte.hspace`; also the Char equivalent, of course.

**Comment by mrkkrp** [comment]
Ah, you are right. I totally forgot about the other `space`. Then yes, what you propose makes sense.

**Comment by dschrempf** [comment]
I apologize for the confusion, I should have been more specific.

**Comment by mrkkrp** [comment]
I just added it. Do you want me to release a new version or it can wait?

**Comment by dschrempf** [comment]
Thank you very much! A new version is definitely not necessary from my side!
