### ISSUE TITLE
Newtype for deriving stream type for lists

### ISSUE THREAD

**Issue by Boarders** [mrkkrp/megaparsec#413]
Would it be possible to make a stream newtype that makes it possible to derive (using derivingVia) a Stream type for newtype wrappers around list. The motivation is when you want to first use a lexer which collects a list of tokens and then parse. As it stands it seems you need to write your own Stream instance in those situations.

**Comment by mrkkrp** [comment]
I think it is a sane idea.

**Comment by mrkkrp** [comment]
Resolved in #415.
