### ISSUE TITLE
Control.Monad.Combinators documentation should be reexported

### ISSUE THREAD

**Issue by ibispi** [mrkkrp/megaparsec#417]
Posting this issue for a friend who doesn't have a github account:

"Open the [Hackage index for Megaparsec](https://hackage.haskell.org/package/megaparsec-8.0.0/docs/doc-index-All.html) and <Ctrl+F> for `sepEndBy`. You will find an entry without a link.
This makes it more difficult to find the relevant documentation. Having a «reexported from Control.Monad.Combinators» would be better for clarity and discoverability in my opinion."

**Comment by mrkkrp** [comment]
This is a Haddock issue, see https://github.com/haskell/haddock/issues/682. Closing, because this is not specific to Megaparsec.

**Comment by merijn** [comment]
This can already be solved by explicitly listing the re-exports though. Which I'd argue is better than re-exporting a module of a dependency as re-exporting the entire module means that a new upstream release that adds new names to the re-exported module also changes the exports of Megaparsec, which violates the PVP.
