### ISSUE TITLE
ExceptT support

### ISSUE THREAD

**Issue by reubenharry** [mrkkrp/megaparsec#419]
I'm considering a use case of megaparsec where I want to represent failure in the output type of the parser that is not parse failure. As a very simplified example, consider parsing "3/0" and getting a successful parse, with the value "Left "division by zero". 

I noticed that ExceptT is not supported for MonadParsec, and this made me wonder if I'm approaching the problem wrong, and should be using the error handling inside ParsecT instead. The problem with that is that I want cases where the parse succeeds, but I still get a failure. I saw the "observing" construction in the (excellent) tutorial, but wasn't sure if this was an appropriate use case.

Thanks! (and thanks especially for writing such a well documented library!!)

**Comment by mrkkrp** [comment]
It looks like you want the failure case to be represented in AST that you're constructing. You can do it without `EitherT`. Just do a validation pass immediately after parsing to find ASTs that contain things like "division by zero" and then perhaps error out if that's what you want to do.

I don't know if `ExceptT` instance makes much sense or whether it can be defined in a reasonable way. I haven't tried to define it.

**Comment by reubenharry** [comment]
Ah okay, that makes sense. I was basically trying an approach where rather than using the combinator parsers to build an AST, I evaluated the AST inside the parsers. So e.g. (in pseudocode):

plus :: Parser Int
plus = do
  x <- int :: Parser Int
  y <- int :: Parser Int
  return (x+y)

Any thoughts on whether that's a reasonable approach? (it probably isn't, but seems tempting)

**Comment by mrkkrp** [comment]
Depends on what you are trying to do, but in 99% of cases `(Add (Int 4) (Int 5))` is a more useful result than just `9`. The former you can then evaluate to `9` anyway, with the latter there are not many interesting things to do.

**Comment by mrkkrp** [comment]
Should we close the issue?
