### ISSUE TITLE
Add base-4.7.0.0 compatibility

### ISSUE THREAD

**Issue by bkaestner** [mrkkrp/megaparsec#42]
This should be rather easy. It's more or less the question whether you actually want backwards-compatibility, and whether you want to use `{-# LANGUAGE CPP #-}` for the `MIN_VER` macro or "redundant import" warnings.

I just tried a quick 'n dirty patch and imported either `Control.Applicative` (17 files\*) or `Data.Foldable (Foldable, foldMap)` (1 file), which passed all tests. Note that the import of `Control.Applicative` isn't necessary in all of those files, e.g. all `parseFromFile` could be written with infix `fmap` instead of `<$>`.

If you're interested in a patch, I can probably prepare a proper one later today.

\* Bug9.hs is the only file that needs `hiding (Const)` due to `data Expr = Const …`.

**Comment by mrkkrp** [comment]
Answering your question, yes, I'm interested in that patch, it would be great. It's now apparent that some users would benefit from compatibility with `base-4.7.0.0` and the library would be more widely used.

Enable `CPP` extension globally in Megaparsec, in `megaparsec.cabal`, then please use `MIN_VER` to add the “missing” imports conditionally. When you have pull request ready we'll discuss other details if necessary.

**Comment by mrkkrp** [comment]
OK, Travis [says](https://travis-ci.org/mrkkrp/megaparsec) that it builds with GHC 7.8 now. Although I Cabal 1.18 required different flag (`--enable-library-coverage` instead of `--enable-coverage`), so I had to put if/then/else statement in `.travis.yml` file. I had to put it all in one line, what a disaster. Closing this.
