### ISSUE TITLE
Non-deterministic parsing (question)

### ISSUE THREAD

**Issue by reubenharry** [mrkkrp/megaparsec#420]
Is there a natural way to allow for non-deterministic parsing in megaparsec? I'd like to be able to write:

```Haskell
parser = tryBoth parserA parserB
```

and have the result of using _parser_ be a list of the parse from _parserA_ and _parserB_. I could potentially do this with a ListT transformer on top of ParsecT. Or should I use a different library, like Earley, if I'm interested in ambiguity?

**Comment by mrkkrp** [comment]
If your grammar is context free Earley is a better choice. I don't think there is a good way to do something like this with Megaparsec.
