### ISSUE TITLE
Parsing left recursive grammar with megaparsec

### ISSUE THREAD

**Issue by isubasinghe** [mrkkrp/megaparsec#421]
Hey @mrkkrp , thanks for making and maintaining this brilliant library. 

Hope its okay for me to ask this here, I am a graduate student studying compilers. 

How does megaparsec parse left recursive grammar? 
```haskell
data CmpOp
    = And Expr Expr
data Expr
    = CmpOp CmpOp

expression :: Parser Expr

andParse :: Parser Expr
andParse = do
    _ <- space
    lhs <- expression
    _ <- space
    rhs <- expression
   return $ CmpOp (And lhs rhs)
```
This is a minimal representation of my current parser which loops infinitely.  
After investigation, tutorials using parsec seem to solve this problem via chainl but this isn't present in this library.

**Comment by anka-213** [comment]
You can use the module [`Control.Monad.Combinators.Expr`](https://hackage.haskell.org/package/parser-combinators-1.2.1/docs/Control-Monad-Combinators-Expr.html) in `parser-combinators` for parsing left-recursive expressions.
