### ISSUE TITLE
Error from try branch used over other branch with (<|>)

### ISSUE THREAD

**Issue by 1Computer1** [mrkkrp/megaparsec#423]
If you have for example:
```hs
p1 = char 'a' >> char 'b' >> char 'c'
p2 = char 'a' >> char 'd'
p3 = try p1 <|> p2
```

then `parseTest p3 "abz"` gives:
```
1:3:
  |
1 | abz
  |   ^
unexpected 'z'
expecting 'c'
```

but you might expect instead the following, since we used `try` on the first branch:
```
1:2:
  |
1 | abz
  |  ^
unexpected 'b'
expecting 'd'
```

This is consistent with what Parsec does, and I think it makes more sense too, but perhaps I might be missing something. The problem arises from `pPlus`:
```hs
pPlus m n = ParsecT $ \s cok cerr eok eerr ->
  let meerr err ms =
        let ncerr err' s' = cerr (err' <> err) (longestMatch ms s')
            neok x s' hs = eok x s' (toHints (stateOffset s') err <> hs)
            neerr err' s' = eerr (err' <> err) (longestMatch ms s')
         in unParser n s cok ncerr neok neerr
   in unParser m s cok cerr eok meerr
```

The fix is to simply remove `ncerr` and use `cerr` instead for `unParser n`.

**Comment by mrkkrp** [comment]
I think the present behavior is better than original Parsec behavior. We basically prefer parse errors from branches that make more progress, that is, they manage to consume more input. In general, in more complicated situations, that's what you want.
