### ISSUE TITLE
Typo in 9.0.0 docs re hspace1

### ISSUE THREAD

**Issue by sullyj3** [mrkkrp/megaparsec#424]
https://hackage.haskell.org/package/megaparsec-9.0.0/docs/Text-Megaparsec-Char.html#v:hspace1

The docs say hspace1 has existed since 8.0.0, I believe it should be 9.0.0

**Comment by mrkkrp** [comment]
Thanks!

**Comment by raehik** [comment]
This doesn't appear to be reflected on the Hackage docs yet. It seems a likely pitfall, due to Stackage not yet serving 9.0.0 (just happened to me).

**Comment by mrkkrp** [comment]
There has been no release yet because I'm reluctant to cut a release just for a typo fix.

**Comment by raehik** [comment]
OK, thanks! Understood, I didn't know how Haskell package releases worked.
