### ISSUE TITLE
Safe Haskell support

### ISSUE THREAD

**Issue by mlugg** [mrkkrp/megaparsec#425]
Currently, Megaparsec does not use the Safe or Trustworthy language extensions, which makes it more challenging to use from codebases that use Safe Haskell. I'm not sure if there are any unsafe exposed features; if not, it should be fine to mark modules as Safe or Trustworthy, but if so, it might be nice to make a module that re-exports a safe subset of Megaparsec.

**Comment by mrkkrp** [comment]
We use `GeneralizedNewtypeDeriving` which is [not allowed](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/safe_haskell.html) in the safe language. This can probably be worked around. Would you like to take a stab at making the library safe?

**Comment by mlugg** [comment]
> We use `GeneralizedNewtypeDeriving` which is [not allowed](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/safe_haskell.html) in the safe language. This can probably be worked around. Would you like to take a stab at making the library safe?

Having looked through the code: GND is only used in two places, which should make the change fairly simple. In Text.Megaparsec.Pos, we use it to derive NFData; this can be replaced with DeriveAnyClass as NFData has a default implementation based on Generic. In Text.Megaparsec.Internal, we derive Semigroup and Monoid for Hints; this can't be removed as easily, however the instances are trivial enough that to me it seems fine to simply define them manually below the newtype. Do you have any issues with this approach?

Also: would you prefer the Safe extension be added to each file, or applied project-wide in the Cabal file?

**Comment by mrkkrp** [comment]
> Do you have any issues with this approach?

No, this is fine.

I prefer to apply language extensions on per-file basis; it looks like in this case we don't really have a choice anyway.

**Comment by mlugg** [comment]
There's one more issue that I've hit. Text.Megaparsec.{Char,Byte}.Lexer import Data.Scientific, which isn't marked Safe. Having looked at `scientific`, I believe it can be, so I'll open a PR there shortly; however, looking at that repo's history, it doesn't look hugely active, and a new version hasn't been pushed to Hackage in several years, so I suspect it will take a while. Should we treat this issue as a blocker, or should we just mark the lexer modules as Trustworthy until Data.Scientific becomes safe (my preferred option)?
Happily, I can confirm that if we do the discussed changes (and mark those two modules as Trustworthy), Megaparsec compiles fine (and all tests succeed).

**Comment by mrkkrp** [comment]
Let's do that. Also please let me know what the maintainers of `scientific` say.

**Comment by mrkkrp** [comment]
Do you want me to release a new version?
