### ISSUE TITLE
Anything bad for lexemes to consume leading spaces instead of trailing ones?

### ISSUE THREAD

**Issue by complyue** [mrkkrp/megaparsec#428]
I'm considering to allow doc comments to be parsed and stored with the node immediately following them, e.g.

```
{##
 # this is the module's doc comment
 #}

# this is regular line comment to be dropped in parsing

{## 
 # this is the doc comment for  `doXXX()`
 #}
method doXXX() pass

{#
 # this is regular block comment to be dropped in parsing
 #}

{## 
 # this is the doc comment for  `doYYY()`
 #}
method doYYY() pass
```

But following the default convention for lexemes to consume trailing whitespaces, a doc comment would have been absorbed by the lexeme before it, the parser for later lexeme then lose its way to optionally receive the doc comment.

I have rough ideas to get it working, but feels like I need to have lexemes to consume leading whitespaces instead, so I would like to ask here, why the default convention of lexemes is so, and any serious problem to go the other way around?

I think one change is to expect whitespaces when expecting eof as before,  but not much other concerns.

**Comment by Kazark** [comment]
@complyue Aren't doc comments proper syntactic elements, and thus not whitespace at all?

**Comment by complyue** [comment]
@Kazark Yes, they should be, but since they are also valid block comments by design (akin to javadoc's `/** ... */` syntax), they'll be consumed as block comments after previous lexeme, if I keep following the default lexeme convention.

**Comment by Kazark** [comment]
Perhaps this is where my thought on it borders between an answer to this and langauge design, but---I have always thought it a hack that doc comments were a kind of comment (i.e. a thing that is normally throwaway from the compiler) rather than their own syntactic element. It doesn't seem to me that you would even need to change the syntax in order to parse `{##...` distinctly from `{#[^#]...`.

**Comment by complyue** [comment]
@Kazark Point taken, I probably will go that way if no more idiomatic ways appear, I'd ask here because Megaparsec encourages the practice like this:

```hs
sc :: Parser ()
sc =
  L.space space1 (L.skipLineComment "#") (L.skipBlockCommentNested "{#" "#}")

lexeme :: Parser a -> Parser a
lexeme = L.lexeme sc

...

parseAlphaName :: Parser AttrName
parseAlphaName = lexeme $ do
  anStart <- takeWhile1P (Just "attribute name") isIdentStart
  anRest  <- takeWhileP Nothing isIdentChar
  return $ anStart <> anRest

```

You see `{#[^#]` may not just work in `L.skipBlockCommentNested "{#" "#}"`, or it can be?

**Comment by Kazark** [comment]
Right, I see what you are saying: you will either have to do something to not make doc comments look syntactically like a specialization of block comments, or you will not be able to use Megaparsec's built-in paradigms. I quite like that Megaparsec not only gives you parser combinators in the abstract, but caters explicitly to typically language conventions. I just tend to have a divergent opinion on this particular language convention. But I get what you're saying now.

**Comment by complyue** [comment]
Help!  In tinkering with an implementation of doc comment parsing, I met an error that I can't reason about, that seems `optional` doesn't work here:

https://github.com/complyue/dcp/blob/1df7ad590d78d4fa9a017eb53f9f265e291bdfa7/src/Parser.hs#L50-L54

https://github.com/complyue/dcp/blob/1df7ad590d78d4fa9a017eb53f9f265e291bdfa7/src/Parser.hs#L31-L32

reprod:

```console
$ cabal run dcp:dcp < samples/basic.txt 
Up to date
dcp: 10:1:
   |
10 | method doXXX() pass
   | ^
unexpected 'm'
expecting ';'

CallStack (from HasCallStack):
  error, called at src/Parser.hs:149:14 in main:Parser
$ 
```

I suspect that bcoz `fail` in a parser after you've consumed some input will err out instead of to try alternatives, I've fixed some code in that pattern from my previous attempts, then this error, I really can't reason about why it is so, help!

**Comment by noughtmare** [comment]
> You see `{#[^#]` may not just work in `L.skipBlockCommentNested "{#" "#}"`, or it can be?

I think you can define your own slightly different `skipBlockCommentNested`:

```Haskell
mySkipBlockCommentNested = p >> void (manyTill e n)
  where
    e = mySkipBlockCommentNested <|> void anySingle
    p = string "{#" <* notFollowedBy (char '#')
    n = string "#}"
```

**Comment by complyue** [comment]
@noughtmare Thanks very much, definitely worth tinkering with this trick.

**Comment by complyue** [comment]
So I've gotten my interpreter refactored for lexemes to consume leading whitespaces instead of trailing ones, and able to parse doc comments besides normal block comments, working with rather complex script files. 

But the modifications seems less desirable, for every symbol tends to not match, I have to modify each parent parser having it as one the alternatives to explicitly consume whitespaces before the `choice`, or add `try` to have the whitespace before the symbol parser, or the overall parsing can be destined to err out for any symbol parser mismatched but have leading spaces consumed. In the later case rest alternative parsers will have to consume whitespaces again and again before one got matched,  seems quite unnecessary an overhead.

So I see the big advantage of trailing-space-consuming lexemes now.

Next, I'll try @Kazark then @noughtmare 's suggestion to have doc comments not parsed as block comment in the first place, and see how it'll come along overall.

But I'm still curious if Megaparsec is used to parse Haskell's pragmas e.g. `{-# UNPACK #-}` which is also valid block comment there, what tactics would you use?

Also if something like https://github.com/mrkkrp/megaparsec/issues/429#issuecomment-716170935 is supported, then repeated consumption of whitespaces before multiple alternatives of different symbols will not be an issue in the first place. Can we (or do we already) have that?

**Comment by complyue** [comment]
I tried the implementation with doc comment as invalid block comment, with slightly modified trailing-space consumer like this:

https://github.com/e-wrks/edh/blob/0.3/host.hs/src/Language/Edh/Parser.hs#L36-L45
```hs
sc :: Parser ()
sc = L.space space1 (L.skipLineComment "#") edhSkipBlockCommentNested

edhSkipBlockCommentNested :: Parser ()
edhSkipBlockCommentNested =
  try (string "{#" >> notFollowedBy (char '#')) >> void
    (manyTill (L.skipBlockCommentNested "{#" "#}" <|> void anySingle)
              (string "#}")
    )
```

Things work pretty well except no doc comment can be placed just before eof, further things based on this e.g. module doc  association and runtime doc binding to procedures instantiated, are making good sense as always, so Megaparsec's choice of the idiom is really very nice. I'll end up with this routine wrt the doc comment parsing.
