### ISSUE TITLE
How to encode *NoMatch* after consumed some input in a parser

### ISSUE THREAD

**Issue by complyue** [mrkkrp/megaparsec#429]
As I observed (have no idea where a canonical definition could live for this) that for the contract of parser combinators:

 * `fail` with no input consumed will have next alternative to be tried with possible success
 * `fail` with some input consumed will err out immediately regardless rest alternatives

Am I right about these rules? Where is the official specification of such rules?

Then I guess that `empty` result of a parser could mean *NoMatch* even after consumed some input, and want to leverage this semantic, but encountered error with current implementation https://github.com/complyue/dcp/blob/5be688396b7e2bda00ea80fd99d2a7b3ec5c788d/src/Parser.hs#L138-L146

```hs
artifactDecl :: Parser ArtDecl
artifactDecl = do
  artCmt <- immediateDocComments
  (eof >> empty) <|> do
    artBody <- takeWhileP (Just "artifact body")
                          (not . flip elem (";{" :: [Char]))
    if T.null $ T.strip artBody
      then empty -- this is not possible in real cases
      else return (artCmt, artBody)
```

```console
$ cabal run dcp < samples/full.txt
Up to date
dcp: 73:1:
   |
73 | <empty line>
   | ^
expecting "{#", "{##", or artifact body

CallStack (from HasCallStack):
  error, called at src/Parser.hs:151:14 in main:Parser
```

So how can I achieve that?

Background is I'm trying to prototype an implementation of doc comment parsing as described at https://github.com/mrkkrp/megaparsec/issues/428

**Comment by noughtmare** [comment]
There is some documentation about the semantics of `<|>` here: https://hackage.haskell.org/package/megaparsec-9.0.0/docs/Text-Megaparsec.html#t:ParsecT. Next to the Alternative instance it says:

> empty is a parser that **fails** without consuming input.

From my own experiments it seems that once you consume some input you have committed to the branch. If you want to back out you have to use the backtracking `try` function.

I expected that this would violate some type class laws from `Alternative`, but it turns out that alternative doesn't have laws about `empty` being the unit of `<|>`.

**Comment by complyue** [comment]
@noughtmare Thanks, and is there already some version of `many` to just ignore some failures (better being discriminative to not hide e.g. syntax errors) ?

```hs
moduleDecl :: Parser ModuleDecl
moduleDecl = do
  moduCmt <- docComments
  arts    <- manyTill artifactDecl eof
  return (moduCmt, arts)
```

So I can simply replace  `manyTill artifactDecl eof` as in above?

**Comment by complyue** [comment]
An uneducated guess: is it possible for `empty` of `ParsecT`'s `Alternative` instance to have a separate implementation from `mzero`, which doesn't **fail** but silently contributes nothing when combined with others?

https://github.com/mrkkrp/megaparsec/blob/ccf314b0b940bdbfec3820b18f42d241e6920b61/Text/Megaparsec/Internal.hs#L202-L205

Failing semantic can still be obtained by using `mzero` I'd think.

**Comment by noughtmare** [comment]
I'm not quite sure what kind of semantics you want this `manyTill` replacement to have. You say you want to ignore some failures, but which exactly?

**Comment by complyue** [comment]
@noughtmare 

> You say you want to ignore some failures, but which exactly?

I mean whitespaces found to be associated with no syntactic element. I know Megaparsec's idiom is to let some lexeme to consume (discard) any whitespace following it, but in my case as described in #428, the doc comment is meaningful when found immediately before a lexeme, but should be treated as block comments if all following it is whitespaces till eof.

**Comment by mrkkrp** [comment]
@complyue You control backtracking with `try`. I have the impression that you have not read the tutorial:

https://markkarpov.com/tutorial/megaparsec.html

It should be helpful for understanding how backtracking works in Megaparsec.

**Comment by mrkkrp** [comment]
You could always encode "no match" by doing something like this:

```haskell
myParser' = try myParser <|> return NoMatch
```

**Comment by complyue** [comment]
@mrkkrp I realize that `NoMatch` is not accurate for my intent, I actually want the semantic to be expressible that:

- no fail (but subsequent parsers should be tried in sequence)
- no backtracking (leave consumed input consumed)
- contributing empty result to outer `many` or a similar combinator

A concrete example is here https://github.com/complyue/dcp/blob/498916f73afbe2b7bbf6105da352a9c99fe88707/src/Parser.hs#L142-L145

```hs
artifactDecl :: Parser ArtDecl
artifactDecl = lexeme $ do
  artCmt <- optional immediateDocComment
  atEnd >>= \case
    True  -> empty
    False -> do
      artBody <- takeWhileP (Just "artifact body")
                            (not . flip elem (";{" :: [Char]))
      if T.null $ T.strip artBody
        then empty -- this is not possible in real cases
        else return (artCmt, artBody)
```

I want `True  -> empty` to let `artifactDecl` evaluate to sth with the semantic said above, and obviously `empty` is not the correct device here.

**Comment by mrkkrp** [comment]
So why don’t you just return some value instead of using empty?

**Comment by complyue** [comment]
I would prefer to have the parser type (`Parser ArtDecl`) simple, i.e. without adding another layer of monad transformer or similar abstraction beyond `ArtDecl`. As I sense it, using `mempty` as `Monoid` is designed can achieve that, can I anticipate that? Or what is making that impossible?

**Comment by complyue** [comment]
I just come to better understanding of the issue, and seems it can be addressed as well as https://github.com/complyue/dcp/pull/3/files , like https://github.com/complyue/dcp/commit/f0c12d51e30cfc49e9e580e5e766c4e8f7d4b54e or https://github.com/complyue/dcp/commit/2600179ab480b2778589495c1ab0bb092f3ae7df , they are very similar.

But I'm still wondering, this really unaddressable from the combinator lib's design space? Why?

**Comment by complyue** [comment]
With help from Olaf, I think I just cracked my confusion now, that I failed
to distinguish between the 2 monoid structures of concatenation and
choice, and have wrongly assumed somehow Alternative can do
concatenation at the same time as choice making.

Now I understand it clearly that parsers can be concatenated only if
their result type is concatenatable, so if the combinator lib is to
address my demand, it can define `maynTill'` with the parser type
fixed like:

```hs
manyTill' :: Monoid a => Parser a -> Parser end -> Parser a
manyTill' p end = go where go = (mempty <$ end) <|> liftA2 mappend p go
```

Then I can tune my result types, and implement my parsers like:

```hs
type ArtDecl = (Maybe DocComment, Text)
data ModuleDecl m = (Applicative m, Monoid (m ArtDecl)) =>
  ModuleDecl (Maybe DocComment) (m ArtDecl)

moduleDecl :: (Applicative m, Monoid (m ArtDecl)) => Parser (ModuleDecl m)
moduleDecl = lexeme $ do
  sc
  moduCmt <- optional docComment
  arts    <- manyTill' (scWithSemiColons >> artifactDecl) eof
  return $ ModuleDecl moduCmt arts

artifactDecl :: (Applicative m, Monoid (m ArtDecl)) => Parser (m ArtDecl)
artifactDecl = lexeme $ do
  artCmt <- optional immediateDocComment
  choice
    [ eof >> return mempty
    , do
      artBody <- takeWhileP (Just "artifact body")
                            (not . flip elem (";{" :: [Char]))
      return $ pure (artCmt, artBody)
    ]
```

https://github.com/complyue/dcp/blob/39039e62db5f63e61814383ffc2c5f4fba240806/src/Parser.hs#L128-L152

This approach clears my doubts, though doesn't seem more ergonomic compared to approaches like

  https://github.com/complyue/dcp/commit/2600179ab480b2778589495c1ab0bb092f3ae7df

or 

  https://github.com/complyue/dcp/commit/f0c12d51e30cfc49e9e580e5e766c4e8f7d4b54e

Well, then I know my options now.
