### ISSUE TITLE
ParsecT violates MonadPlus laws

### ISSUE THREAD

**Issue by noughtmare** [mrkkrp/megaparsec#430]
Specifically the [`v >> mzero = mzero`](https://hackage.haskell.org/package/base-4.14.0.0/docs/Control-Monad.html#t:MonadPlus) law. E.g.

```Haskell
>>> isRight $ parse ((char 'a' >> mzero) `mplus` char 'a') "" "a"
False
>>> isRight $ parse (mzero `mplus` char 'a') "" "a"
True
```

I think this causes much of the confusion in https://github.com/mrkkrp/megaparsec/issues/429.

The current behaviour could be retained with the Alternative instance, since Alternative doesn't have this law, but I think that would also be confusing.

**Comment by complyue** [comment]
I'm not sure I fully understand this issue, but:

```hs
λ> isRight $ parse (try (char 'a' >> mzero) `mplus` char 'a') "" "a"
True
```

Does this make some difference?

**Comment by complyue** [comment]
Also, my intuition expects `Right "ab"` in below but:

```lhs
>>> parse (string "a" `mplus` string "b") "" "ab"
Right "a"
```

I'm so confused what behavior should I expect from `ParsecT`'s `MonadPlus` instance, also `Alternative` instance?

**Comment by mrkkrp** [comment]
Interesting. Combinators that are defined in terms of `MonadPlus` are more efficient than those defined in terms of `Alternative`. So the current situation is a compromise. I think we should keep things as they are. Perhaps adding a note to the docs would be the right thing to do here?

**Comment by noughtmare** [comment]
I also got this reply on the haskell-cafe mailing list:

> That law (v >> mzero = mzero) is controversial. It's near impossible to satisfy for slightly sophisticated monads. It's notably broken by `MaybeT` whose very purpose is to augment a monad with such an extra Alternative/MonadPlus capability (a concrete counterexample for that law can be found with `MaybeT (State s)`).
>
> MonadPlus is there mainly for historical reasons, because it predates Applicative. Then Alternative was added because the operations turned out to be useful even for Applicatives that were not Monads. The presence of both seems to sugggest there ought to be a difference, but IMO they should just be considered the same and we should thus simply forget about MonadPlus. How would you document that Alternative and MonadPlus may have different  implementations anyway? Imagine if `Control.Monad.msum` and `Control.Applicative.asum` were not the same, how confusing that would be.
>
> To add an error that can not be recovered from you can use `Maybe` or `Either` as the base monad for `ParsecT`: `ParsecT e s Maybe`, so `lift Nothing` fails with your "unparsable" semantics.
> 
> Li-yao

So, `Alternative` and `MonadPlus` are both unfortunately pretty lawless. 

But, I think we could interpret the `=` in the `v >> mzero = mzero` law as equivalent modulo "side-effects". So the effects from `v` may still be performed (in terms of `ParsecT`: you don't have to backtrack), but the interaction with `mplus` should be the same for `v >> mzero` and `mzero` (the next alternative has to be tried if one of the first cases results in a failure).

---

> Combinators that are defined in terms of MonadPlus are more efficient than those defined in terms of Alternative.

The `Alternative` instance is implemented in terms of the `MonadPlus` instance for `ParsecT`:

```Haskell
-- | 'empty' is a parser that __fails__ without consuming input.
instance (Ord e, Stream s) => Alternative (ParsecT e s m) where
  empty = mzero
  (<|>) = mplus
```
[(source)](http://hackage.haskell.org/package/megaparsec-9.0.0/docs/src/Text.Megaparsec.Internal.html#line-198)

So, I don't think one is more efficient than the other.

**Comment by mrkkrp** [comment]
> So, I don't think one is more efficient than the other.

In practice, monadic code is more efficient. If you benchmark combinators from `Control.Applicative.Combinators` against `Control.Monad.Combinators` (both come from `parser-combinators`) you'll find that the latter are faster and have no memory leaks. This has to do not with how `(<|>)` and `mplus` are defined, but with the way parsing operations are sequenced and perhaps with the way GHC performs optimizations for monadic code.

**Comment by complyue** [comment]
Have we come to some conclusion about this issue? Sorry but I can't see it, maybe `mzero` should be interpreted in `ParsecT`'s instance as: there is at lease one mismatch happened, regardless whether the combined parsers as a whole ultimately parses or unparses?
