### ISSUE TITLE
Ways to implement a fault tolerant parser

### ISSUE THREAD

**Issue by complyue** [mrkkrp/megaparsec#431]
Google shows this question asked but no answer: https://www.reddit.com/r/haskell/comments/eg8lyn/fault_tolerant_parser/

Quoting https://github.com/microsoft/tolerant-php-parser#design-goals

> Error tolerant design - in IDE scenarios, code is, by definition, incomplete. In the case that invalid code is entered, the parser should still be able to recover and produce a valid + complete tree, as well as relevant diagnostics.

A real world example could be [Eclipse](https://en.wikipedia.org/wiki/Eclipse_(software))'s Java editor, which from the very beginning (initial release date back to 2004), parses Java code as much as possible besides syntax errors in it. (Even more stunning, its Java compiler can produce runnable `.class` bytecode files from `.java` files with syntax errors postponed to runtime, but that's less relevant here.)

As part of my effort to create a [language server](https://langserver.org) for my language, like https://github.com/haskell/haskell-language-server for Haskell, I'd like to have my parser be abled to give out partial AST in case there are errors found. But Megaparsec's general output format is `Either (ParseErrorBundle s e) a`, so seems not directly possible.

I'd think `ParseErrorBundle` might be possible to be part of my parser's result type, but that still requires deeper knowledge about the internal structure of `ParseErrorBundle`, so I'd like to gather idiomatic practices and advices by asking here to get started.

**Comment by mrkkrp** [comment]
Typically a parer either fails or succeeds. What you are describing is not impossible though, but you'll need to write more specialized code manually. You could allow e.g. top-level structures in the AST of your language to be replaced by parse errors. Then you'd need custom error printing function that would find and display all the nodes that have failed to parse.

A real-world example of a parser that doesn't give up despite errors is MMark parser here:

https://github.com/mmark-md/mmark/blob/master/Text/MMark/Parser.hs

Although it is quite involved.

Also, have you seen [`registerParseError`][register-parse-error]? This is not helpful if you want to output incomplete ASTs but can be useful if you want to be able to output several parse errors.

[register-parse-error]: https://hackage.haskell.org/package/megaparsec-9.0.0/docs/Text-Megaparsec.html#v:registerParseError

**Comment by complyue** [comment]
Thanks! mmark will be a great reference, I'm aware of `registerParseError` but haven't started using it by far.

I'm surprised that searching within mmark's codebase for `registerParseError` but with no hit, why mmark doesn't use this tactic?

**Comment by mrkkrp** [comment]
MMark performs parsing is two passes. First pass parses top-level structure, and is not fault-tolerant, AFAIR. The second pass is done in "parallel" on many fragments and each fragment can potentially be malformed. Parsing errors are then combined and presented to the user.

**Comment by complyue** [comment]
Thanks @mrkkrp , I'll read through MMark's codebase to understand this idea.
