### ISSUE TITLE
parseMaybe parsing eof is unintuitive 

### ISSUE THREAD

**Issue by AlistairB** [mrkkrp/megaparsec#433]
Hi,

I've burnt a couple of hours due to `parseMaybe` and the `This function also parses eof, so if the parser doesn't consume all of its input, it will fail.`. It usually involves being very confused why the parser is failing. I then switch to `parse` to get more info on the failure, but of course `parse` works. Lots of head scratching later I check the docs and notice this. And I did this twice because I forgot about it whoops :sweat_smile: 

It feels unintuitive that `parse` and `parseMaybe` have different parsing behaviour. I'm curious on the reasoning for `parseMaybe` also parsing `eof`?

**Comment by mrkkrp** [comment]
`parseMaybe` is for using a parser quickly as a standalone tool. Usually you want to consume all input in this case.

At this point we can't change the behavior. It is a good habit to read docs carefully before you do anything.

**Comment by AlistairB** [comment]
ok thanks for the response.
