### ISSUE TITLE
utf-8 encoded char fails to parse

### ISSUE THREAD

**Issue by kfiz** [mrkkrp/megaparsec#435]
Attempting to parse utf-8 characters "äöü" surprisingly fails in megaparsec on macOS and linux:
```
λ> parseTest (some (printChar :: Parsec Void Text Char)) "äöü"
"\228\246\252"
```
Is this the expected behavior?

**Comment by mrkkrp** [comment]
It doesn't look like it's failing. Perhaps you are confused by the string literal `"\228\246\252"`? It is Haskell's string syntax for encoding such characters. They characters are not lost or corrupted. We can print them back:

```
> parseTest (some (printChar :: Parsec Void Text Char)) "äöü"
"\228\246\252"
> putStrLn "\228\246\252"
äöü
```

**Comment by kfiz** [comment]
Thanks for the clarification, I obviously didn't know that. But don't you think that a megaparsec user would expect a parser to return the chars after a successful match in the same human readable format as the input chars?

**Comment by mrkkrp** [comment]
Megaparsec does exactly that. The way they are printed back in the REPL is a consequence of the design of Haskell as a language, specifically its syntax for string literals.
