### ISSUE TITLE
How to get source positions efficiently?

### ISSUE THREAD

**Issue by valmirjunior0088** [mrkkrp/megaparsec#440]
Hello!

In the documentation, it is mentioned that the `getSourcePos` [function is not cheap, do not call it e.g. on matching of every token, that's a bad idea](https://hackage.haskell.org/package/megaparsec-9.0.1/docs/Text-Megaparsec.html#v:getSourcePos).

The thing is, to be able to construct meaningful errors with precise source positions, I need to call this function before almost every other token.

Is there any other, more efficient, way of doing this?

**Comment by mrkkrp** [comment]
The way this is done by default is that we store offsets (which are cheap to obtain) in error messages and then convert offsets to positions when we need to present error messages to the user.

**Comment by valmirjunior0088** [comment]
Okay. Thanks!
