### ISSUE TITLE
makeExprParser and precedence

### ISSUE THREAD

**Issue by lucadp19** [mrkkrp/megaparsec#443]
While trying to parse an extended-STLC kind of language I've run into a little problem with `makeExprParser` and operator precedence. In order to make a really minimal example, consider this language:

    data Term
        = LitZero
        | Succ Term
        | Add Term Term

The parser I tried to write was the following:

    parseSingle = choice
        [ parens parseOp
        , LitZero <$ symbol "0"
        , symbol "succ" *> (Succ <$> parseTerm)
        ]

    parseOp = makeExprParser parseSingle 
        [ [ InfixL $ Add <$ symbol "+" ] ]

but this parser parses `succ 0 + succ 0` as `succ (0 + succ 0)`, instead of the more sensible `(succ 0) + (succ 0)`. The problem is fixed removing the third choice in `parseSingle` and editing `parseOp` like this:

    parseOp = makeExprParser parseSingle
        [ [ Prefix $ Succ <$ symbol "succ" ]
        , [ InfixL $ Add  <$ symbol "+" ]
        ]

but I don't really understand why this works while the first version didn't, or if there is a better way to make it work than to move all the "prefix"-like parsers into `parseOp`.

**Comment by mrkkrp** [comment]
What is the definition of `parseTerm`?

**Comment by mrkkrp** [comment]
In short, I think that `parseTerm` just parses `0 + succ 0`. IOW, having consumed `0` it doesn't stop. I'd be able to tell more if you showed me the definition.

**Comment by lucadp19** [comment]
`parseTerm` in this case was just a synonym for `parseOp`, sorry I forgot to change it.

Anyway, yeah I thought as much. Another way I found to do the same thing was creating three chained parsers, splitting `parseSimple` into two parts:

    parseOp = makeExprParser parseComplex
        [ [ InfixL $ Sum <$ symbol "+" ] ]

    parseSingle = choice
        [ Succ <$ symbol "Succ" <*> parseLiteral 
        , parseLiteral 
        ]

    parseLiteral = choice
        [ parens parseTerm
        , LitZero <$ symbol "0"
        ]

which I think is what `makeExprParser` does automatically if I add the prefix rule for `Succ`.

Thank you anyway for your assistance!
