### ISSUE TITLE
Honour pkgs overrides

### ISSUE THREAD

**Issue by cdfa** [mrkkrp/megaparsec#444]
I'm trying to use megaparsec in a GHCJS project and I ran into some issues:
1. Megaparsecs nix configuration runs benchmarking by default, which causes a huge closure size ([~2.3GB ](https://hydra.nixos.org/build/136840467#tabs-details)). I'm not sure if this is common for packages, but it seems a bit unnecessary to me.
2. Megaparsecs nix configuration does not honour overrides on the `pkgs` argument. Specifically, this code:
https://github.com/mrkkrp/megaparsec/blob/7dda58a2f71090012a5ec0956ba7802f768a09a5/default.nix#L77-L85
overrides any previous overlays (which I need because QuickCheck Terminal tests fail on GHCJS).
After a lot of messing around (I'm still learning Nix), I came up with the following patch:
```diff
diff --git a/default.nix b/default.nix
index c741aeb..c1a1fa9 100644
--- a/default.nix
+++ b/default.nix
@@ -4,6 +4,8 @@
 
 let
 
+  inherit (pkgs.lib) recursiveUpdate composeExtensions;
+
   megaparsecSource = pkgs.lib.sourceByRegex ./. [
     "^CHANGELOG\.md$"
     "^LICENSE\.md$"
@@ -74,12 +76,14 @@ let
     "language-puppet" = doJailbreak super.language-puppet;
   };
 
-  updatedPkgs = pkgs // {
-    haskell = pkgs.haskell // {
-      packages = pkgs.haskell.packages // {
-        "${ghc}" = pkgs.haskell.packages.${ghc}.override {
-          overrides = megaparsecOverlay;
-        };
+  updatedPkgs = recursiveUpdate pkgs {
+    haskell = {
+      packages = {
+        "${ghc}" = pkgs.haskell.packages.${ghc}.override (
+          old: {
+            overrides = composeExtensions (old.overrides or (_: _: {})) megaparsecOverlay;
+          }
+        );
       };
     };
   };
```

It would be even nicer if megaparsec accepted an overrides argument so I would not need to import `nix/nixpkgs/default.nix` myself, but that's just a minor suggestion. I'd be willing to submit a PR if you like!

**Comment by mrkkrp** [comment]
The Nix configuration in the repo is not really for re-use, it's just for the developers to run benchmarks and tests of the dependent packages. Why don't you just use megaparsec that comes from `nixpkgs`?

**Comment by cdfa** [comment]
I would like to use the latest version of megaparsec, but other dependencies prevent me from using a more up-to-date `nixpkgs`. Building it from source seems to be the only way.

**Comment by cdfa** [comment]
Actually, it's rather that I don't know of any nixpkgs version that both has megaparsec 9 and a functioning ghcjs (it seems to be broken for a few months now)

**Comment by mrkkrp** [comment]
You can do something like this:

```nix
let source = pkgs.fetchFromGitHub {
      owner = "mrkkrp";
      repo = "megaparsecn";
      rev = "<rev>";
      sha256 = "<hash>";
    };
in pkgs.haskellPackages.callCabal2nix "megaparsec" source {}
```

**Comment by cdfa** [comment]
I like to reuse nix configurations of packages that have one, but in this case it seems like there is little difference. Feel free to close :)
