### ISSUE TITLE
Link broken: Documentation

### ISSUE THREAD

**Issue by m-ildefons** [mrkkrp/megaparsec#447]
While trying to find the documentation for Megaparsec, I followed the link to the [Hackage page](https://hackage.haskell.org/package/megaparsec) and tried to go to the documentation from there, but the link for the documentation (https://hackage.haskell.org/package/megaparsec-9.0.1/megaparsec-9.0.1/src#documentation) leads to an error 404 page.

**Comment by mrkkrp** [comment]
The readme document that Hackage displays is meant to be read on GitHub. As you can see the link points to the fragment `#documentation`. For it to work there should be a corresponding anchor on the page. GitHub generates those anchors for markdown files, Hackage doesn't. Hackage tries its best to render readmes, but the results are subpar. There is little I can do about it.

Please click: https://github.com/mrkkrp/megaparsec#documentation

**Comment by m-ildefons** [comment]
Thanks for the quick reply! That makes sense, although I still find it a bit confusing, because the documentation paragraph only leads back to Hackage, but then again, I don't see how this could be fixed.
