### ISSUE TITLE
Can Ord constraint on streams be removed/moved?

### ISSUE THREAD

**Issue by clintonmead** [mrkkrp/megaparsec#451]
I've split my parsing into a lexing and parsing process, with the lexer being a `Parsec Text Text [Lexeme]` and the parser being a `Parsec Text [Lexeme] Result`. But I've got the problem that `Lexeme` is not `Ord`, nor can it automatically derive from `Ord`, and whilst I can hack up an `Ord` instance it's quite ugly.

I was wondering what the reason is for the `Ord a` constraint on streams in `instance Ord a => Stream [a]`, and whether it can be removed and/or moved to the level of the combinators which actually require it?

**Comment by mrkkrp** [comment]
The need for an `Ord` instance comes from the fact that `ErrorItem`s are kept in `Set`s in `ParseError`s.
