### ISSUE TITLE
dbg without Show

### ISSUE THREAD

**Issue by bradrn** [mrkkrp/megaparsec#455]
`Text.Megaparsec.Debug.dbg` is extremely useful for debugging parsers, but has a `Show` constraint on the parser output, which is inconvenient in the rare cases where the output cannot be `show`n. Would it be possible to have another debugging function which does not print the output and so can be used with un`show`able values? (So something like `dbgSilent :: (VisualStream s, ShowErrorComponent e) => String -> ParsecT e s m a -> ParsecT e s m a`. I’m willing to have a go at implementing it myself if we agree on a design.)

**Comment by mrkkrp** [comment]
Could it be solved by wrapping the output with some type that has a dummy `Show` instance?

**Comment by bradrn** [comment]
@mrkkrp It could, but if I’m just temporarily wrapping each parser in `dbg`, I don’t necessarily want to go to the trouble of making a new wrapper type with a custom `Show` instance. (And it has to be custom: because the underlying type is un`show`able, I can’t just do `deriving Show`.)

This does suggest one other solution: create a newtype `Text.Megaparsec.Debug.Unshowable` such that `show (Unshowable _) = "<cannot show type>"`, after which the user can do `getUnshowable . dbg . Unshowable $ _parser`. But I’m not sure this is better than my first idea.

**Comment by mrkkrp** [comment]
If you define

```haskell
dbg' lbl parser = getUnshowable <$> dbg lbl (Unshowable <$> parser)
```

It can be used as a drop-in version of `dbg` with the difference that the result will not be showed; it sounds exactly like the function you wanted to add. I'm fine with adding something like this to the library, but I'd prefer it to be implemented this way.

**Comment by mrkkrp** [comment]
I've just added `dbg'`. I'll release a new version shortly.

**Comment by bradrn** [comment]
Thanks @mrkkrp!
