### ISSUE TITLE
Compatibility with transformers 0.6

### ISSUE THREAD

**Issue by sjakobi** [mrkkrp/megaparsec#458]
https://hackage.haskell.org/package/transformers-0.6.0.0/changelog

Could you upload a compatible release or make a Hackage revision?

Note that https://github.com/haskell/mtl/issues/88 will probably need to be addressed first.

**Comment by mrkkrp** [comment]
I allowed `transformers-0.6`, but it won't make any difference until `mtl` is compatible with it.

**Comment by mrkkrp** [comment]
I'm going to watch that `mtl` issue you opened. Will bump the `mtl` version bound as soon as they release a new version.

**Comment by sjakobi** [comment]
> I allowed `transformers-0.6`, but it won't make any difference until `mtl` is compatible with it.

That might have been a mistake. With the current `mtl` `master`, I'm getting:
```
Text/Megaparsec/Internal.hs:334:10: error:
    • Could not deduce (Stream s)
        arising from the superclasses of an instance declaration
      from the context: Monad m
        bound by a quantified context at Text/Megaparsec/Internal.hs:1:1
      Possible fix:
        add (Stream s) to the context of
          a quantified context
          or the instance declaration
    • In the instance declaration for ‘MonadTrans (ParsecT e s)’
    |
334 | instance MonadTrans (ParsecT e s) where
    |          ^^^^^^^^^^^^^^^^^^^^^^^^

Failed to build megaparsec-9.2.0
```

**Comment by mrkkrp** [comment]
Once there is a new release of `mtl` I can make a release of Megaparsec that will work with it.
