### ISSUE TITLE
Parsers for Word16, Word32, Word64 (BE and LE)

### ISSUE THREAD

**Issue by raehik** [mrkkrp/megaparsec#459]
(Half issue, half PR.) I'm doing some binary format parsing and was surprised to find that there's not much on Hoogle for obtaining unsigned integers like Word16. I ended up having to use some monadic Get computation from `binary`, which also had me converting my strict ByteString to a lazy one. Wasn't happy, wrote a helper library for Megaparsec to parse `[Word8]` to the various other Word types.

Would this be useful as an extra library to Megaparsec, or would you maybe consider adding it directly? I feel like it's handy for binary format parsers. Attoparsec has a simple package `attoparsec-binary`, but it's long been unmaintained.

The aim being to provide a handful of parsers for doing things like:

```haskell
userParser = do
...
  value1 :: Word32 <- anyW32LE
  value2 :: Word16 <- anyW16BE
  value3 :: Word64 <- anyLE
...
```

And knowing that it works on any stream of `Word8` tokens with OK performance. Is this the sort of thing other Megaparsec users might find useful?

---

I have an initial library at https://github.com/raehik/megaparsec-binary . It's <100 SLOC and has no additional dependencies. The API is not well thought-out (function names etc).

**Comment by mrkkrp** [comment]
I think it would be a great addition! Please open a PR :)

**Comment by raehik** [comment]
Yay! I'm working on it at #460 .
