### ISSUE TITLE
Please bump minimum version of 'scientific' to 0.3.7.0

### ISSUE THREAD

**Issue by lechner** [mrkkrp/megaparsec#461]
Probably related to #425:

I had to specify a historical version to build @srid's [tagtree](https://github.com/srid/tagtree) on Debian bullseye with `cabal install --lib --constraint 'megaparsec == 9.0.0'`

A likely explanation came courtesy of `hpc` on `Libera:#haskell`: 

> megaparsec added the safe haskell extension, which means (among other things) that module can only import other safe modules but the dependency constraints include versions of scientific that don't have the safe haskell extension on that module it's importing

Hope that helps!

**Comment by mrkkrp** [comment]
Thanks for notifying me! Resolved in f87298a611c4b4db452cbe4d4a0190c3ab6a4c33; I also made a Hackage revision.
