### ISSUE TITLE
Better error message when using `notFollowedBy` with parsers that don't partially consume input

### ISSUE THREAD

**Issue by TotallyNotChase** [mrkkrp/megaparsec#468]
`notFollowedBy` currently produces somewhat unintuitive error messages when used with parsers such as `char`, `string` and so on - essentially parsers that either fully fail (without consuming anything) or fully succeed (by consuming). No notion of partial consumption with later failure.

Here's an example-
```hs
> parseTest (notFollowedBy (string "ab")) "ab"
1:1:
  |
1 | ab
  | ^
unexpected 'a'
```
But it really should've said-
> unexpected "ab"

This can be demonstrably problematic in certain cases of ambiguity, such as-
```hs
lookAhead (char '\r') *> notFollowedBy (string "\r\n")
```
i.e, a parser that is completely fine with a CR that follows, unless it's actually a CRLF.
```hs
> parseTest (lookAhead (char '\r') *> notFollowedBy (string "\r\n")) "\r\n"
1:1:
  |
1 |
  | ^
unexpected carriage return
```

(Note that I'm not asking for the error message to contain expected tokens - that should be handled by the parsers wrapping around `notFollowedBy`)

**Comment by mrkkrp** [comment]
Unfortunately, `notFollowedBy` has no way of knowing what its argument parser expects (that would be the thing it'd declare as unexpected), because when `notFollowedBy p` fails, `p` actually succeeds. We do here the next best thing: we examine the input stream and pick the first token from there, unless the stream is empty, in which case we claim that end of input is unexpected.

**Comment by TotallyNotChase** [comment]
Hmm, I see. I'm curious if it would be possible to report using the label (if any) instead. For `string "\r\n"` - I assume the label is just `"\r\n"`. But even for regular parsers, the label usually signifies the "expected item", whether singular (in case of `takeWhileP`) or all at once (in case of `string`). Of course, when used with `notFollowedBy` the label for "expected item" *is* the unexpected item.

I think it'd be a more intuitive substitute to naming the first token in a stream (since in this case the token(s) can be named by the user). But I assume it's currently not possible to inspect the label of a certain parser?

**Comment by mrkkrp** [comment]
A label is just another form of expected input that a parser reveals when it fails, it cannot be inspected for the same reason.

**Comment by TotallyNotChase** [comment]
Ah, unfortunate. Is there no workaround for this then? Other than being aware of a parser's label before hand to manually raise it at call site?

**Comment by mrkkrp** [comment]
I'm not aware of a solution other than a big refactoring or adding another version of `notFollowedBy` that would take `Maybe String` as a kind of explicit label to report.
