### ISSUE TITLE
Unnecessary major version bumps

### ISSUE THREAD

**Issue by sjakobi** [mrkkrp/megaparsec#469]
The recent 9.1.0 and 9.2.0 releases didn't introduce [any breaking changes](https://hackage.haskell.org/package/megaparsec-9.2.0/changelog) AFAICT. Nevertheless they were major releases according to the PVP.

In the `dhall` project, we use upper bounds on our dependencies to avoid compilation failures when dependencies introduce breaking changes. Therefore, the mentioned `megaparsec` releases caused us a bit of work: https://github.com/dhall-lang/dhall-haskell/pull/2258, https://github.com/dhall-lang/dhall-haskell/pull/2311.

I was wondering whether you would consider using major version bumps more sparingly, to avoid causing maintenance work for downstream packages like `dhall`.

**Comment by mrkkrp** [comment]
Well, Megaparsec follows SemVer, as it has 3 components in its version:

```
MAJOR / MINOR / PATCH
```

I bump:

* `PATCH` if a release is just a bug fix.
* `MINOR` if new functionality is added (the case in question).
* `MAJOR` if breaking changes were introduced.

**Comment by mrkkrp** [comment]
In my newer packages such as `modern-uri` I use PVP, but the three-component scheme is a bit of a legacy think.

**Comment by sjakobi** [comment]
Thanks for the clarification, @mrkkrp!

If you intend to stick with SemVer, I think it would be very helpful if this was documented somewhere on the Hackage page.

A brief note or reference at the top of the changelog would also be very handy!

**Comment by mrkkrp** [comment]
I have add a note to the changelog: 3cf7549244eed2e6881663ef491ac6a31bf5bab9.
