### ISSUE TITLE
Get the left input in failure or success

### ISSUE THREAD

**Issue by chamini2** [mrkkrp/megaparsec#47]
Hi, I'm developing an interpreter and was using Parsec for some preprocessing of an Abstract Syntax Tree, while developing I asked on [StackOverflow how to get the input wether the parser succeeds or not](http://stackoverflow.com/questions/32813797/get-parsecs-left-input), and have changed to using megaparsec since your announcement in the mailing list.

I don't need this feature anymore, but it may be a good idea to have this option anyway.

**Comment by mrkkrp** [comment]
I currently do not consider this as something we should have in Megaparsec. However, let it hang here and if more people request it, providing realistic cases where such a feature would be useful, we will return to the issue.

**Comment by tulcod** [comment]
This is impressive coding. Just by refactoring some internals, Mark fixed an issue he was not even intending to fix. Great work again.
