### ISSUE TITLE
Support text 2.0

### ISSUE THREAD

**Issue by kozross** [mrkkrp/megaparsec#472]
Currently, the bounds on `megaparsec` prohibit `text-2.0`. Given the significant improvements in performance that `text-2.0` brings, it'd be good to have this supported. It shouldn't require anything other than bounds changes - `--allow-newer` makes the build work fine.

**Comment by Kleidukos** [comment]
I would greatly benefit from this as well!

**Comment by mrkkrp** [comment]
I have also updated the dependency on Hackage.

**Comment by kanashimia** [comment]
> I have also updated the dependency on Hackage.

@mrkkrp it seems those revisions on hackage don't update tarball which nixpkgs uses to fetch deps, and then build fails with unmet deps, i've wasted many minutes on this :moyai: 
This is a nixpkgs tooling problem, just let you know.
