### ISSUE TITLE
Why is `Stream s` requiring `Ord (Token s)`?

### ISSUE THREAD

**Issue by janmasrovira** [mrkkrp/megaparsec#474]
To me it is not intuitive to require that tokens of a stream must have an order. I guess there must be a reason for that, but I haven't been able to find it by reading the documentation of the library.

**Comment by mrkkrp** [comment]
See #451

**Comment by janmasrovira** [comment]
I see. 
Have you considered using HashSet instead of Set , then requiring `Hashable` and `Eq` instead of `Ord`?

I think it would be good for the library to be able to parse streams of tokens which have no sensible `Ord` definition.

**Comment by mrkkrp** [comment]
I'd say that the main problem right now is compatibility. Besides, if you can define `Hashable` for your type, then you probably can also define some kind of `Ord` by doing comparisons on the resulting hashes, right?

**Comment by janmasrovira** [comment]
> Besides, if you can define Hashable for your type, then you probably can also define some kind of Ord by doing comparisons on the resulting hashes, right?
Yes, this is a good idea.

**Comment by janmasrovira** [comment]
I have a followup question. Is the `Ord` constraint only used for error reporting, or is it a structural part of the parsing algorithm?

**Comment by mrkkrp** [comment]
It is used to construct `ParseError` values (which uses `Set`s) which is hardwired in the library, but not for parse error rendering/reporting per se.

**Comment by mrkkrp** [comment]
Closing for now.

**Comment by janmasrovira** [comment]
Thank you for your answers @mrkkrp!
