### ISSUE TITLE
Consume "inline" spaces (or simply ignore spaces entirely)

### ISSUE THREAD

**Issue by Rafaeltheraven** [mrkkrp/megaparsec#475]
I'm working on parsing an esoteric language which takes inspiration from early versions of FORTRAN. In these early versions, whitespace was completely ignored, meaning that `IDENTIFIER` and `IDENT IFIER` mean the exact same thing. Because of other stipulations, I am not able to simply remove all whitespace. Is it possible in megaparsec to do something like this?

I was thinking it might be possible to just parse character by character, but I'm not sure if that's the fastest setup

**Comment by mrkkrp** [comment]
Perhaps you could add whitespace to all lexemes e.g. identifier would be `many x` where `x` matches letters, digits, and white space but not other characters that could start other constructs, etc. If you define every lexeme like this, I imagine that whitespace will be accepted at arbitrary positions and completely ignored.

**Comment by Rafaeltheraven** [comment]
Wouldn't `many x` in this case just also include the whitespace though? My current identifier looks as follows:
```
identifier :: Parser String
identifier = (lexeme p)
    where
        p  = (takeWhile1P (Just "anyCharacter") f) <?> "variable"
        f x = not (x == '.')
```
(this could be implemented with `many` as well, which shows the same behaviour).

This does indeed allow spaces inside of variables, but it does not ignore them, so you still have a difference between `IDENTIFIER` and `IDENT IFIER`, or do I not fully understand your suggestion?

**Comment by mrkkrp** [comment]
You can filter spaces out from the parsed `String`.

**Comment by Rafaeltheraven** [comment]
Ah yes, I may be stupid. Sometimes it's easy to get so wrapped up in convoluted solutions you forget the simple ones :P
