### ISSUE TITLE
Space leak in reachOffset'

### ISSUE THREAD

**Issue by tomjaguarpaw** [mrkkrp/megaparsec#486]
The `SourcePos` field of `St` is lazy:

https://github.com/mrkkrp/megaparsec/blob/cd6302d9b9e21f0de7a895da686c94d834437b73/Text/Megaparsec/Stream.hs#L358

This causes a space leak in reachOffset':

https://github.com/mrkkrp/megaparsec/blob/cd6302d9b9e21f0de7a895da686c94d834437b73/Text/Megaparsec/Stream.hs#L419-L436

Although the `St` constructor remains evaluated each time around the `foldl'` iteration, the `SourcePos` inside does not. Instead it accumulates a large thunk.

Now, this doesn't affect `megaparsec` itself, because it only uses `reachOffset'` to derive `reachOffsett` methods and the `reachOffset` methods are never used within the library itself. However, a problem can arise if a client defines a `TraversableStream` whose `reachOffsetNoLine` method is derived from its `reachOffset`. If that `reachOffset` uses `reachOffset'` directly, or indirectly by using one of the built in `TraversableStream` instances, then the space leak will manifest itself.

Given that `reachOffset` seems no longer used by `megaparsec` perhaps the best long term fix is to deprecate then remove that method. In the short term perhaps you could make that field strict again.

The `SourcePos` field was made lazy in e3072661adcb7169ac6b9e6729a6b92dd44ba632 but I don't understand why. I can hardly imagine that allowing this space leak is good for performance.

**Comment by mrkkrp** [comment]
IIRC this was a conscious decision. `reachOffset` is supposed to be used only when parsing is finished as part of error reporting. Its performance therefore doesn't matter as much because it will be evaluated only in "parse failure" branches of execution flow. I remember that I profiled some parsers and making that field lazy gave some noticeable performance improvement, so I made it lazy.

I'm open to either updating the documentation to mention this possible performance problem or making the field strict provided the benchmarks are not getting any worse.

**Comment by mrkkrp** [comment]
It may be that my memory deceives me though. Happy to make this strict provided there is no performance regression.

**Comment by tomjaguarpaw** [comment]
> the `reachOffset` methods are never used within the library itself

I just realised this isn't true. `reachOffset` is used in `errorBundlePretty`, so it's even more imperative to fix this issue.

Is there any circumstance in which one would call `reachOffset` but *not* evaluate the `PosState` it returns? If not then it makes no sense to make that field of `St` lazy. If it's lazy you still do exactly as much computation updating the `PosState`, plus additional computation creating and entering thunks, plus consume additional amounts of memory proportional to `o - pstateOffset`.  The constant factor on the memory usage is large, tens of bytes at least, so if you are parsing a 10 MB file you can easily consume 1 GB just to report errors.

**Comment by tomjaguarpaw** [comment]
## `master`

Uses 2.4 MB to report errors in a 10 kB input stream, an overhead of 24x! (Naturally, the size of the space leak scales linearly with the size of the input file.)

![screenshot0](https://user-images.githubusercontent.com/1951567/187629491-5cbb6ba7-1d2e-4fbc-8425-fc2c4cde44b7.png)

## Strict `SourcePos` in `St`

The space leak is gone.

![screenshot1](https://user-images.githubusercontent.com/1951567/187629566-a85a5d48-c5c4-4d96-9392-6e30a4fe64bf.png)

## Code

<https://github.com/tomjaguarpaw/megaparsec-bug>

**Comment by mrkkrp** [comment]
Would you like to open a PR?

**Comment by tomjaguarpaw** [comment]
OK: https://github.com/mrkkrp/megaparsec/pull/487
