### ISSUE TITLE
Export all of original parsec's combinators

### ISSUE THREAD

**Issue by recursion-ninja** [mrkkrp/megaparsec#49]
For easy of adoption you should export all of Parsec's useful combinators.

`many1` and `spaces` are missing amongst others.

Forcing users to define these manually will likely lead to people not adopting the new library as they will not have a clean "drop-in" substitution.

**Comment by tulcod** [comment]
Some of these combinators have different semantics than Parsec's. Code will not work as-is, even with a fake translation layer.

`many1` is not really "missing", it's a misnomer that has been purged. `some` is the new `many1`. Either the translation is easy, and might as well be done manually in translating code from Parsec to Megaparsec, or it is not easy, and cannot be done by merely adding drop-in lookalikes.

**Comment by neongreen** [comment]
> `some` is the new `many1`

It should really be mentioned in `Text.Megaparsec.Combinator` (in fact, it should be reexported properly, because people won't notice it if it's simply mentioned in module description).

**Comment by neongreen** [comment]
Hm, on the other hand they are all reexported in [Text.Megaparsec.Prim](http://hackage.haskell.org/package/megaparsec-4.0.0/docs/Text-Megaparsec.html#g:2), so perhaps merely adding a link in Text.Megaparsec.Combinator would be enough after all.

**Comment by mrkkrp** [comment]
@recursion-ninja, This library has different naming conventions. `many1` is called `some` and `spaces` is called `space`. There is nothing you need to define manually, just read the documentation. Some of combinators are placed in different modules, but there are reasons for it, *this is different library*.

@neongreen, I don't think we should mention this. The library is a fork and it's similar to Parsec and it does all the things Parsec does, but of course a bit differently. *The library should be self-sufficient and we should stop define it in terms of Parsec.* I don't like this trend “please look like Parsec or you will be never widely used”. There will be not a single step in that direction, that's not what I wanted when I started to work on this.

Closing this.

**Comment by recursion-ninja** [comment]
At the time I made this suggestion I didn't realize that Megaparsec was diverging from Parsec with breaking changes to be a better standalone parsing library, not an improvement to Parsec.

The new documentation does clear this up!
