### ISSUE TITLE
Does there already exist functionality for lexing a little further to generate better "unexpected" error messages

### ISSUE THREAD

**Issue by expipiplus1** [mrkkrp/megaparsec#502]
For example

```haskell
foo = parseTest p "bar"
 where
  p :: Parsec Void String String
  p = dot >> ident
  ident = takeWhileP Nothing isAlpha
  dot = single '.'
```

To parse my language `.someIdent`. 

Currently this generates the error message:

```
1:1:
  |
1 | bar
  | ^
unexpected 'b'
expecting '.'
```

However in this language `ident` is an atom, so the user would be better helped by getting a message like `unexpected 'bar', expecting '.'`. 

One could currently:
- Use `region` to enhance the error messages freely
- Lex first and parse on that stream
- Wrap all the lexemes with some code to parse any other lexeme then fail (probably the nicest way)

These all seem a little cumbersome..

Outside the parser it's really not terribly hard to just extend this after the fact, so I suppose that this isn't actually a super important request!

**Comment by mrkkrp** [comment]
I think I wanted to do something like this a while ago, but it is not really possible. At the time when we try to match we only know what we want and what we've got on the token level. Labels are not in the picture.

**Comment by mrkkrp** [comment]
Closing for now, feel free to reopen if needed.

**Comment by expipiplus1** [comment]
thanks :)

Happy to have this closed.
