### ISSUE TITLE
Question: mergeError

### ISSUE THREAD

**Issue by horus** [mrkkrp/megaparsec#506]
Hello,

I am currently studying the code. I have the following question:
https://github.com/mrkkrp/megaparsec/blob/b054083a496f8339ac8f72c41ea1b7317775a43b/Text/Megaparsec/Error.hs#L235
Why `n = max` isn't enough here or did I miss something relevant?

Thanks in advance!

**Comment by mrkkrp** [comment]
It might be that I just did not think of  the instance `Ord a => Ord (Maybe a)`. I imagine it does exactly the same as the code you quote. In that case, `n` could be `max`.

**Comment by horus** [comment]
Thank you very much for your reply. That clarifies my question.
