### ISSUE TITLE
A failing test (GHC 7.8.4)

### ISSUE THREAD

**Issue by mrkkrp** [mrkkrp/megaparsec#51]
Somehow one of tests [failed](https://travis-ci.org/mrkkrp/megaparsec/jobs/83564002#L623-L627). It failed on very simple input. Currently every test is iterated 1000 times. And all other combinations of Cabal/GHC pass the tests. Why this particular test failed is beyond my understanding.

If you have any idea, it's interesting to hear.

**Comment by bkaestner** [comment]
@mrkkrp I just noticed myself and opened an issue. Didn't notice this issue though, apparently it took ~15 minutes to write #52.

Either way, it's a defect in `prop_string'`.

**Comment by mrkkrp** [comment]
@bkaestner, your description is better, so I'll close this.
