### ISSUE TITLE
Processing input prior to parsing while retaining source positions

### ISSUE THREAD

**Issue by bramhaag** [mrkkrp/megaparsec#518]
Prior to parsing, I would like to modify the input to discard certain characters and lines, and process any `#include`-like directives. I still want to report errors in the correct positions in the original input.

I can trivially do this preprocessing on the `String` input, and return a list of `Char` with position information. I can then make a custom `Stream` instance as [described in the tutorial](https://markkarpov.com/tutorial/megaparsec.html#working-with-custom-input-streams) and re-implement the basic parsers to work with my custom `WithPos Char` tokens. In theory this would work, but it seems rather intimidating. 

Is there a better approach to do preprocessing? For example, could I supply a list of `Char` with positional information without creating a new `Stream` instance + parsers, or construct a pre-processing parser and do the parsing in two phases while retaining the original source positions, or maybe do the pre-processing on an existing Stream?

**Comment by mrkkrp** [comment]
Without a new `Stream` instance this is not possible, to my knowledge.
