### ISSUE TITLE
string' test broken

### ISSUE THREAD

**Issue by bkaestner** [mrkkrp/megaparsec#52]
A Travis build [has shown](https://travis-ci.org/mrkkrp/megaparsec/jobs/83564002#L622-L625) that the case-insensitive test doesn't work as intended. A minimal example that shows the defect has also been provided in that build:

    -- prop_string a s
    prop_string "a" "A"

This returns the match `"A"` correctly, but the test expects a matched `"a"` due to the logic in `checkString`. The problem here is that the parser `string' a` doesn't necessarily return `a`, but `s` if the case-insenstive match is successful.

You can reproduce this result with the following property:

```haskell
prop_string'_custom :: String -> Property
prop_string'_custom a = prop_string' (map toLower a) (map toUpper a)
```

**Comment by mrkkrp** [comment]
Initially logic of `string'` was to return string cased as argument of the parser. This later was changed. It's strange that it took so many tests to revel this defect in the test. I'll investigate/fix it tomorrow when I have more clear state of mind. Enough hacking for today.

**Comment by bkaestner** [comment]
> It's strange that it took so many tests to revel this defect in the test.

I've noticed that there are only property based tests, but not any with static values. This behavioural change could have been noticed with static tests. Maybe you want to add some in the future for edge cases? Not for every property, but it might be reasonable for `string'`. You could reuse the already written properties for them.

Either way, take your time. The culprit has been found, and it was "just" in a test, not in `string'` itself.

**Comment by mrkkrp** [comment]
@bkaestner, another approach would be to modify existing test for `string'` so this sort of behavior would manifest itself with greater probability.

**Comment by bkaestner** [comment]
Hm. Something like this comes to mind:

```haskell
-- Randomly change the case in the given string
fuzzyCase :: String -> Gen String
fuzzyCase s = do
    b <- vector (length s)
    return $ zipWith f s b
  where f k True  = if isLower k then toUpper k else toLower k
        f k False = k

prop_string'_fuzzied :: String -> Property
prop_string'_fuzzied a =
  forAll (fuzzyCase a) $ \s ->
   checkString (string' a) a casei (showToken a) s
```

This would test `string'` with a string that only differs in case.

**Comment by mrkkrp** [comment]
@bkaestner, I've fixed that bug (it was trivial `Right a'` → `Right s'` in definition of `checkString`). I think I'll add your `prop_string'_fuzzied` to the test suite.
