### ISSUE TITLE
`local` clears all hints

### ISSUE THREAD

**Issue by Lev135** [mrkkrp/megaparsec#528]
I was very surprised, when observed this. Maybe we should add a note for `MonadReader` instance, if we can't implement this better?

**Comment by mrkkrp** [comment]
Does this section of the tutorial help? https://markkarpov.com/tutorial/megaparsec.html#the-monadparsec-type-class

**Comment by Lev135** [comment]
> Does this section of the tutorial help? 

As far as I understood the section in the tutorial is about the influence of parsing on other effects (like backtracking state). However, here I have the converse problem. I had a simple parser 
```hs
p = optional (string "a")
```
I expected, that `local (+ 1) p` should behave exactly as the `p` itself (we are changing environment, which is not used). However, it's not true! The call of local clears hints:
```hs
run p = case runParserT p "" "b" `runReader` 0 of
  Left peb  -> putStrLn $ errorBundlePretty peb
  Right str -> print str
```
```
run (p <* hidden eof)
1:1:
  |
1 | b
  | ^
unexpected 'b'
expecting 'a'
```
```
run (local (+ 1) p <* hidden eof)
1:1:
  |
1 | b
  | ^
unexpected 'b'
```

I found that this is due to the use of calling `runParsecT` in `local`, which seems to clear all hints. It's a bit strange that hints can't be preserved when the environment changes. But even if it's so, I think this should be documented in the `MonadReader` instance for `ParsecT`

**Comment by mrkkrp** [comment]
This is the only way to define `local` for `ParsecT`. You have to delegate to `local` on the inner monad, and to do that you have to run the `ParsecT` monad to get to the inner `m` monad. You are welcome to try to improve on this.

What happens when you try the other way around, e.g.:

```haskell
p :: ReaderT Int (Parsec Void String) (Maybe String)
p = optional (chunk "a")

run :: Show a => ReaderT Int (Parsec Void String) a -> IO ()
run x = case runIdentity (runParserT (runReaderT x 0) "" "b") of
  Left peb  -> putStrLn $ errorBundlePretty peb
  Right str -> print str
```

I think this might allow `ParsecT` bind without interruption and so hints should work.

**Comment by Lev135** [comment]
It seems like we can fix this easy just by adding `Hints` to `Result`. 
I've added this in my [fork](https://github.com/mrkkrp/megaparsec/compare/master...Lev135:megaparsec:preserve-hints ). `local` in the simplest test case works as expected. I haven't tested other transformers but I hope they will work fine. I'm not sure about `MonadCont` and `MonadFix` instances -- to be honest, I haven't ever used them and don't understand properly, how they should work.

**Comment by mrkkrp** [comment]
I quite like this idea, actually. Would you like to open a PR with this change?
