### ISSUE TITLE
Remove/upgrade version bounds of executable `test-debug` from megaparsec-tests 

### ISSUE THREAD

**Issue by Lev135** [mrkkrp/megaparsec#537]
I've added it to test `MonadParsecDbg` ouput. If I understood correctly it isn't currently needed, since we have automatic tests for trace output. If you prefer to keep it for some reasons we should update version bounds for it (now cabal fails to build `megaparsec-tests` since `test-dbg` only works with `megaparsec=9.2.2`)

**Comment by mrkkrp** [comment]
Sorry, I don't know what `test-dbg` is. There is no such executable in `megaparsec-tests`. Can you clarify?

**Comment by Lev135** [comment]
Oh, I'm sorry, that's my fault. Somehow merged my local changes in the main branch of my fork.
