### ISSUE TITLE
get col, row (as Int's) and error message of the first TrivialError

### ISSUE THREAD

**Issue by KeesBleijenberg** [mrkkrp/megaparsec#544]
The tutorial is not clear to me. It is about displaying error messages, not getting the value of the col and row. 
I can get the offset of an error. But how do I calculate the col and row from the offset?

**Comment by mrkkrp** [comment]
I think you are looking for [`attachSourcePos`](https://hackage.haskell.org/package/megaparsec-9.5.0/docs/Text-Megaparsec-Error.html#v:attachSourcePos). You can run your parser with [`runParser'`](https://hackage.haskell.org/package/megaparsec-9.5.0/docs/Text-Megaparsec.html#v:runParser-39-) to get `PosState s` (it will be inside `State s e`).

**Comment by KeesBleijenberg** [comment]
Thank you. This solved the problem.
