### ISSUE TITLE
How to use `Operator` from tutorial

### ISSUE THREAD

**Issue by ju-sh** [mrkkrp/megaparsec#558]
Hi.

I was trying to go through the tutorial at
https://markkarpov.com/tutorial/megaparsec.html

There we set up an operator table, right?

But `Operator` was removed from megaparsec.
I guess we should use it from parser-combinators now.

But I couldn't figure out how to even import parser-combinators.
Name clashes?
How we use the `Operator` table for the tutorial example for parsing `Expr`?

**Comment by mrkkrp** [comment]
Well, without a more concrete description of your situation I'm not sure where the difficulty arises. The tutorial is up to date, it states explicitly that you should depend on `parser-combinators` and import `Control.Monad.Combinators.Expr`.

**Comment by ju-sh** [comment]
Oh, it is?

Sorry, then it's my goof up.
I must not have copy pasted all of it properly.
