### ISSUE TITLE
Show errors in more standard format

### ISSUE THREAD

**Issue by Toxaris** [mrkkrp/megaparsec#56]
The format of the location information in error messages generated by parsec is unusual, which makes it harder to provide basic IDE support for languages with parsec-based implementations. For example, I often write code like [in this commit](https://github.com/tewe/uroboro/commit/c67e6553f6c04a3fa8bafda33a2e044a1d0aeb92) to help Emacs jump to locations in parsec errors. Megaparsec could improve on this by making it easier to customize the formatting and/or by choosing a more default default.

**Comment by recursion-ninja** [comment]
Couldn't you get the list of error messages on a failure, or are you entirely reliant on the stringified results of `show :: ParseError -> String`? 

*Example*

```case result of
  Left x -> f $ errorMessages x
  Right _ -> undefined
  where f = undefined -- Your code to operate on the errors```

**Comment by Toxaris** [comment]
Yes, that's what I'm doing. More precisely, something like this:

~~~haskell
Left err -> 
  let pos = errorPos err
      name = sourceName pos
      line = sourceLine pos
      column = sourceColumn pos
      messages = showErrorMessages
                   "or" "unknown parse error" "expecting"
                   "unexpected" "end of input"
                   (errorMessages err)
  in intercalate ":" [name, show line, show column, "Syntax Error"] ++
     (unlines $ map ("  " ++) $ lines $ message)
~~~

That's relatively complicated for such a simple task, and I have to lookup how to call `showErrorMessage` in the sources as well as figure out the API for source positions.

**Comment by mrkkrp** [comment]
@Toxaris, rendering of error messages (i.e. everything except for the first line with file name, line number, and column number) is done with `showMessages` function, which is hopefully more handy than Parsec's `showErrorMessages`. Its type looks like this:

```haskell
showMessages :: [Message] -> String
```

When I first saw `showErrorMessages` it made me choke. Absolutely naïve idea of passing words into this function in hope to make it “international”. Has it even occurred to the author of Parsec that translation into different language is not done by one-to-one word substitution? Even if we consider only punctuation, list separated by commas with “or” / “and” at the end looks differently in different languages. I only speak three languages: Russian, English, and French and it's different in them all (punctuation); I can imagine this approach is even less applicable for eastern languages like Arabic and Japanese. So, let's focus on English alone for now.

----

What you're asking is worth consideration. That part about better default representation is. I don't see how I can make easier custom rendering of error messages. If you want it, you'll obviously have to write some Haskell.

Although I use Emacs on daily basis I don't know whether it expects quoted file names when they contain space…

**Comment by Toxaris** [comment]
Oh `showMessages` sounds like a nice improvement indeed. Sorry for not checking out what you already improved before posting here.

A better default would still help me. Maybe there is a standard format that is understood by many tools, not just emacs?

**Comment by mrkkrp** [comment]
@Toxaris, The format has been changed in b062a39, the new default should be satisfactory.

**Comment by Toxaris** [comment]
thanks :+1:
