### ISSUE TITLE
runParser function that receives initial SourcePos

### ISSUE THREAD

**Issue by chamini2** [mrkkrp/megaparsec#57]
I looked for a function that did this, and none seemed to do it. If we are parsing certain parts of a file, we may want to set the initial `SourcePos` to something different than `1`, `1`.

This could be easily implemented with

    runParserInitPos :: Stream s t => Parsec s a -> String -> Int -> Int -> s -> Either ParseError a
    runParserInitPos act src lin col str = runParser (setPosition pos >> act) src str
        where
            pos :: SourcePos
            pos = newPos src lin col

But this may be a good function to have exposed to the users.

**Comment by mrkkrp** [comment]
Well, in may be implemented on lower level if we place it in `Text.Megaparsec.Prim` module. When you run parser, it constructs initial state, which includes position, we could write a bit more general version of `runParserT` that takes the position as argument instead.

Since you open this sort of issue, you probably can explain how this feature would be widely useful in practice?

**Comment by chamini2** [comment]
Well, I'm currently writing an interpreter for a functional programming language that supports *mixfix operators*, these are operators where the *arguments* can be in any part of them, I'll illustrate with an example:

~~~haskell
_+_ : Nat -> Nat -> Nat
Z + n     = n
(S m) + n = S (m + n)
~~~

So we define the operator, indicating where the arguments go with the underscore character `_`, a more complex example is `if_then_else_`

~~~haskell
if_then_else_ : forall x : Type . Bool -> x -> x -> x
if True  then y else _ = y
if False then _ else n = n
~~~

And we have a statement for indicating the fixity and precedence

~~~haskell
operator if_then_else_ prefix 1
operator _+_           infixL 4
~~~

So I first parse the source of a program with [Alex](https://www.haskell.org/alex/) and [Happy](https://www.haskell.org/happy/), and run over the Abstract Syntax Tree to get such `operator` statements, creating rules for a dynamic parser, in Megaparsec.

So in every expression found in the AST, I must run a parser, but just on that part, or at least that's how I'm doing it.

For example, 

~~~haskell
x : Bool -> Nat
x b = S Z + (if b then Z else S Z)
~~~

I want the function definition to become

~~~haskell
x b = _+_ (S Z) (if_then_else_ b Z (S Z))
~~~

I don't know if this classifies as widely used, but I thought more people may want to parse specific parts of some already parsed information, not starting at the position (1, 1) of the information.

**Comment by mrkkrp** [comment]
I think this (along with ability to get rest of input on success and failure) will be added in version 4.2.0, perhaps.
