### ISSUE TITLE
Make expression parser parse repeated prefix/postfix operator

### ISSUE THREAD

**Issue by mrkkrp** [mrkkrp/megaparsec#64]
For more information see this SO question:

https://stackoverflow.com/questions/10475337/parsec-expr-repeated-prefix-postfix-operator-not-supported

Note to self: we cannot remove chaining combinators until this is implemented.

**Comment by mrkkrp** [comment]
I think it should be implemented in 4.2.0, not in 4.3.0. Obsolete combinators of `chain` family fill be removed in 4.2.0 too. This version will be released in December probably, don't want to release it too soon because 4.1.1 should be fine for most users.

**Comment by bartavelle** [comment]
Not sure if this is the appropriate place to ask, but how do can I parse multiple "lookups" with `Postfix`? For example, for the array lookup syntax you can find in several languages:

    [1,[2,3]][1][0]

**Comment by mrkkrp** [comment]
@bartavelle, Unfortunately I have no time right now to write working example, but see in documentation how to parse several unary operators in a row:

https://hackage.haskell.org/package/megaparsec-4.4.0/docs/Text-Megaparsec-Expr.html#v:makeExprParser

Basically, you first write a parser for `[x]` things that should actually allow nested indices and then you:

```haskell
parseManyPostfixIndices = foldr1 (.) <$> some parseOneIndex
```

This should do the trick.

**Comment by bartavelle** [comment]
I should have read the docs! Thanks a lot, and sorry for the noise.

**Comment by jmorag** [comment]
Sorry to rehash this, but I can't for the life of me figure out goes in the `parseOneIndex` space. The type, according to ghci, is `Functor f => f (a -> a)` but it's very unclear to me if that is the expression parser, the term parser, the operator, or something else.

**Comment by mrkkrp** [comment]
@jmorag, `parseOneInex` should parse an index, such as `[1]` for example, and return a function that would change some `a`, which is probably what you want to return from the whole parser, i.e. a term.

For example:

```
my_array[0][1]
```

* `my_array` could on its own return something like `Var "my_array"`.
* The indices could add something like this: `Indexed (Indexed (Var "my_array") 0) 1`. So the function that `parseOneIndex` would return could be: `\x -> Indexed x n`, where `n` comes from whatever you parse in that parser, of course.

**Comment by jmorag** [comment]
Ah, I see. So, to parse multiple prefix operators, as in the example in the haddocks, one would change 
`prefix  name f = Prefix  (f <$ symbol name)` to
`prefix  name f = Prefix $ foldr1 (.) <$> some (f <$ symbol name)`.
Thank you very much for your help, and for writing a great library!

**Comment by xhliu** [comment]
```
opSubscript = Postfix $ foldr1 (.) <$> some singleIndex

singleIndex = do
  index < brackets expr
  return $ \l -> ArrayIndex l index
```
array[1][2] is expected to be parsed as

`ArrayIndex (ArrayIndex (Var "array") 1)) 2`

However, it was

`ArrayIndex (ArrayIndex (Var "array") 2)) 1`

What is going wrong here?

**Comment by xhliu** [comment]
[Fixed](https://www.reddit.com/r/haskell/comments/lfnd3o/issue_when_parsing_array12_using_megaparsec/) with `foldr1 (flip (.))`
