### ISSUE TITLE
Signed numbers are impossible in Text.Megaparsec.Lexeme

### ISSUE THREAD

**Issue by recursion-ninja** [mrkkrp/megaparsec#67]
The `number` combinator in the module `Text.MegaParsec.Lexeme` is very useful, however it only parses unsigned `Integer`s/`Double`s. You cannot apply the `number` combinator as the last argument of the `signed` (eg. `signed space number`) because `Either Integer Double` is not an instance of `Num`. The API feels slightly inconsistent regarding `signed` and `number`.

I was able to construct my own `singedNumber` combinator:

    signedNumber = try (Right <$> signed space float) <|> Left <$> (signed space integer)

However this feels heavy handed. Perhaps there is some possible modification to allow `signed` and `number` compose without a custom definition?

**Comment by mrkkrp** [comment]
Good catch, I'll definitely think how to handle this elegantly.

**Comment by mrkkrp** [comment]
Here is a possible fix via custom `Signed` type class:

```haskell
import Prelude hiding (negate)
import qualified Prelude

…

-- | This type class abstracts the concept of signed number in context of
-- this module. This is especially useful when you want to compose 'sign'
-- and 'number'.

class Signed a where
  negate :: a -> a

instance Signed Integer where
  negate = Prelude.negate

instance Signed Double where
  negate = Prelude.negate

instance (Signed l, Signed r) => Signed (Either l r) where
  negate (Left  x) = Left  $ negate x
  negate (Right x) = Right $ negate x
```

Then change signature of `signed`:

```haskell
signed :: (MonadParsec s m Char, Signed a) => m () -> m a -> m a
```

This will allow to compose all provided numeric parsers with `signed`. Custom `negate` method won't be exported, unlike `Signed` which should be exported at least for the sake of documentation. As far as I can tell this won't break any existing code. I don't think there is a better solution, I also do not find this one perfect too.
