### ISSUE TITLE
Why don't we benchmark the stuff?

### ISSUE THREAD

**Issue by mrkkrp** [mrkkrp/megaparsec#7]
It might be a good idea to benchmark at least basic things. Not sure I can do all the stuff myself, but let it hang here, maybe someone could help in future and write some benchmarks. I think `criterion` library can be used.

**Comment by mrkkrp** [comment]
I think we only need to benchmark “core” of Megaparsec (that is `Text.Megaparsec.Prim`) and generic combinators in `Text.Megaparsec.Combinator`.

**Comment by mrkkrp** [comment]
Help on this issue is appreciated. I haven't started writing benchmarks yet, so pull requests implementing some part of this work are welcomed.

**Comment by tulcod** [comment]
Perhaps the goals of this should be specified a bit more. What do you want to measure? Efficiency of the primitives and combinators? Or do you want to compare "semantic" implementations with not-too-naive "manually written" parsers, or theoretical optimum? Are sample applications relevant?

One thing that I think would be quite interesting is to see if we can find test cases against the kind of inefficiencies regexes are known for.

**Comment by mrkkrp** [comment]
@tulcod, Currently my idea is to measure efficiency of primitives and combinators. This will allow us to detect performance degradation in future. Also, the benchmarks can be used (with minor edits) to measure performance of original Parsec and compare performance of Megaparsec and Parsec. This would be interesting.

**Comment by tulcod** [comment]
I'd like to try to pick this up.

Efficiency or complexity? IOW, do you just want to see a list of timings of a few primitives and combinators (which indeed should be easy enough to generate using criterion)? In that case, which combinations would you like to see (one benchmark per primitive, one benchmark per combinator with fixed primitives as input?)? Should it be in one big benchmark file?

**Comment by mrkkrp** [comment]
I think list of primitive combinators is (from `Text.Megaparsec.Prim`):

* `(<|>)` (re-exported from `Control.Applicative` in Megaparsec)
* `many` ↑ the same
* `some` ↑ the same
* `optional` ↑ the same
* `unexpected`
* `(<?>)`
* `label`
* `hidden`
* `try`
* `lookAhead`
* `notFollowedBy`
* `eof`
* `token`
* `tokens`

A few words about the primitive parsers. Obviously some of them don't make sense to benchmark: `unexpected`, `label`, `hidden`. Others can be better tested via combinators from `Text.Megaparsec.Char` where they are used (`satisfy` and `string`).

List of non-primitive combinators (from `Text.Megaparsec.Combinator`):

* `between`
* `chainl`
* `chainl1`
* `chainr`
* `chainr1`
* `choice`
* `count`
* `count'`
* `endBy`
* `endBy1`
* `manyTill`
* `option`
* `sepBy`
* `sepBy1`
* `sepEndBy`
* `sepEndBy1`
* `skipMany`
* `skipSome`

These also can be benchmarked one benchmark per combinator. You can also write a couple of more complex benchmarks where various parts of library interact, if you wish. This may give more realistic results.

> Should it be in one big benchmark file?

Organize it as you wish. You can have one file to benchmark primitive combinators, another file for non-primitive combinators, and third for mixed cases. Finally you will need “entry-point” main file.

**Comment by tulcod** [comment]
One of `criterion`'s dependencies is `parsec`.

Additionally, one of its dependencies is `statistics`, which depends on `aeson`, which depends on `attoparsec`.

So to benchmark `megaparsec`, we need `parsec` and `attoparsec`.

But this is to be solved later, I guess. Let's make sure we don't introduce any dependency loops!

**Comment by mrkkrp** [comment]
@tulcod, when Megaparsec is finished, I could write a tutorial or something like that explaining why projects using Parsec should consider switching. However, for now most project will use Parsec by inertia, just because it's well known and thus quite popular (not surprising give it's 15 years old).

**Comment by tulcod** [comment]
This is what I have so far. Is it heading in the right direction?

```haskell
-- -*- Mode: Haskell; -*-
--
-- Criterion benmarks for Megaparsec, main module.
--
-- Copyright © 2015 Megaparsec contributors
--
-- Redistribution and use in source and binary forms, with or without
-- modification, are permitted provided that the following conditions are
-- met:
--
-- * Redistributions of source code must retain the above copyright notice,
--   this list of conditions and the following disclaimer.
--
-- * Redistributions in binary form must reproduce the above copyright
--   notice, this list of conditions and the following disclaimer in the
--   documentation and/or other materials provided with the distribution.
--
-- This software is provided by the copyright holders "as is" and any
-- express or implied warranties, including, but not limited to, the implied
-- warranties of merchantability and fitness for a particular purpose are
-- disclaimed. In no event shall the copyright holders be liable for any
-- direct, indirect, incidental, special, exemplary, or consequential
-- damages (including, but not limited to, procurement of substitute goods
-- or services; loss of use, data, or profits; or business interruption)
-- however caused and on any theory of liability, whether in contract,
-- strict liability, or tort (including negligence or otherwise) arising in
-- any way out of the use of this software, even if advised of the
-- possibility of such damage.

{-# LANGUAGE CPP #-}

module Main (main) where

import Criterion.Main

import Text.Megaparsec

-- Configuration parameters. Used in benchBunch

-- benchmarkSteps and benchmarkSize control the linear size distribution for the benchmark.
benchmarkSteps :: Int
#if BENCHMARK_STEPS
benchmarkSteps    = BENCHMARK_STEPS
#else
benchmarkSteps    = 5
#endif
benchmarkSize :: Int
#if BENCHMARK_SIZE
benchmarkSize = BENCHMARK_SIZE
#else
benchmarkSize = 1000
#endif

main :: IO ()
main = defaultMain benchmarks

benchmarks :: [Benchmark]
benchmarks =
  [
  -- First the primitives
    bgroup "string" $ benchBunch $ \str -> parse (string str) "" (repeat 'a')
  , bgroup "try-string" $ benchBunch $ \str -> parse (try $ string str) "" (repeat 'a')
  , bgroup "lookahead-string" $ benchBunch $ \str -> parse (lookAhead $ string str) "" (repeat 'a')
  , bgroup "notfollowedby-string" $ benchBunch $ \str -> parse (notFollowedBy $ string str) "" (repeat 'a')

  -- Now for a few combinators
  -- Major class instance operators: return, >>=, <|>, mzero
  -- TODO

  -- Non-primitive combinators follow below
  -- between : not worth testing, it's just `open *> p <* close`
  -- chainl : chainl1 p op <|> return x
  , bgroup "chainl" $ benchBunchNoMatch $ \str -> parse (chainl (string "a" >> return (1::Int)) (return (+)) 0) "" str
  , bgroup "chainl1" $ benchBunchNoMatch $ \str -> parse (chainl1 (string "a" >> return (1::Int)) (return (+))) "" str
  -- chainr : chainr1 p op <|> return x
  , bgroup "chainr" $ benchBunchNoMatch $ \str -> parse (chainr (string "a" >> return (1::Int)) (return (+)) 0) "" str
  , bgroup "chainr1" $ benchBunchNoMatch $ \str -> parse (chainr1 (string "a" >> return (1::Int)) (return (+))) "" str
  -- this is actually a nontrivial fold that we should benchmark
  , bgroup "choice" $
      [ bgroup "match" $ benchBunchNoMatch $ \str -> parse (choice (map (\c -> char c) str)) "" $ repeat 'b'
      , bgroup "nomatch" $ benchBunchNoMatch $ \str -> parse (choice (map (\c -> char c) str)) "" $ repeat 'b'
      ]
  -- TODO: count, but it has many cases
  -- count' : count n n
  -- TODO: endBy, endBy1, manyTill
  -- option : p <|> return x
  -- TODO: sepBy, sepBy1, sepEndBy, sepEndBy1
  -- skipMany : void $ many p
  -- skipSome : void $ some p
  ]

benchBunch :: (String -> b) -> [Benchmark]
benchBunch f =
  [ bgroup "match" $ benchBunchMatch f
  , bgroup "nomatch" $ benchBunchNoMatch f
  ]

benchBunchMatch :: (String -> b) -> [Benchmark]
benchBunchMatch f =
  [benchOne num | num <- [benchmarkSize,benchmarkSize*2..benchmarkSize*benchmarkSteps]]
    where
      benchOne num = bench (show num) $ whnf f (take num $ repeat 'a')

benchBunchNoMatch :: (String -> b) -> [Benchmark]
benchBunchNoMatch f =
  [benchOne num | num <- [benchmarkSize,benchmarkSize*2..benchmarkSize*benchmarkSteps]]
    where
      benchOne num = bench (show num) $ whnf f ((take (num-1) $ repeat 'a') ++ "b")
```

**Comment by mrkkrp** [comment]
@tulcod, a couple of notes here.

1. Do you absolutely need C++ preprocessor here? Can you handle it differently? See for example benchmarks for `pipes` library:

   https://github.com/Gabriel439/Haskell-Pipes-Library/tree/master/benchmarks

   You preprocessor sets value if preprocessor macro is already defined, else it defaults, why not just use raw value? Like this:

   https://github.com/Gabriel439/Haskell-Pipes-Library/blob/master/benchmarks/LiftBench.hs#L14-L15

2. Would it be more handy if you fork the repo and commit your changes there instead of copy/pasting them here? Even if your work is not complete, you could then amend last commit, etc.

3. Try to keep lines under 80 characters long.

Apart from these minor notes, I think it's OK, thanks for your work, I definitely have no time to do it myself :-D

**Comment by tulcod** [comment]
1. Well, to answer your question, obviously I don't _absolutely_ need the C preprocessor, but the C preprocessor is installed wherever GHC is installed, and this provides a convenient and easy way to configure the benchmarking a little bit, so I think it's justified.

2. Yes, this was just for quickly showing progress - I don't like pushing half commits to public repos.

3. Yes obviously :)

I'll finish this and send a PR.

**Comment by mrkkrp** [comment]
@tulcod, by the way, since you're using preprocessor, you could easily
create benchmarks to measure performance of various `Stream` types:
`String`, `Text` (strict and lazy), and `ByteString` (strict and lazy). This
is also very interesting thing to know.

Just use type `Parsec a`, which is defined per stream type in the following
files:

* `Text.Megaparsec.String`
* `Text.Megaparsec.Text`
* `Text.Megaparsec.Text.Lazy`
* `Text.Megaparsec.ByteString`
* `Text.Megaparsec.ByteString.Lazy`

Would this be possible?

**Comment by mrkkrp** [comment]
@tulcod, There is no rush, of course, but can you tell what is progress of benchmarking suite?

**Comment by tulcod** [comment]
@mrkkrp, yes, that is a very reasonable question. I am in the process of moving from the Netherlands to England, which is taking up a lot of my free time. This is still on my todo-list, and I hope to finish it this week. Apologies for the delay, I'll keep you up to date.

**Comment by mrkkrp** [comment]
@tulcod, Understandable, I'm going to move to different city soon and it involves some time-consuming activity as well :-)
