### ISSUE TITLE
Tutorial link in readme back to readme

### ISSUE THREAD

**Issue by madebyjeffrey** [mrkkrp/megaparsec#71]
In the readme it says under tutorial: "You can visit site of the project which has several tutorials that should help you to start with your parsing tasks. The site also has instructions and tips for Parsec users who decide to switch."  where the site of the project links back to the repository showing the readme, never actually showing a tutorial.

**Comment by mrkkrp** [comment]
There is a copy of `README.md` file on the site for people who first come to the site, not GitHub repo. There is however very visible menu at the boom that has the following sections:

* Tutorials (this is what you're probably looking for);
* Link to Hackage;
* Link to GitHub repo.

Maybe the menu fails to appear in your case? If so, tell me which browser you're using and is JavaScript enabled.

**Comment by madebyjeffrey** [comment]
Okay, it just wasn't very "discoverable" immediately without being told it was there. I am used to something like that being at the top.

**Comment by mrkkrp** [comment]
Yeah, maybe I just need to move it to more *standard* place :-)
