### ISSUE TITLE
Support for transformers-0.5 release

### ISSUE THREAD

**Issue by hvr** [mrkkrp/megaparsec#78]
See http://hackage.haskell.org/package/transformers-0.5.0.0

(NB: you don't need a new full hackage release upload if it turns out all that's needed is a `.cabal`-revision)

**Comment by mrkkrp** [comment]
Thanks for the heads-up. Corrected in f69661a9 and updated on Hackage.

**Comment by hvr** [comment]
thanks

btw, leaving off upper bounds is rather risky, as you effectively chose to ignore an important signalling mechanism for upstream maintainers notifying you of semantic changes which don't show at the type-level. This has happened in the past already and lead to hard to debug issues.
