### ISSUE TITLE
Treat `'\r'` as an EOL sequence

### ISSUE THREAD

**Issue by recursion-ninja** [mrkkrp/megaparsec#79]
When parsing ***ancient*** files often `'\r'` is used as the EOL sequence, not `"\r\n"` or `'\n'`.

I have found this antiquated EOL `'\r'` sequence from:

 - Macintosh operating system files prior to Mac OS X

 - Files saved from some older Microsoft software written for Mac OS X

I'm requesting:

 - Add the `'\r'` character to the `eol` combinator definition

 - Consider `'\r'` as a newline when printing the file line/column on a parse failure.

I'm not sure there are any downsides to this, but I'm open to a counter example.

**Comment by mrkkrp** [comment]
This may be not a good idea because `"\r\n"` sequence that is used on Windows will be treated as *two* newlines. To solve you problem I would recommend to process the files first (replacing `'\r'` with `'\n'`) and then parse the result.

**Comment by recursion-ninja** [comment]
Preprocessing the stream to replace `'\r'` would preclude using `parseFromFile`, which isn't a deal breaker, but it is not preferred (I think).

The changes to `eol` would be straight forward:

    eol = (pure <$> newline) <|> crlf <|> string "\r" <?> "end of line"

However, I think that the issue you raised is resolvable with a single character lookahead:

    updatePosChar :: Int        -- ^ Tab width
                  -> SourcePos  -- ^ Initial position
                  -> Char       -- ^ Character at current position
                  -> Maybe Char -- ^ Character at next position
                  -> SourcePos
    updatePosChar width (SourcePos n l c) curr next=
      case (curr, next) of
        -- In the first case we don't increment the line number,
        -- We will increment it on the subsequent `updatePosChar` call
        -- when `'\n'` is in the current position
        ('\r', Just '\n') -> SourcePos n l 1
        ('\r', _        ) -> SourcePos n (l + 1) 1
        ('\n', _        ) -> SourcePos n (l + 1) 1
        ('\t', _        ) -> let w = if width < 1 then defaultTabWidth else width
                             in SourcePos n l (c + w - ((c - 1) `rem` w))
        _                 -> SourcePos n l (c + 1)

With such a lookahead, files originating from Windows will still have their EOL sequences handled appropriately. That would constitute a non-trivial change, but I think it would greatly improve compatibility with files from any origin!

**Comment by mrkkrp** [comment]
`parseFromFile` is defined trivially and it's no better than manual reading of file and parsing of its contents, it's just a shortcut.

Modifying of `eol` is simple, but your proposition for `updatePosChar` would increase complexity (and not only of that function) and probably degrade performance for no real benefit.

**Comment by shaleh** [comment]
Perhaps the solution is to include "carriage return eol" as a possible parser? It would be used in place of ``eol`` in files known to include carriage return only lines.

**Comment by mrkkrp** [comment]
Problem is not in parsing, it's in incrementing of textual position.

**Comment by mrkkrp** [comment]
@recursion-ninja, Have you resolved your problem?

**Comment by recursion-ninja** [comment]
I'm still experimenting with preprocessing the stream. I'm not terribly optimistic because I can't efficiently reconstruct the original stream type.

    preprocess :: Stream s Char => s -> String

Not

    preprocess :: Stream s Char => s -> s

Because I can't efficiently `cons` except for with a List. I also can't use `filter` because of the lookahead...

**Comment by mrkkrp** [comment]
Why don't you just read the whole file in as `Text` for example, run [`replace`](https://github.com/chrisdone/structured-haskell-mode) on the whole thing and only then feed it into parser? I don't understand. E.g.:

```haskell
main :: IO ()
main = do
  let myFile = "my-ancient-file.txt"
  input <- T.replace "\r" "\n" <$> T.readFile myFile
  … <- parse myParser myFile input
  …
```

**Comment by recursion-ninja** [comment]
I was thinking too abstractly. I am pretty sure what you suggested will work. I'll get back to you next week with a definite yea or nay.

**Comment by recursion-ninja** [comment]
I'm not sure how the link to `[replace](https://github.com/chrisdone/structured-haskell-mode)` is related to the problem. I'm probably missing something simple on that page...?

**Comment by neongreen** [comment]
@recursion-ninja: I think @mrkkrp meant this [`replace`](http://hackage.haskell.org/package/text-1.2.2.0/docs/Data-Text.html#v:replace).

**Comment by mrkkrp** [comment]
Sorry, I must have inserted wrong link.

**Comment by mrkkrp** [comment]
I'm closing this, since the conversation has got rather long for such a trivial thing. I believe there is nothing that needs to be changed in Megaparsec to better handle this rather rare use-case.
