### ISSUE TITLE
Q: Recommended way to handle source-locations for languages which support include files?

### ISSUE THREAD

**Issue by hvr** [mrkkrp/megaparsec#83]
I have been wondering what the recommended way to handle languages with include files is.

I currently have a stream of tokens I pass to the parser (I have a separate CPP pass, which I want to keep that way to keep the `ParsecT` stack `IO`-less), with a special token to denote file changes, i.e. 

    data Token = ... | SourcePush FilePath | SourcePop | ...`

With Parsec I would have maintained a `StateT`  stack of `SourcePos`itions updated everytime the respective `Token` came along. However, since with `megaparsec` the user-state is gone, I'm now wondering if there's a different/better/recommended way to handle this case without having to add a `StateT` around `ParsecT` to emulate Parsec's custom state.

PS: would it be conceivable if megaparsec came with builtin support for maintaining a `SourcePos` stack? This would probably simplify handling include files a lot, unless I'm missing something.

PS2: what if handling  `SourcePos` updating would move away from the `token` primitive into the  `Stream` class? Why is `SourcePos` updating a concern of the `token` function?

**Comment by mrkkrp** [comment]
For this you definitely need custom backtracking state and putting `ParsecT` inside `StateT` is the only option that comes to mind. Can you elaborate why exactly you consider it not the best solution? Everything in Megaparsec works with any instance of `MonadParsec`, so I don't see problems with this approach, should be just as easy as Parsec's user state.

----

> PS: would it be conceivable if megaparsec came with builtin support for maintaining a SourcePos stack? This would probably simplify handling include files a lot, unless I'm missing something.

This is an interesting idea, although I don't see how it can be done in a backward-compatible way, because constructor of `State` is public (not a bad thing per se, because we support incremental parsing now and construction/manipulation of `State` may be of interest for users).

Compatibility concerns aside, we could easily have `[SourcePos]` instead of `SourcePos` in `State` and then switching contexts would be as trivial as pushing to and popping from the list. I see no way it can affect performance either.

----

> PS2: what if handling SourcePos updating would move away from the token primitive into the Stream class? Why is SourcePos updating a concern of the token function?

It's Parsec's legacy. Somehow it didn't come to my mind when I reorganized things when I started Megaparsec. I love the idea, but again it will break backward-compatibility.

Thanks for the input, I think these changes/features will be available in Megaparsec 5.0.0, which is going to be the next release after upcoming Megaparsec 4.4.0.

**Comment by mrkkrp** [comment]
Note to self: consider elimination of `updatePosString` in version 5.0.0. `tokens` should handle this automatically knowing how to advance `SourcePos` for one character.

**Comment by mrkkrp** [comment]
One more note to self: should be not `[SourcePos]`, but `NonEmpty SourcePos`, since `semigroups` will be in `base` anyway.

**Comment by hvr** [comment]
> For this you definitely need custom backtracking state and putting ParsecT inside StateT is the only option that comes to mind. Can you elaborate why exactly you consider it not the best solution?

Mostly because it seems contrived; I have to extract the state, somehow figure out the current/next token (and the `token` primitive expects a pure source-pos-advancing function for that), and inject the off-band computed new source-position into the `token` function.

Currently I ended up with the following hack which seems less hackier than the `StateT` version, but still seems unsatisfying...

```haskell
type PliParsec = Parsec TokenStream
type SrcPosStack = [SourcePos] -- better yet: NonEmpty
data TokenStream = TokenStream SrcPosStack [Token]

-- | Next-position + token
data NPosToken = NPosToken !Token SourcePos  deriving Show

instance P.Stream TokenStream NPosToken where
    uncons (TokenStream _   [])     = Nothing
    uncons (TokenStream pos (t:ts)) = Just (NPosToken t pos0, TokenStream pos' ts)
      where
        pos'@(pos0:_) = posAdvTok t pos

-- | Advance 'SrcPosStack' by input 'Token'
posAdvTok :: Token -> SrcPosStack -> SrcPosStack

-- | Hack for
pliToken :: (Token -> Bool) -> PliParsec Token
pliToken p = getToken <$> token (\_ _ -> getNPos) (maybe (Left []) Right . justIf (p . getToken))
  where
    getToken (NPosToken t _)  = t
    getNPos  (NPosToken _ np) = np
```

**Comment by mrkkrp** [comment]
I agree that current position-advancing/changing methods are not as flexible as they should be for users who work with streams of non-character tokens. I have another issue opened about somewhat related thing. I think this problem will be properly addressed in the future release of Megaparsec.

**Comment by mrkkrp** [comment]
I'm currently working on this feature as part of #99 (which includes quite a few cool changes). Stack of positions is already supported in `SourcePos` and it's included in `State`. The only missing part is actual API to push files to the stack and pop them from the stack. The only idea I have so far is to make `updatePos` return something that would indicate pushing or popping together with newly calculated positions.

Currently `updatePos` looks like this:

```
updatePos
  :: Proxy s         -- ^ Proxy clarifying stream type
  -> Pos             -- ^ Tab width
  -> SourcePos       -- ^ Current position
  -> Token s         -- ^ Current token
  -> (SourcePos, SourcePos) -- ^ Actual position and incremented position
```

However, this would make this feature only usable for users who work with custom streams of tokens, so I'm not sure this is the right API. What do you think, do you have specific ideas how switching should be done?

**Comment by chamini2** [comment]
Maybe I'm not understanding the problem right, but shouldn't the pop and push operations be done separately from `updatePos`?

Maybe you read a string of tokens that indicates to include a new file, so you run:
```
pushSourcePos 
  :: MonadParsec s m t 
  => String                 -- new file path
  -> Int                    -- line
  -> Int                    -- column
  -> m ()

```
That pushes a new `SourcePos` to continue parsing right there. Then, when the file is done parsing, you run:
```
popSourcePos :: MonadParsec s m t => m ()
```
Which just pops it.


*****

Just trying to give a different view on the problem, but I'm not sure if it makes sense for this issue; if not, my bad. Hope it helps.

**Comment by chamini2** [comment]
I would imagine the use being like:

```
parseIncludes = many includeFile
    where
        includeFile = do
            getTk (== "include")
            incPath <- getTk (const True)
            let pos = newPos incPath 1 1
            pushPosition pos
            incAST <- parseFile
            popPosition
```

**Comment by mrkkrp** [comment]
@chamini2, Thanks for your comments. As I understand, the main motivation behind this feature is to avoid `IO` inside of `ParsecT`, so the parser monad could be pure.

**Comment by mrkkrp** [comment]
But I agree, I don't like making `updatePos` too heavyweight, so the operations will probably be added as separate monadic actions.

**Comment by chamini2** [comment]
@mrkkrp, I understand the `IO` problem, didn't see it before. I guess you could pre-process the input to search for all `include`s, so you have the files' contents while parsing, maybe in a `Map FilePath String`. But that's more of a specific problem of usage of the library, not a problem with Megaparsec.
