### ISSUE TITLE
Provide `eitherP`-like combinator

### ISSUE THREAD

**Issue by hvr** [mrkkrp/megaparsec#85]
Attoparsec provides this convenient combinator which I keep missing and defining for parsec and megaparsec in my projects. It may be useful to include this in `megaparsec` (modulo name-bikeshedding):

```haskell
-- | Combine two alternatives.
eitherP :: (Alternative f) => f a -> f b -> f (Either a b)
eitherP a b = (Left <$> a) <|> (Right <$> b)
```

**Comment by mrkkrp** [comment]
This will definitely go into Megaparsec 4.4.0.
