### ISSUE TITLE
How to cite this software?

### ISSUE THREAD

**Issue by chamini2** [mrkkrp/megaparsec#88]
Hello, I'm currently writing my thesis and I want to reference this software, who should I list as the author(s), Mark Karpov?, or who from the `AUTHOR.md` file?

**Comment by mrkkrp** [comment]
As many open-source projects, Megaparsec has many authors. For your purposes, shorter list may be used, I would use this version:

> Mark Karpov, Paolo Martini, Daan Leijen

Where I'm the principal author of Megaparsec, Daan Leijen is the original author of Parsec, and Poalo Martini is also listed as copyright holder in Parsec docs, so I guess his contribution to Parsec is substantial.

**Comment by chamini2** [comment]
Thanks.
