### ISSUE TITLE
Nested block comments

### ISSUE THREAD

**Issue by zachhalle** [mrkkrp/megaparsec#96]
The option to specify that block comments are allowed to be nested in the lexer would be nice.

**Comment by mrkkrp** [comment]
Would be nice indeed. We currently have `skipLineComment` and `skipBlockComment`, I think we could add something like `skipBlockComment'` or `skipBlockCommentNested` to handle possibly nested block comments. Care to try a PR?

**Comment by zachhalle** [comment]
I'll see if I can put an implementation together and then submit

**Comment by zachhalle** [comment]
This is my prototype:

`skipBlockCommentNested :: MonadParsec s m Char
  => String            -- ^ Start of block comment
  -> String            -- ^ End of block comment
  -> m ()
skipBlockCommentNested start end = helper (1 :: Int)
  where 
    helper 0 = return ()
    helper k = p >> (
        void $ manyTill anyChar $
            try (p >> helper (k+1)) 
            <|> (n >> helper (k-1))
        )
    p = string start
    n = string end`

It must be wrong, though I'm not sure why, because when I try to parse the following I get an error.

`avg a b c = 
  let sum = a + b + c in sum

  /- 
   -block comment
       /- 
        - nested block
        -/
  -/`
The error I get is: "unexpected '-', expecting expression"

**Comment by mrkkrp** [comment]
I guess this should do the trick (this is untested):

```haskell
-- | @skipBlockCommentNested start end@ skips possibly nested block comment
-- starting with @start@ and ending with @end@.

skipBlockCommentNested :: MonadParsec s m Char
  => String            -- ^ Start of block comment
  -> String            -- ^ End of block comment
  -> m ()
skipBlockCommentNested start end = p >> void (manyTill e n)
  where p = C.string start
        n = C.string end
        e = skipBlockCommentNested start end <|> void C.anyChar
```

**Comment by chamini2** [comment]
How about changing the type of `skipBlockComment` to include a `Bool` that indicates if it's nested or not? They're both block comments.

**Comment by mrkkrp** [comment]
I prefer to keep things backward-compatible where possible.
